### ISSUE TITLE
some improvements to getRange

### ISSUE THREAD

**Issue by fergiemcdowall** [OfficeDev/office-js-docs#1000]
Documentation for `Range.getRange` (https://github.com/OfficeDev/office-js-docs/blob/WordJs_1.3_Openspec/reference/word/range.md#getrangerangelocation-string) currently reads like this:

> Optional. Optional. The range location can be 'Whole', 'Start', 'End', 'After' or 'Content'. Possible values are: Whole, Start, End, Before, After, Content

 * "Optional" is there twice.
 * It is unclear if `Before` is a valid value or not.
 * The effects of the possible range location values are not described, neither is usage. Needs an example and some more explanation.

(My use case is that I am trying to find out how to read from the beginning of a sentence up to the selection cursor. Maybe I am looking in the wrong place? If so- where should I be looking?)

**Comment by sumurthy** [comment]
This needs to be assigned to the engineer who can fix this in the code comment. The double optional is a result of adding optional in the code and tool appending it again.

**Comment by kbrandl** [comment]
Closing this issue, as it was fixed some time ago (in the new docs: https://docs.microsoft.com/en-us/javascript/api/word/word.range?view=office-js).
