### ISSUE TITLE
Error during "Project Build"

### ISSUE THREAD

**Issue by cognologixguru** [OfficeDev/office-js-docs#1006]
Article:
Enable single sign-on for Office Add-ins
Issue: 
When I tried to build a solution, the error has been shown : 
1. Error    CS0234    The type or namespace name 'Identity' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)   ..\ValuesController.cs    Line #7

2. Error        The element 'VersionOverrides' in namespace 'http://schemas.microsoft.com/office/taskpaneappversionoverrides' has invalid child element 'WebApplicationId' in namespace 'http://schemas.microsoft.com/office/taskpaneappversionoverrides'. List of possible elements expected: any element in namespace 'http://schemas.microsoft.com/office/taskpaneappversionoverrides/1.1'.    Office-Add-in-ASPNET-SSO   ..\Office-Add-in-ASPNET-SSO.xml    Line#142

3. When I changed sequence, it shows -
The element 'OfficeApp' in namespace 'http://schemas.microsoft.com/office/appforoffice/1.1' has invalid child element 'WebApplicationId' in namespace 'http://schemas.microsoft.com/office/appforoffice/1.1'. List of possible elements expected: any element in namespace 'http://www.w3.org/2000/09/xmldsig#'.

Expected Scenario : 
Check logged in User. If already logged in "in Office Word/Excel" desktop application, get access_token and if not then pop-up for login and fetch access_token only "within desktop application" and not in Web Browser.

**Comment by Rick-Kirkham** [comment]
Errors #2 and #3 mean that your version of Visual Studio does not recognize the new markup. See the Prerequisites section of the article for the version that you need. If you more than one version of VS installed, it might be that an older version launches by default when you open the .sln file.

Error #1 means that for some reason, Microsoft.Identity.Client.dll (the MSAL library), which is listed in the packages.config at the root of the project, did not install. Go to the Nuget Package Manager and install the version 1.1.0-Preview or later.

**Comment by cognologixguru** [comment]
Hello Rick,
I tried same code to build on Visual Studio 2017 (Community Edition) but shows same error as I mentioned above.

**Comment by Rick-Kirkham** [comment]
The community edition is fine, but you need the _preview_: As noted in the Prerequisites section of the walkthrough for the ASP.NET version: "Visual Studio 2017 Version 15.3.0 **Preview 3** or later."

But the markup is changing very soon. What build of Office do you have? The markup is going to change with version 1708 8430.nnnn

**Comment by cognologixguru** [comment]
Visual Studio Community 2017 Preview (2)
15.3.0 Preview 7.0
Free, fully-featured IDE for students, open-source and individual developers
and
Office Version 1701 Build (7766.2099)

**Comment by Rick-Kirkham** [comment]
Your Office version is too old. From the Prerequisites: 

"Office 2016, Version 1704, build 8027.nnnn or later (the Office 365 subscription version, sometimes called “Click to Run”). You might need to be an Office Insider to get this version. For more information, see Be an Office Insider."

**Comment by cognologixguru** [comment]
Hi Rick,
I tried with **Visual Studio 2017 Preview (7.1) Version 15.3.0 and Subscription Product MS Office 365 Version 1708 (Build 8431.2022 Click-to-run)** but facing errors as mentioned in following file.

[SSO-Build Error.docx](https://github.com/OfficeDev/office-js-docs/files/1233197/SSO-Build.Error.docx)

**Comment by Rick-Kirkham** [comment]
The errors about Microsoft.Identity.Client mean that Visual Studio failed to install it, even though it is in the packages.config. Other people have seen the same thing. The solution is to manually install it with the Nuget Package Manager. Just search for Microsoft.Identity.Client and install it in the web project. 

The error about manifest markup means that your version of Visual Studio does not support the new manifest markup. The markup has changed since this issue was created. There is a workaround for this problem described in the article: [Create SSO Office Add-ins ASP.NET](https://dev.office.com/docs/add-ins/develop/create-sso-office-add-ins-aspnet) (which has been updated to account for the new markup). Scroll down to step 6 of the **Configure the add-in** section.
