### ISSUE TITLE
Uniform way to detect when Office is about to close

### ISSUE THREAD

**Issue by jwesly** [OfficeDev/office-js-docs#1012]
I don't know if anything currently exists to solve this but it would be super useful to have an event that is called when the Add-in is about to close. My specific use case is saving some session information on exit. In other words, is there either a JS event or an analog of Office.initialize for when Excel closes?

**Comment by Rick-Kirkham** [comment]
This is a great idea, but it is not supported right now. Please go to [Office Developer Voice](https://officespdev.uservoice.com/) and make this suggestion. (But first search to see if its already been made and, if so, vote it up.)
