### ISSUE TITLE
Error calling Office.context.auth.getAccessTokenAsync

### ISSUE THREAD

**Issue by vkulov** [OfficeDev/office-js-docs#1013]
`{"status":"failed","error":{"name":"Permission Denied","message":"You don't have sufficient permissions for this action.","code":7000}}`

I seem to lack permissions to call auth.getAccessTokenAsync?

I'm testing locally on an outlook add-in in Outlook 2016 Desktop App

**Comment by OriAmir** [comment]
You set 'ReadWriteMailbox '  permissions on manifest?

https://docs.microsoft.com/en-us/outlook/add-ins/understanding-outlook-add-in-permissions

**Comment by vkulov** [comment]
Yes, we did

**Comment by Rick-Kirkham** [comment]
@vkulov 
Please raise this issue on StackOverflow and be sure to tag it "office-js". The Issues for this repo are used to report problems with the documentation. Technical questions should be raised on StackOverflow. Be sure to add some details about the flow of steps that lead to the error and where you see the error. Also, be sure that you are familiar with the article [SSO in Office Add-ins](https://dev.office.com/docs/add-ins/develop/sso-in-office-add-ins) and it's child articles. Thanks.
