### ISSUE TITLE
Word add-in js getHtml() function not return all fully style

### ISSUE THREAD

**Issue by OriAmir** [OfficeDev/office-js-docs#1014]
Hey I write word add-in in JS using this API: https://dev.office.com/reference/add-ins/word/word-add-ins-reference-overview

everything OK but when I use function body.getHtml() I get almost everything include all style but for example table of content is not with style, and when I use body.insertHtml() all style of table of content is not exist.

I success to get all style with body.getOoxml() function but it's very very long when I compare it to the html..

What could I do?

thank you

**Comment by Rick-Kirkham** [comment]
@OriAmir 
Please raise this question on StackOverflow and be sure to tag it "office-js". That way everyone encountering the problem will see the answers. The issues for this repo are intended for reporting problems with the documentation.
