### ISSUE TITLE
Topic does not appear in TOC

### ISSUE THREAD

**Issue by Rick-Kirkham** [OfficeDev/office-js-docs#1016]
Article:
https://dev.office.com/docs/add-ins/develop/persisting-add-in-state-and-settings

Issue: 
It does not appear in the TOC.

**Comment by Lauragra** [comment]
This article does appear in the TOC, if you expand Develop, and then expand Office JavaScript API, click the TOC entry "Persist state and settings". In some cases when the GitHub folder structure does not match the TOC structure on the site, a topic is not highlighted in the TOC when you land on it from an external link. This is a known bug.
