### ISSUE TITLE
Edit in GitHub link is broken

### ISSUE THREAD

**Issue by Hongbo-Miao** [OfficeDev/office-js-docs#1019]
Article:
https://dev.office.com/reference/add-ins/excel/loadoption
https://dev.office.com/reference/add-ins/excel/requestcontext
https://dev.office.com/reference/add-ins/excel/trackedobjectscollection
https://dev.office.com/reference/add-ins/excel/functions

Issue: 
If you click **Edit in GitHub**, it goes to a page which does not exist.

**Comment by Lauragra** [comment]
These topics don't exist in the Excel folder in the repo. It's possible that they have been removed since they were originally published; if so, we need to remove them from the Excel section of the TOC and redirect the URLs on the site.

**Comment by lindalu-MSFT** [comment]
@kbrandl @sumurthy Please advise. Should I remove the topics from the TOC or where they moved somehow? This seems like a quick fix once you tell me what to do.

**Comment by kbrandl** [comment]
@sumurthy -- can you provide guidance here as to what should be done (since your tool auto-generates the Excel reference docs)?  Or would you suggest that we postpone addressing this issue, if it'll be addressed/fixed automatically whenever the docs are moved to docs.microsoft.com (and the reference docs (including TOC) are generated automatically from the d.ts file)?

**Comment by lindalu-MSFT** [comment]
Sorry to be a nag about all this but I went through all the GitHub open issues and it seems that there are a few things that we can easily address with a teeny time hit that would make a better experience for our customers. When things are broken, they loose confidence. Many of these things started before I came on board and now I’m here to help fix them!

**Comment by sumurthy** [comment]
This is a legitimate issue. Though this should be addressed with the new docs process that's being worked on - except https://dev.office.com/reference/add-ins/excel/functions
The functions page is handcrafted and should be preserved through another way. We should probably write an advanced topic for this in Excel.

**Comment by kbrandl** [comment]
Thanks for the feedback, @sumurthy.  

I'll take ownership of this issue and have opened a VSO work item for us to refactor the [Worksheet Functions](https://dev.office.com/reference/add-ins/excel/functions) page into a conceptual article under **Excel >> Advanced concepts**.

**Comment by kbrandl** [comment]
Closing this issue, as the Office JS API Reference docs have now been migrated to a new location (https://docs.microsoft.com/en-us/javascript/api/overview/office?view=office-js) where this issue is no longer relevant.
