### ISSUE TITLE
Files do not show

### ISSUE THREAD

**Issue by Hongbo-Miao** [OfficeDev/office-js-docs#1020]
These files in the folder
https://github.com/OfficeDev/office-js-docs/tree/master/reference/excel
do no show in the TOC of
https://dev.office.com/reference/add-ins/excel/application

- bindingdatachangedeventargs.md
- bindingselectionchangedeventargs.md
- cellvalueconditionalformat.md
- colorscaleconditionalformat.md
- conditionalcellvaluerule.md
- conditionalcolorscalecriteria.md
- conditionalcolorscalecriterion.md
- conditionaldatabarnegativeformat.md
- conditionaldatabarpositiveformat.md
- conditionaldatabarrule.md
- conditionalformat.md
- conditionalformatcollection.md
- conditionalformatrule.md
- conditionaliconcriterion.md
- conditionalpresetcriteriarule.md
- conditionalrangeborder.md
- conditionalrangebordercollection.md
- conditionalrangefill.md
- conditionalrangefont.md
- conditionalrangeformat.md
- conditionaltextcomparisonrule.md
- conditionaltopbottomrule.md
- customconditionalformat.md
- customxmlpart.md
- customxmlpartcollection.md
- customxmlpartscopedcollection.md
- databarconditionalformat.md
- filtercriteria.md
- filterdatetime.md
- formatprotection.md
- icon.md
- iconsetconditionalformat.md
- pivottable.md
- pivottablecollection.md
- presetcriteriaconditionalformat.md
- rangereference.md
- rangeview.md
- rangeviewcollection.md
- selectionchangedeventargs.md
- setting.md
- settingcollection.md
- settingschangedeventargs.md
- sortfield.md
- textconditionalformat.md
- topbottomconditionalformat.md

**Comment by Lauragra** [comment]
Assigning to Sudhi. I don't think that every file in the Excel folder needs to be included in the TOC. @sumurthy , can you follow up and let me know which of these (if not all) you want to add to the TOC?

**Comment by lindalu-MSFT** [comment]
@Lauragra @sumurthy This is still open, should I simply add the missing ones to the ReferenceTOC? There's only a few missing.

**Comment by Lauragra** [comment]
@sumurthy , are you changing the approach and included all files in the TOC?

**Comment by sumurthy** [comment]
This is fixed in the new TOC.
