### ISSUE TITLE
Word api sending http request in IE11 DOMException Error

### ISSUE THREAD

**Issue by PawelK95** [OfficeDev/office-js-docs#1033]
I'm currently developing javascript add-in with word api for Microsoft Office Professional 2016. On frontend side there is angular 4. I have problem with Internet Explorer 11 when I'm trying to send a http request (e.g. get, post). In other browsers everything works fine but in IE I get this error:

object DOMException]{ABORT_ERR: 20, code: 11, constructor: DOMException {...}, DATA_CLONE_ERR: 25, DOMSTRING_SIZE_ERR: 2, HIERARCHY_REQUEST_ERR: 3, INDEX_SIZE_ERR: 1, INUSE_ATTRIBUTE_ERR: 10, INVALID_ACCESS_ERR: 15, INVALID_CHARACTER_ERR: 5, INVALID_MODIFICATION_ERR: 13, INVALID_NODE_TYPE_ERR: 24, INVALID_STATE_ERR: 11, message: "InvalidStat...", name: "InvalidStat...", NAMESPACE_ERR: 14, NETWORK_ERR: 19, NO_DATA_ALLOWED_ERR: 6, NO_MODIFICATION_ALLOWED_ERR: 7, NOT_FOUND_ERR: 8, NOT_SUPPORTED_ERR: 9 ...}

Does anybody knows how to solve this problem?

Thank You for reply:)

**Comment by lindalu-MSFT** [comment]
Hi, can you post this question to StackOverflow and tag it office.js?

This issues forum is for actual documentation bugs. YOu'll get a better answer from the broader community on StackOverflow. 

THanks,
Linda

closing issue, reopen if documentation bug needs addressing.
