### ISSUE TITLE
ConfidentialClientApplication not fount

### ISSUE THREAD

**Issue by gomteshhatgine** [OfficeDev/office-js-docs#1037]
Issue: 
I have add all related usings:
using Microsoft.Identity.Client;
using System.IdentityModel.Tokens;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Web.Http;
using Office_Add_in_ASPNET_SSO_WebAPI.Helpers;
using Office_Add_in_ASPNET_SSO_WebAPI.Models;

then also for the line
 ConfidentialClientApplication cca =
                                new ConfidentialClientApplication(ConfigurationManager.AppSettings["ida:ClientID"],
                                                                  "https://localhost:44355", clientCred, null, null);
               
having error such that "The type or namespace name  ConfidentialClientApplication  could not be found - 

Please check this code attached::
[code.txt](https://github.com/OfficeDev/office-js-docs/files/1217450/code.txt)

**Comment by Rick-Kirkham** [comment]
@gomteshhatgine 
It looks like you're having a problem with the sample at [Office-Add-in-ASPNET-SSO](https://github.com/OfficeDev/Office-Add-in-ASPNET-SSO). Please go to that repo and raise this issue where it will be seen sooner by people who can help. The issues for this office-js-docs repo are really intended to report problems with the documentation.
