### ISSUE TITLE
Outlook addin is not supported when outlook custom forms are installed

### ISSUE THREAD

**Issue by adhorvath** [OfficeDev/office-js-docs#1046]
Hello,

I'm opening this issue here on documentation side, because I did not find any part, where it is described. I would like to validate information, which is provided to me on stackoverflow.

In short I'm implementing outlook addin, which is using ribbon button together with task pane. However, in my case there is also a custom outlook form installed. According to the answer on stackoverflow **addins are not supported, if custom forms are installed**. Is this true? I did not find any documentation part, which is describing that kind of limitation.

If so then it would be good to include it into the documentation, because error how Outlook behaves in this case is misleading and in my opinion should be documented.

Here is the link for the [stackoverflow](https://stackoverflow.com/questions/44966974/outlook-mailapp-ribbon-button/45098272?noredirect=1#comment78328003_45098272) question.

Could you validate this info or provide me a documentation, where it is included?

**Comment by adhorvath** [comment]
Hi, 
@jasonjoh is there any new info regarding to this issue?

**Comment by jasonjoh** [comment]
No there isn't. This issue is not documented currently. I'll work with the engineering team to get the specifics and document the limitation.

I want to be clear here though, because your statement isn't quite correct if read out of context :). Add-ins are supported with custom forms installed. However, they cannot activate on a specific item that uses a custom form.

So even if you have custom forms, add-ins will still work on normal items.

**Comment by adhorvath** [comment]
Yes, you are right, the issue description is not 100% punctual and may be confusing if somebody is reading it out of context.  By the way you already confirmed, that the limitation what I wanted to know. ;) Thx. Is there any future date, when this part will be documented?

**Comment by jasonjoh** [comment]
I'm working on it. I'll update/close this issue once it's done.

**Comment by lindalu-MSFT** [comment]
@jasonjoh Labeling this as Documentation: Request. Is this issue resolved?

**Comment by adhorvath** [comment]
Hi,

is some change regarding to this issue? Thank you.

**Comment by jasonjoh** [comment]
Sorry for the delay. Custom forms were added to the list of items that add-ins won't activate for. Here's the PR: https://github.com/OfficeDev/outlook-dev-docs/pull/131
