### ISSUE TITLE
How do I publish my Excel add-in?

### ISSUE THREAD

**Issue by avi12** [OfficeDev/office-js-docs#1047]
Hey. Recently I developed an add-in for Excel, and now I want to publish it - not to the Office Add-ins store, but to a specific person.
I need to publish it as easily as possible, for free, as well as make it easy to install.
How do I do this?

Thanks a lot!

**Comment by Rick-Kirkham** [comment]
By 'publish' do you mean deploy the add-in manifest or host the add-in's web application? If you are only asking about deploying the manifest, you can just send it to that person. (S)he then puts it into a shared folder and adds that folder to the Trusted Catalogs in Office. (S)he can then install the add-in from the **Add-ins** on the ribbon of Office.
If you mean hosting the add-in's web application, you have all the options you would have with any web application. NodeJS or IIS, local server or cloud service, etc.
