### ISSUE TITLE
Requirement Set Link not found

### ISSUE THREAD

**Issue by cognologixguru** [OfficeDev/office-js-docs#1063]
Article:
specify-office-hosts-and-api-requirements.md
Issue: 
Requirement Set Link not found. 404-Page Not Found error was shown.
https://github.com/OfficeDev/office-js-docs/blob/Addin_SSO_OpenSpec/reference/office-add-in-requirement-sets.md

**Comment by lindalu-MSFT** [comment]
@Lauragra This URL needs a redirect, correct? The correct URL is 
https://github.com/OfficeDev/office-js-docs/blob/master/reference/requirement-sets/office-add-in-requirement-sets.md
What are the steps to redirect?

**Comment by lindalu-MSFT** [comment]
@cognologixguru The correct URL is:
https://github.com/OfficeDev/office-js-docs/blob/master/reference/requirement-sets/office-add-in-requirement-sets.md
