### ISSUE TITLE
GetAccessTokenAsync() is not working in Office Version : 16.0.6741.2048

### ISSUE THREAD

**Issue by cognologixguru** [OfficeDev/office-js-docs#1066]
Article:
office.context.auth.getAccessTokenAsync.md
Issue: 
Unable to fetch access_token

I am trying this sample for my add-in application. I am using following setups to perform this task.
Visual Studio 2017
Office Version : 16.0.6741.2048

My Manifest file : 
[WordWebAddIn-SingleSignOn.txt](https://github.com/OfficeDev/office-js-docs/files/1266143/WordWebAddIn-SingleSignOn.txt)

**Comment by cognologixguru** [comment]
Unable to fetch access_token in Office Version : 1707
Visual Studio 2017
Office Version : 1707 (Build 8326.2096)

**Comment by Rick-Kirkham** [comment]
@cognologixguru 
Please raise this issue in the repo for the sample you mentioned. This repo is intended for reporting errors in documentation.
