### ISSUE TITLE
Word add-in walkthrough doesn`t explain how to generate a GUID

### ISSUE THREAD

**Issue by fergiemcdowall** [OfficeDev/office-js-docs#1067]
Article: https://dev.office.com/docs/add-ins/word/word-add-ins?product=word

Point 5 says: 

> Generate a GUID and replace the value in the OfficeApp/Id element with your GUID

How do you generate a GUID?

**Comment by Rick-Kirkham** [comment]
I'll create a bug to add this info to the article. In the meantime, the answer is that you can use any of the tools that generate random GUIDs. Just search the internet for "Generate GUID" or "Get GUID".

**Comment by Rick-Kirkham** [comment]
The article has been updated in the source and the new version should appear online in the next few days.

**Comment by fergiemcdowall** [comment]
👍
