### ISSUE TITLE
Several Issues with the "new" Office Add-in docs on dev.office.com; please keep MSDN version for now

### ISSUE THREAD

**Issue by jbarr33** [OfficeDev/office-js-docs#107]
The new docs in their current state on dev.office.com need some improvements to match the same level of help as the previous docs on MSDN. Here's just a few the issues encountered so far with the new docs that should be addressed:  1) you can't open links in new tab or window as you get "page not found" (this is the most frustrating problem) and many links are just broken, 2) the docs don't take up my entire window width on my large screen monitor (I have the space, use it), 3) the altering color of table rows (white/blue) makes it less readable and is distracting and text should be top-aligned, 4) the browser back/forward buttons break most of the time, 5) I have no idea where I am in the "big picture" when navigating around, 6) the left menu and the "Docs" vs. "API Reference" at the top are a lot less helpful than the MSDN version, 7) the trailing color of hovering on the left menu is clever but really distracting and the selected nav item is too dark, 8) the syntax coloring of examples is less "bright" than the MSDN version and harder to read and also when you copy/paste the example into OneNote for example it pastes as just red and black, 9) the "Send to OneNote" formatting is not good and just as important, because of #1 issue above, all the links are broken when clicked on in OneNote, 10) overall it took me at least 4 times as long to find the information I was looking for because of "new tab" issue and it seems that I have to scroll a lot more because the left nav is not dynamic to the current context (ex. if I am viewing Table Object the props and methods of the table object should be available on the left nav)

Sorry if this is harsh but it was a very frustrating day trying to find and organize information that I should have been able to do in a couple of hours. I'm sure the docs are a work-in-progress but generally they just don't seem ready for prime time yet.

Please re-activate the MSDN docs until these issues can be resolved.

Thanks.

**Comment by MIchaelMainer** [comment]
@jbarr33 Thank you for raising your issues about your experience with the documentation. You raise some very valid points, some if which we recently became aware of and others that you are now bringing to our attention. I'm passing this along so that we can consider our options moving forward. 

Again, I thank you for your fair feedback.

**Comment by keyur32** [comment]
@jbarr33  Thank you for the feedback here. We're working hard to resolve the blocking issues, especially with the new window/tab links and the browser back behavior.  We'll be prioritizing #1 and #4 above for our next release (we aim to fix issues on the site on a weekly basis). We'll also look to smooth out some of the other points here that you mentioned like removing the gradient.

As mentioned on the other issue, you can workaround #1 by removing the ".htm".  We'll be working to fix this as soon as we can.

Also, for the send to OneNote scenario, we'd like to understand this a bit more? Can you elaborate you use OneNote with the docs?

Part of our goal was to move the docs into GitHub so we could have conversations like this one to improve the overall quality of the docs and we're looking for more in the future. Sorry again for the pain and thank you for the feedback.

**Comment by jbarr33** [comment]
@keyur32 and @MIchaelMainer  Thanks for the quick reply and glad to know you're open to feedback. I'm happy to give feedback and, again, sorry if it was too harsh as I'm sure you're working hard at this. I just happen to be using the docs heavily again right now for my next Add-in and I was used to the old docs.  Part of it what makes it confusing, which is not your fault, is the "common API" vs. app-specific API (like Excel API) because there are many ways to do the same thing and finding out the "right" way to do something is sometimes very hard. This must be difficult to document. Also, some of my comments are obviously based on opinion/taste so others may disagree but I hope some can be addressed since this is the main source of help for the Office Add-in API.

Regarding OneNote, IE browser has a "Send to OneNote" feature which allows you to take an entire page or highlight part of a page and create a OneNote note with it.  I do this a lot to capture pages that I have already visited/read and for future reference. Doing this with the current docs results in some weird styling such as code examples displaying in only 2 colors -- black and red and some paragraphs come out entirely in blue. These are not a huge deal as it does sometimes happen with other web sites too but it is less optimal than before.

If you're looking for a good (frustrating :) example of the browser back button not working go to https://dev.office.com/docs/add-ins/excel/excel-add-ins-javascript-api-reference which I use heavily and then click on the Range link and then try the back button. Glad to know this is high on your priority list.

Thanks again for your responses.

**Comment by keyur32** [comment]
Hi @jbarr33,  the new link issue should now be fixed, as is the forward and back browser (thanks for the example above - we added that as a test case).  

We understand the confusion around common vs app specific APIs and we'll work to be more prescriptive on the content for developers targeting the new Excel/Word APIs  vs developers targeting only the common API.  

Thanks and still checking on what we can do for the formatting.

**Comment by jbarr33** [comment]
Hi @keyur32 et al.  Thanks for the update! The docs are much easier to navigate now.

**Comment by keyur32** [comment]
Hi @jbarr33, I'm closing this out for now, as we're going through open issues. If you have any other issues with the docs, please create a new issue.   Couple of updates that are on-going, we're adding product landing pages to make it easier to navigate (word has one, we'll be adding those to Excel and PowerPoint as well).  We're also working on bringing the "In this article" content back to make navigation easier within a topic. Once we do, we may tweak the CSS styles a bit more to be. In the short term, we went with a lighter color scheme, as we found that it aided discovery of the API reference topics.  thanks again.

**Comment by jbarr33** [comment]
Hi @keyur32.  Thanks for the update. I appreciate it. Keep up the good work!
