### ISSUE TITLE
Where does office cache command icons?

### ISSUE THREAD

**Issue by weird-dreams** [OfficeDev/office-js-docs#1094]
We implemented command bars and are testing in office 16 (Version 1707).
Now our designer has new icon files (png) which were replaced in the project
But they do not show up in the ribbon - there are still the initial ones.
Where does office cache those icons?
Rebuilding the windows icon cache did not help.
Any ideas?
Thx, Andi

**Comment by Rick-Kirkham** [comment]
Sometimes the Office cache does not get cleared. See here for how to clear it: [Clear the Office cache](https://dev.office.com/docs/add-ins/testing/troubleshoot-manifest#clear-the-office-cache)
