### ISSUE TITLE
link for Javascript reference is duplicated

### ISSUE THREAD

**Issue by Hongbo-Miao** [OfficeDev/office-js-docs#1136]
_[Copy from Yina's mail]_

Article:
https://dev.office.com/docs/add-ins/excel/excel-add-ins-overview?product=excel

Issue: 
The link for Javascript reference is duplicated and the second one takes the user out of context.
![image](https://user-images.githubusercontent.com/3375461/31353370-2fd1f7ca-ace7-11e7-86f0-b6f5854fc76c.png)

**Comment by kbrandl** [comment]
Issue resolved by PR 1137:  https://github.com/OfficeDev/office-js-docs/pull/1137.  This TOC change (to not show the second reference link when docs are filtered by product=Excel) has been verified on the staging site and will be published to the live site with the next batch of doc updates (this week).
