### ISSUE TITLE
office.js: Word document looses bindings when copied to OneDrive !?

### ISSUE THREAD

**Issue by weird-dreams** [OfficeDev/office-js-docs#1158]
Hi there,

we have developed a Office Addin that inserts OoXML content into a word document.
This works as expected with Office 2016 Desktop versions.

When we open this document with Word Online the bindings are not found anymore!? 
The file is copied therefore 1:1 into OneDrive for Business (or by a Save As).

Word Online uses the exact same Add In as Word Desktop.

The other way: when we create a new document by Word Online and insert OoXml content here and re-open the file then the bindings are ok.

This seems to be a bug. May you pass this to the developers...?

**Comment by weird-dreams** [comment]
This Issue only arises only when we add this option at document creation:
Office.context.document.settings.set("Office.AutoShowTaskpaneWithDocument", enable);

**Comment by Rick-Kirkham** [comment]
@weird-dreams 
Please raise this issue on StackOverflow and tag it office-js. Doing so maximizes the chance that it will be seen by someone who can help, or confirm that you have found a bug. The issues for this repo are intended to report problems in only the documentation.

**Comment by ThePillowPrince** [comment]
@weird-dreams, did you manage to find a solution or find the cause?

**Comment by weird-dreams** [comment]
@ThePillowPrince Will try it out again tomorrow...
