### ISSUE TITLE
Broken images in "Office Add-in UI Elements"

### ISSUE THREAD

**Issue by hshapley** [OfficeDev/office-js-docs#117]
The images appear fine in GitHub but not on dev.office.com. https://dev.office.com/docs/add-ins/design/ui-elements/ui-elements

**Comment by Lauragra** [comment]
I see the images on the page but I have noticed that images sometimes don't show until the page is refreshed. Try refreshing the page and you should see the images.

**Comment by hshapley** [comment]
Trying on a different computer, they show up.
