### ISSUE TITLE
contentControls not found

### ISSUE THREAD

**Issue by hengchengfei** [OfficeDev/office-js-docs#1171]
Article:
https://dev.office.com/reference/add-ins/word/word-add-ins-reference-overview

Issue:
Firstly, I added multiple ContentControls manually in Document.
Then, I want to list all ContentControls.
But , search no result.

Visual Studio 2017
Office 2016

Debug:
<img width="645" alt="2" src="https://user-images.githubusercontent.com/3182964/32097667-df6f997c-bb3c-11e7-9fa9-0427cb872b7d.png">

Word:
<img width="1070" alt="1" src="https://user-images.githubusercontent.com/3182964/32097673-e4e7359a-bb3c-11e7-8d22-1417e1f1ed2e.png">

Thank you.

**Comment by Rick-Kirkham** [comment]
@hengchengfei 
The Issues in this repo are intended to report bugs in the documentation. Please ask technical questions like this one on StackOverflow and tag it "office-js". That way others who encounter the problem will see the answer.
