### ISSUE TITLE
OfficeThemes.css not regenerating in Excel add-in

### ISSUE THREAD

**Issue by zelliott** [OfficeDev/office-js-docs#1176]
I'm following the guidelines here (https://dev.office.com/docs/add-ins/powerpoint/use-document-themes-in-your-powerpoint-add-ins?product=excel) to dynamically change the color palette based upon the current Office Excel theme.  For reference, I am building an Excel add-in.

However, it seems as though the docs suggest that the OfficeThemes.css functionality is only available for add-ins to PowerPoint?  This might explain why - despite following the guidelines essentially verbatim - the OfficeThemes.css stylesheet does not seem to dynamically regenerate when one changes the Excel theme.  I was wondering if I could get some clarification on this point here.  If it turns out that the OfficeThemes.css stylesheet should work with Excel add-ins, then I'd like to make sure that I am following the guidelines properly.

Thanks.

**Comment by Rick-Kirkham** [comment]
I have confirmed that document themes is supported only for PowerPoint. If you'd like to see it supported on other Office apps, please go to [Office Developer Voice](https://officespdev.uservoice.com/) and suggest it.
