### ISSUE TITLE
Network Share not listed as deployment option

### ISSUE THREAD

**Issue by Rick-Kirkham** [OfficeDev/office-js-docs#1179]
Article:
https://github.com/OfficeDev/office-js-docs/blob/master/docs/publish/publish.md

Issue: 
The overview of add-in publishing models does not list **Network Share** as an option. The article seems to assume that a Network Share catalog is only used during development. In fact, companies can put their custom add-ins on a network share if they want. Do we recommend against this? Or was it a mistake to not include Network Share as an option? 

**EDIT**: It looks like even the oldest version of the article June, 2016, did not mention Network Share.

**Comment by lindalu-MSFT** [comment]
@Rick-Kirkham I added the Network share topic to the list and created a PR for you to review.
