### ISSUE TITLE
Protect api no longer work in excel online

### ISSUE THREAD

**Issue by shyambhiogade** [OfficeDev/office-js-docs#1185]
Protect api documented here and example given no longer works
https://github.com/OfficeDev/office-js-docs/blob/master/reference/excel/worksheetprotection.md#protectoptions-worksheetprotectionoptions

it gives error as 
Home.js:69 Error: InvalidArgument: The argument is invalid or missing or has an incorrect format.
(anonymous) @ Home.js:69
Home.js:71 Debug info: {"code":"InvalidArgument","message":"The argument is invalid or missing or has an incorrect format.","errorLocation":"WorksheetProtection.protect"}

**Comment by Rick-Kirkham** [comment]
I can reproduce this. I'm making inquiries with the product team. 
@shyambhiogade  Do you know for sure that this used to work?

**Comment by sumurthy** [comment]
We are aware of the issue. We're working on a fix to update the JavaScript library to fix the issue. ETA: 1-2 weeks at most.

**Comment by shyambhiogade** [comment]
@Rick-Kirkham yes, this used to work, I had the code in production, which suddenly started failing.

**Comment by kbrandl** [comment]
Closing this issue, as this product bug appears to have been fixed.
