### ISSUE TITLE
Excel API Queries

### ISSUE THREAD

**Issue by AhmedVali** [OfficeDev/office-js-docs#1188]
Hi Experts,

Is there any method available for reading/updating the Header from a Workbook.  I could see we have a similar function in Word- getHeader. ?

Also what is the timeline for custom properties to be included in the API for Excel?

**Comment by mlafleur** [comment]
This isn't support by the Excel API today.  I recommend visiting the [UserVoice](https://officespdev.uservoice.com/) and adding your suggestion.

**Comment by sumurthy** [comment]
We do now support custom properties in preview for desktop and online. Mac and iOS support should also be coming soon. 

See here: https://github.com/OfficeDev/office-js-docs/blob/ExcelJs_OpenSpec/reference/excel/documentproperties.md

The workbook header is not in the roadmap - please add uservoice request.
