### ISSUE TITLE
TOC does not show correctly

### ISSUE THREAD

**Issue by Hongbo-Miao** [OfficeDev/office-js-docs#1195]
When I click Office Add-ins at [here](https://developer.microsoft.com/en-us/excel)
![image](https://user-images.githubusercontent.com/3375461/32625440-13174514-c541-11e7-9c84-ee1ccfd8e6ce.png)

It opens this page. However, the table of content does not show it correctly.
![image](https://user-images.githubusercontent.com/3375461/32625467-25804f16-c541-11e7-9169-e3f6d0795005.png)

What I expect is something like this: expand Excel and highlight quick start.
![image](https://user-images.githubusercontent.com/3375461/32625511-3a685cca-c541-11e7-9a91-e4e615f0e21a.png)

**Comment by kbrandl** [comment]
This is a bug with the dev.office.com docs platform, and should be automatically resolved when we migrate the Office Add-ins docs to docs.microsoft.com in Q4 2017.

**Comment by lindalu-MSFT** [comment]
@Hongbo-Miao Closing. TOC now renders correctly.
