### ISSUE TITLE
http://dev.office.com/docs/ generates 404 error

### ISSUE THREAD

**Issue by lnyswonger** [OfficeDev/office-js-docs#120]
http://dev.office.com/docs/ throws a 404 because it has a trailing slash but this should be handled.

**Comment by keyur32** [comment]
Our fix last week didn't fully solve this issue (the page renders but we incorrectly show the 404 banner at the top of the page).

**Comment by keyur32** [comment]
This was resolved a few weeks back. Closing it now.
