### ISSUE TITLE
Improvements to docs: How to attach Tooltips or "titles" to PivotItems

### ISSUE THREAD

**Issue by fergiemcdowall** [OfficeDev/office-js-docs#1201]
https://developer.microsoft.com/en-us/fabric#/components/pivot

I'm assuming that there is some way to get a mouseover `Tooltip` or `title` on a PivotItem so that users can get a concise explanation of each option in a `Pivot` element.

It would be great if this could be explained/demonstrated in the documentation

**Comment by lindalu-MSFT** [comment]
@fergiemcdowall Hi, have you clicked on "Show Code" to the right of each element?

**Comment by lindalu-MSFT** [comment]
@fergiemcdowall Also, here's additional documentation. 
[Office UI Fabric in Office Add-ins](https://dev.office.com/docs/add-ins/design/office-ui-fabric) Getting started using JS and React. 
[More on Fabric UI components with code samples](https://dev.office.com/fabric-js/Components/Pivot/Pivot.html)

**Comment by fergiemcdowall** [comment]
Just to be more specific: you can assign Tooltips to a whole Pivot, but not to each PivotItem. It seems like there should be some way to assign Tooltips to PivotItems, but its not explained/demonstrated

**Comment by lindalu-MSFT** [comment]
I'll see if I can location the Fabric PM to answer this question for you.

**Comment by lindalu-MSFT** [comment]
Hi @fergiemcdowall I checked with the PM and they requested that you open this against the following repo:
[https://github.com/OfficeDev/office-ui-fabric-react](https://github.com/OfficeDev/office-ui-fabric-react)

You'll have a better chance at finding the right person from the Fabric team or the larger Fabric community if you open the issue there. 

Sorry I couldn't be more help. Thanks, lindalu

**Comment by frevds** [comment]
Just hack it using the following code. It's been 1.5 years and nothing changed, so obviously no point to wait for it. 
````
<PivotItem itemKey={'foo'} itemIcon="Lightbulb" onRenderItemLink={ (props, defaultRenderer) => { const tooltip = 'Foo'; return <span title={tooltip}>{ defaultRenderer(props) }</span>; } }>Foo</PivotItem>
````

**Comment by fergiemcdowall** [comment]
Thanks @frevds

**Comment by v-khkuma** [comment]
Will this solution for tooltip in PivotItem, work in Mobile mode as well?

**Comment by frevds** [comment]
@v-khkuma Obviously not, if there is no "hovering".

**Comment by v-khkuma** [comment]
Thanks @frevds

**Comment by frevds** [comment]
It also seems not to work in Internet Explorer (SharePoint supports IE11), for whatever reason the title attribute on this element is completely ignored (clearly a bug) and would have to move one level higher in the DOM, but we can't access that level.

**Comment by frevds** [comment]
Not sure from what version on this is already, but I just discovered the `PivotItem.headerButtonProps`, which takes a IButtonProps object. This allows to set a tooltip rather easily now: 

````
<PivotItem headerButtonProps={ { title: 'foo' } }>Oy</PivotItem>
````

**Comment by v-khkuma** [comment]
@frevds Thanku
