### ISSUE TITLE
Range.getOoxml() & Range.insertOoxml()

### ISSUE THREAD

**Issue by ArtemZinenko** [OfficeDev/office-js-docs#121]
Hello! Please tell me when the methods of Range.getOoxml() and Range.insertOoxml() will be implemented for Word Online? I checked these by Word API 1.1 and get an exception "Not implemented".

**Comment by AlexYovenko** [comment]
Hello,

Very good question. I have the same issue on my end.

**Comment by AlexYovenko** [comment]
Hello JuaneloJuanelo,

Any update?

**Comment by sixfoot** [comment]
Hello!
The same issue! Please help.

**Comment by weshi** [comment]
For Word Online version of getOoxml() and insertOoxml(), they will be ready for preview in late April or early May.

**Comment by AlexYovenko** [comment]
weshi, is this official information? where you was able to found this?

**Comment by weshi** [comment]
My team is actively working on this now.

**Comment by JuaneloJuanelo** [comment]
Yes we are going to have support for these APIs! as Weshi commented!

**Comment by AlexYovenko** [comment]
Clear, thank you! Can you please update this thread when this methods will be available.

**Comment by AlexYovenko** [comment]
Hi All,

Next methods seems became implemented for MS Word online, at least we do not get an exception "Not implemented" any more, but new exception appear:

Body.insertOoxml - {"name":"OfficeExtension.Error","code":"InvalidArgument","message":"The argument you provided is not valid. Check the OfficeExtension.Error.debugInfo for more information.","traceMessages":[],"debugInfo":{"errorLocation":"Body.insertOoxml"}}

Range.insertOoxml - {"name":"OfficeExtension.Error","code":"InvalidArgument","message":"The argument you provided is not valid. Check the OfficeExtension.Error.debugInfo for more information.","traceMessages":[],"debugInfo":{"errorLocation":"Range.insertOoxml"}}


We using location value as "start" and OOXML string from valid MS Word document, the same methods with the same arguments works fine on Desktop MS Word.

Please advice, is this methods should work in Online MS Word?

**Comment by weshi** [comment]
Yes, we have started preview of the Word API 1.1 & 1.2. The majority of the APIs will become available while the build is rolling out in the next several weeks. Please let us know if there is any feedback and comments. Some of the APIs may not be available (NotImplemented) or with some known issues, but they will become available when new builds are deployed. 

For getOoxml and insertOoxml, the function is now working, but the return value for insertOoxml will be available in next deployment. You can try the sample code below:
[insertOoxml smaple code](https://github.com/OfficeDev/office-js-docs/blob/master/reference/word/body.md#insertooxmlooxml-string-insertlocation-insertlocation)

**Comment by AlexYovenko** [comment]
Very strange, this methods works now.
Thank you for your reply.
