### ISSUE TITLE
The title of Dialog not change

### ISSUE THREAD

**Issue by hengchengfei** [OfficeDev/office-js-docs#1227]
Article:
https://dev.office.com/docs/add-ins/develop/dialog-api-in-office-add-ins

Issue: 
When I redirect to another html page, the Dialog title not change.
For example,
 Page One's title: 'xxxxx'
 Page Two's title: 'yyyyy'

When redirect from One page to Two Page, The Dailog's title should be 'yyyyy' rather than 'xxxxx'.

<img width="490" alt="wechat image_20171125234043" src="https://user-images.githubusercontent.com/3182964/33232034-2bd643d8-d23a-11e7-96a0-514dd06cadbb.png">

**Comment by Rick-Kirkham** [comment]
The Dialog's title is always the title of the add-in (or in Office Online it is "Message from Add-in: <add-in-title>"). See the screenshots in the article [Use the Dialog API in your Office Add-ins](https://dev.office.com/docs/add-ins/develop/dialog-api-in-office-add-ins). 

But it's a good idea to make the title customizable or mirror the <title> tag in the page. Please go to [Office Developer Voice](https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/suggestions/17196659-improve-custom-dialog) and make this suggestion.

**Comment by hengchengfei** [comment]
I found that the Dailog's title contains two part.

add-in's title + "-" + html page's title.

**Comment by Rick-Kirkham** [comment]
@hengchengfei 
Sorry. By sheer luck, all the examples I was looking at have pages with empty <title></title> tags, so I didn't realize that the page title is added to the dialog's title. I can reproduce your symptoms. I will ask the product team for help, but I believe this is a bug.

**Comment by Rick-Kirkham** [comment]
This is confirmed to be a bug and I've bugged it here: https://github.com/OfficeDev/office-js/issues/36
 The only workaround that I can think of in the meantime is to have blank <title> tags in all the pages that will appear in the dialog.
