### ISSUE TITLE
GeneralException on context.sync after loading properties on Excel Online

### ISSUE THREAD

**Issue by forlemon** [OfficeDev/office-js-docs#1229]
Error on Javascript Console thrown after the first context.sync after loading properties on a writing text to cells in Excel Online, this does not appear to happen in Excel Applications for Windows and Mac, just Online:

> `r {name: "OfficeExtension.Error", code: "GeneralException", message: "Ocorreu um erro interno.", traceMessages: Array(0), innerError: null, …}
> code:"GeneralException"
> debugInfo:{code: "GeneralException", message: "Ocorreu um erro interno.", toString: ƒ}
> innerError:null
> message:"Ocorreu um erro interno."
> name:"OfficeExtension.Error"
> traceMessages:[]
> __proto__:Error`

Code that is throwing this error:

>                 $scope.writeText = function (item) { 
>                     Excel.run(function (context) {                       
>                        var click = item.Click;
>                         var sourcestring = item.onAction;
>                         var excelString = item.excel;
>                         var sheet;
>                         var activeRange;
>                         var string;
>                         if (excelString === "") string = sourcestring;
>                         else string = excelString;
>                         sheet = context.workbook.worksheets.getActiveWorksheet();
>                         activeRange = context.workbook.getSelectedRange();
>                         activeRange.load('columnIndex');
>                         activeRange.load('rowIndex');
>                         return context.sync().then(function () {
>                              CODE NOT EXECUTED, error thrown before this code
>                         }
>                       }
>                     }

This runs fine on Excel 2016, 365, etc. Just doesn't work on Online.

**Comment by Rick-Kirkham** [comment]
@forlemon 
The issues of this repo are intended for noting problems in the documentation. Please raise this technical question on StackOverflow, where the answer will be seen by others who encounter the same problem. Be sure to tag the question "office-js".

**Comment by kbrandl** [comment]
_**Note:**_ I've opened this issue on the customer's behalf in the **office-js** repo, since it's a potential product bug.

https://github.com/OfficeDev/office-js/issues/47
