### ISSUE TITLE
PeoplePicker component some questions.

### ISSUE THREAD

**Issue by hengchengfei** [OfficeDev/office-js-docs#1233]
<img width="384" alt="1" src="https://user-images.githubusercontent.com/3182964/33420057-194d4d0e-d5e8-11e7-886b-390ddb97d3b6.png">

Article:
https://dev.office.com/fabric-js/Components/PeoplePicker/PeoplePicker.html

Issue: 
In IE Browser，it is OK.
But in Office, it doesn't work.

1、Cancel's icon is not show.
2、Cancel's click event not work.

**Comment by Hongbo-Miao** [comment]
Please move to https://github.com/OfficeDev/office-ui-fabric-core/issues
