### ISSUE TITLE
IE error "Unable to get property 'removeChild' of undefined

### ISSUE THREAD

**Issue by hengchengfei** [OfficeDev/office-js-docs#1234]
Article:
https://dev.office.com/fabric-js/Components/Dialog/Dialog.html

Issue: 
There's an issue in IE (10 and 11, did not check previous versions) when click button.

<img width="309" alt="1" src="https://user-images.githubusercontent.com/3182964/33427170-5a016a62-d5ff-11e7-8824-88a66ced8db6.png">
<img width="502" alt="2" src="https://user-images.githubusercontent.com/3182964/33427178-5fcfab0c-d5ff-11e7-82cb-a6c48f087e10.png">

**Comment by Rick-Kirkham** [comment]
@hengchengfei 
This repo is intended to report errors in the documentation. Please raise this technical issue on StackOverflow and tag it "office-js". It will get handled faster there and others will benefit from seeing the answer. Thanks.

**Comment by Hongbo-Miao** [comment]
Hi @hengchengfei If it is Fabric issue, please open at https://github.com/OfficeDev/office-ui-fabric-core/issues.

If it is related with office.js, please let us know, We will reopen this. Thanks!
