### ISSUE TITLE
Excel WorkSheetProtection.protect API fails: Object doesn't support property or method 'parseInt'

### ISSUE THREAD

**Issue by djlmills** [OfficeDev/office-js-docs#1238]
All calls to `workSheet.protection.protect()` throw runtime exception: Object doesn't support property or method 'parseInt'. I have tried this with no arguments, the options argument and the options and password arguments with the same result.

The full error details are:

```
Exception was thrown at line 33, column 4 in https://appsforoffice.microsoft.com/lib/1/hosted/excel-win32-16.01.js

0x800a01b6 - JavaScript runtime error: Object doesn't support property or method 'parseInt'
```

This issue may be related to #1185, but the exception types are quite different.

This was working up until Monday Nov 27, 2017 but the same deployed add-in failed on Nov 28.

**Comment by kbrandl** [comment]
Closing this issue, as the product bug appears to have been fixed.
