### ISSUE TITLE
Angular 2 and Office apps

### ISSUE THREAD

**Issue by mwchan** [OfficeDev/office-js-docs#124]
Hi,

I am using Visual Studio 2015 Update 2 and am having some issues getting Angular 2 to work with Typescript. I was just trying to get a basic sample going based on the Angular 2 quickstart https://angular.io/docs/ts/latest/quickstart.html. 

Is what I am doing supported by Office apps(Angular 2 + Typescript + SystemJS + RxJS)?

Thanks in advance!

**Comment by MIchaelMainer** [comment]
@mwchan 

Thank you for posting your question here. Yes, you can use Angular2, TypeScript, SystemJS, and RxJS to produce an Office add-in. We don't have any examples that demonstrate those technologies at this moment,

Regarding Visual Studio 2015 Update2 + Angular2 + TypeScript, I suggest that you post to StackOverflow to help get you unblocked.
