### ISSUE TITLE
Code style

### ISSUE THREAD

**Issue by Hongbo-Miao** [OfficeDev/office-js-docs#1254]
Need find an efficient way to improve code style like spacing in all docs.

Right now it is not good:

```js
Excel.run(function (ctx) { 
	var sheetName = "Sheet1";
	var rangeAddress = "D4:G6";
	var range = ctx.workbook.worksheets.getItem(sheetName).getRange(rangeAddress);
	var range = range.getBoundingRect("G4:H8");
	range.load('address');
	return ctx.sync().then(function() {
		console.log(range.address); // Prints Sheet1!D4:H8
	});
}).catch(function(error) {
		console.log("Error: " + error);
		if (error instanceof OfficeExtension.Error) {
			console.log("Debug info: " + JSON.stringify(error.debugInfo));
		}
});
```

**Comment by Hongbo-Miao** [comment]
prettier might be a good solution.
https://github.com/prettier/prettier

**Comment by Linda-Editor** [comment]
@lindalu-MSFT  You might want to take a look at this request. Not sure I'm the one to make any decisions regarding code styling.

**Comment by kbrandl** [comment]
@lindalu-MSFT and @Linda-Editor -- can you please fix any code-indentation issues that you notice in the Office Add-ins docs?  Each level of indentation should include 4 spaces.  I'd be happy to discuss further if you need more info. Thanks!

**Comment by Hongbo-Miao** [comment]
Let's use 2 spaces which is much more common for JavaScript.

**Comment by Linda-Editor** [comment]
Normally editors do not touch the code blocks. We do, however, make sure that entire code blocks are indented so that procedure steps appear correctly (in order). So I'm not sure what you're asking for here because it appears that you'd like us to do something INSIDE the code block. Please explain. Thanks.

**Comment by Hongbo-Miao** [comment]
For indentation, something like this
```js
Excel.run(function(ctx) {
  var sheetName = "Sheet1";
  var rangeAddress = "D4:G6";
  var range = ctx.workbook.worksheets.getItem(sheetName).getRange(rangeAddress);
  var range = range.getBoundingRect("G4:H8");
  range.load('address');
  return ctx.sync().then(function() {
    console.log(range.address); // Prints Sheet1!D4:H8
  });
}).catch(function(error) {
  console.log("Error: " + error);
  if (error instanceof OfficeExtension.Error) {
    console.log("Debug info: " + JSON.stringify(error.debugInfo));
  }
});
```
(But the code itself also is wrong, like there are two `var range =`)

**Comment by Linda-Editor** [comment]
Exactly. The editors are not developers, so this is really something that the writers or developers should be fixing before docs get published or go to editing. Sometimes I'll fix code where it's obvious (such as spacing on beginning and ending tags in HTML), but most of the time I leave it alone for fear of doing something that "wrecks" it...

**Comment by Hongbo-Miao** [comment]
Yeah, for indentation, we might need update the code generation tool.
For code sample mistake, I will create another issue for this.

**Comment by kbrandl** [comment]
@Linda-Editor -- fair enough; you can disregard this issue and we'll get someone else to address it.

**Comment by lindalu-MSFT** [comment]
@Linda-Editor @Hongbo-Miao @kbrandl I think we can close this issue. See the[ OPS topic on code snippets](https://opsdocs.azurewebsites.net/en-us/opsdocs/partnerdocs/codesnippets?branch=master#supported-languages).  Depending on the language selected, the code style and spacing is much better. For example, C# indents with 2 spaces now.
