### ISSUE TITLE
DOM-manipulation in Visio iframe

### ISSUE THREAD

**Issue by thorild** [OfficeDev/office-js-docs#1257]
Hi!

As far as I can see it is not possible to reach into the frame hosting the Visio Online doc for DOM manipulation. Let's say we wanted to change the colour of a border or background or maybe add some custom events on all hyperlinks etc.

Have I missed any option already in place or is it feasible to open up for this functionality?

**Comment by kbrandl** [comment]
@rahul-mi -- I've assigned this Visio issue/question to you. Can you please take a look and provide feedback to the customer? Thanks!

**Comment by rahul-mi** [comment]
Hi,

Visio Online JS APIs do not provide access to DOM manipulation directly. If you want to remove some UI element like status bar or add custom events to hyperlinks, you need legitimate APIs to achieve these results. In above example, you will need something like Application.ShowStatusBar = False and a MouseClick event API for custom hyperlinks.

Having said that, the above APIs are not yet available and we are in the process of adding those. Would request you to share your asks and feedback related to direct DOM manipulation on tellvisio[at]microsoft.com.

Regards
Rahul Mittal | Program Manager | Microsoft Visio

**Comment by rahul-mi** [comment]
Thanks Kim for reaching out.
I have provided the feedback to the customer and believe that the issue can be closed, unless the customer comes back with another ask/question.

Regards
Rahul Mittal

**Comment by kbrandl** [comment]
@thorild -- thank you for your inquiry. Given @rahul-mi's comment, I am closing this issue, but please feel free to submit additional feedback as directed in @rahul-mi's response.
