### ISSUE TITLE
CustomXMLParts listed as shared API but only available for Word

### ISSUE THREAD

**Issue by Falkayn** [OfficeDev/office-js-docs#126]
The CustomXMLParts is listed as a shared API resource, but it is only currently available for Word.

The documentation currently says it is not available for Word Online, but our experience is that it is working for us in our developer (edge) tenant.

When will it work for Excel and PowerPoint as this is functionality we have had in the COM API for years now.

Thanks,
Angus

**Comment by MIchaelMainer** [comment]
Hello @Falkayn 

CustomXmlParts are working for the getter scenario for Word Online. The setter scenario is being enabled. Regarding Excel and PowerPoint, I know this scenario has been discussed and the team is aware of this, and other requests for this functionality. I'm unaware of when this would be enabled for other clients like Excel and PowerPoint. 

With regards,
Michael

**Comment by Falkayn** [comment]
Thanks @MIchaelMainer for the update. I will make sure our testers are aware of the Setter gap and test that use case for our app. I'm glad the team is awar eof the issue - I just hope we hear soon that it will be fixed! :smile:
