### ISSUE TITLE
The Office.context.officeTheme property is undefined in Outlook 2016

### ISSUE THREAD

**Issue by eblancperso** [OfficeDev/office-js-docs#1262]
The property Office.context.officeTheme is undefined when used in the Outlook application: [Official documentation](https://dev.office.com/reference/add-ins/shared/office.context.officetheme). In Word, Excel and PowerPoint, the property is defined and I can access its children properties (bodyBackgroundColor, controlForegroundColor, etc...). I tried with both latest (1.1.0.13) and previous (1.1.0.12) versions of Office.JS but it doesn't work. My outlook version is: 1711 (Build 8730.2127) and I also tried in the latest insiders build. Sample code:

```
Office.initialize = function (reason) {
    $(document).ready(function () {

        // The "Office" object and its "context" property are valid but the "officeTheme" property is undefined.
        // This works in Word, Excel and PowerPoint but not in Outlook.
        if (!Office.context.officeTheme) {
            console.log("Office theme not loaded");
        }
    });
}
```

I already posted this same question [here ](https://stackoverflow.com/questions/47780059/the-office-context-officetheme-property-is-undefined) but unfortunately didn't get any feedback. Thank you!

**Comment by kbrandl** [comment]
@jasonjoh -- can you please follow-up with appropriate person on the Outlook team about this issue?

**Comment by eblancperso** [comment]
@kbrandl @jasonjoh  Any updates on this issue soon? Thank you!

**Comment by jasonjoh** [comment]
Sorry @eblancperso. I started a discussion with the Outlook team on this a while back which I need to follow up on. The short answer here is that Outlook has never done the work to support the `officeTheme` property so from that perspective the docs need to be updated to reflect that.

**Comment by jasonjoh** [comment]
Thanks @kbrandl for updating the docs.
