### ISSUE TITLE
where to place Requirements element in manifest file?

### ISSUE THREAD

**Issue by chenxizhang** [OfficeDev/office-js-docs#1265]
i want to implement SSO in add-in , according this guide as below, but i don't know where to place `Requirements` element in manifest file? it's always throw error no matter where I put it

https://github.com/OfficeDev/office-js-docs/blob/master/reference/shared/office.context.auth.getAccessTokenAsync.md

**Comment by Rick-Kirkham** [comment]
It should be a child of the OfficeApp element. 
For more information, see https://dev.office.com/reference/add-ins/manifest/requirements
and https://docs.microsoft.com/en-us/office/dev/add-ins/develop/specify-office-hosts-and-api-requirements

**Comment by chenxizhang** [comment]
thank you rick @Rick-Kirkham 

but it's not work for me

![image](https://user-images.githubusercontent.com/1996954/34236884-95007d52-e634-11e7-963d-974971d779d7.png)

**Comment by Rick-Kirkham** [comment]
Try putting the Requirements element just below the </Hosts> closing tag.

**Comment by chenxizhang** [comment]
i am try everywhere, but it doesn't work at all

**Comment by Rick-Kirkham** [comment]
In my last comment I made the mistake of putting angle brackets around an element name and apparently that prevents the entire name from rendering. This is what I meant to suggest:
Try putting the Requirements element just below the Hosts element closing tag.

**Comment by chenxizhang** [comment]
than you @Rick-Kirkham 

it's awesome, the manifest is work fine. 

![image](https://user-images.githubusercontent.com/1996954/34281784-fb1df264-e6fb-11e7-8bf4-87431500c266.png)

but when i try to call getAccessTokenAsync method, 

![image](https://user-images.githubusercontent.com/1996954/34281791-101ee65a-e6fc-11e7-8814-5ec1544f62c9.png)

i got the error 

`The identity API is not supported for this add-in.`

**Comment by Rick-Kirkham** [comment]
YOu may not have a recent enough version of Office, or you may have left out the WebApplication markup from the manifest. See these articles:
https://docs.microsoft.com/en-us/office/dev/add-ins/develop/troubleshoot-sso-in-office-add-ins#13000
https://docs.microsoft.com/en-us/office/dev/add-ins/develop/create-sso-office-add-ins-aspnet
