### ISSUE TITLE
The host name should not be based on already owned domain

### ISSUE THREAD

**Issue by chenxizhang** [OfficeDev/office-js-docs#1268]
Hi there 

I want to implement SSO in Excel Addin. I read this article "https://docs.microsoft.com/en-us/office/dev/add-ins/develop/create-sso-office-add-ins-aspnet" and follow the step to register an application 

if i specify the settings as below ,then i got an error and can not save 

![image](https://user-images.githubusercontent.com/1996954/34344848-1c5dddd2-ea25-11e7-8e40-8965903a9048.png)

if i specify the other settings as below,

![image](https://user-images.githubusercontent.com/1996954/34344871-4c2c4756-ea25-11e7-92bc-082b080879bf.png)

and modify the manifest to match

![image](https://user-images.githubusercontent.com/1996954/34344885-73c963f2-ea25-11e7-9866-4a2d800e26a3.png)

then i got another error message

![image](https://user-images.githubusercontent.com/1996954/34344896-8365940c-ea25-11e7-9f57-41dc0f977f62.png)

What a puzzling experience！！！

can you guys really improve this feature 、article and demo code???

**Comment by Rick-Kirkham** [comment]
@chenxizhang 
The issue you created for the sample is a better place to track this. It's not really an issue with the documentation, but a problem with either the code or a bug in AAD. So, I will close this.
