### ISSUE TITLE
Requirements manifest XML topic is missing information

### ISSUE THREAD

**Issue by Rick-Kirkham** [OfficeDev/office-js-docs#1274]
Article:
[Requirements](https://github.com/OfficeDev/office-js-docs/blob/master/reference/manifest/requirements.md)
Issue: 
The article tells what the parent element is, but it can't be just anywhere in that parent. It has to be below the Hosts element.

**Comment by kbrandl** [comment]
Note: This issue applies to the Manifest documentation as a whole -- i.e., there are several elements that must appear in a specific location in the XML file, but the docs don't specify info about element sequence.

**Comment by Rick-Kirkham** [comment]
This is being tracked here: https://office.visualstudio.com/OC/_workitems/edit/2075086
