### ISSUE TITLE
save as dialog to save word document in word web add ins

### ISSUE THREAD

**Issue by radhikaalone** [OfficeDev/office-js-docs#1288]
I have to save file using save as functionality in word web add ins using JavaScript. but there is no functionality for it so may i know  how to implement it? so that i can save file with any name and open downloaded file in word using web add ins.

**Comment by Rick-Kirkham** [comment]
@radhikaalone 
We use the Issues of this repo to track errors in the documentation. For a technical question like this, please ask it on StackOverflow and tag the question office-js. This will ensure that knowledgeable people see your question and that the answer will be seen by other programmers who face the same question in the future.
