### ISSUE TITLE
How to get 'CoercionType' of the current e-mail in office365?

### ISSUE THREAD

**Issue by MacPherson** [OfficeDev/office-js-docs#129]
How to get 'CoercionType' of the current e-mail in office365? I can not find getter in the OfficeJS library.

**Comment by jasonjoh** [comment]
If this is in a compose window, you want `Office.context.mailbox.item.body.getTypeAsync()` (https://dev.outlook.com/reference/add-ins/Body.html#getTypeAsync). There is not a method to get this for read mode. In read mode the body only exposes `getAsync`, and you can use the `coercionType` parameter to force the returned data into the format you want to work with.
