### ISSUE TITLE
Outlook Requirement Sets Clients Chart Out of date

### ISSUE THREAD

**Issue by stephenegriffin** [OfficeDev/office-js-docs#1301]
Article:
https://dev.office.com/reference/add-ins/outlook/tutorial-api-requirement-sets

Issue: 
My add-in reports the highest requirement set it can find and using that I'm seeing discrepancies between the chart and the clients I'm testing in.

I'd submit a pull request, but I want help verifying the problems in the chart first and finding proper sources. What I see in my own testing:
Outlook 2013 for Windows - chart says 1.3, I see 1.4 (1.4 added by https://support.microsoft.com/en-us/help/3118280/ms16-107-description-of-the-security-update-for-outlook-2013-september)
Outlook for iPhone - chart says 1.4. I see 1.5
Outlook for Android - chart says 1.4 - I don't have an android phone to test, but I suspect this is 1.5 like iphone

**Comment by kbrandl** [comment]
@stephenegriffin -- thank you for reporting this potential issue with the docs; we'll have someone look into this and respond here when more info is known.  

@jasonjoh -- would you mind following up about this issue (and looping in @ElizabethSamuel-MSFT and/or @dmahugh if you think it'd be a useful exercise for them)?

**Comment by Reezaali** [comment]
FYI I've created an internal bug for this already. Thanks @kbrandl.

**Comment by rickgoud** [comment]
Is there any news on this?
As I expect/hope that Exchange 2016 also support is higher than reported, namely 1.5 instead of 1.3...

**Comment by rickgoud** [comment]
Can somebody at microsoft please respond to my latest remark?

**Comment by jasonjoh** [comment]
@rickgoud I'm following up internally on this. Exchange 2016 OWA wasn't included in the original report so it wasn't something we were checking on for this. Usually the client teams let us know if they add support for a new requirement set, but I'm checking with the OWA team to verify.

**Comment by rickgoud** [comment]
Thanks; is Exchange 2016 OWA the same as Exchange 2016 with OWA365 (in hybrid mode)? :). Some of our clients use that

**Comment by jasonjoh** [comment]
It could be. What matters is what servers they use to access OWA. If they're going to https://outlook.office.com or https://outlook.office365.com, then they're getting Office 365's web app, which supports later requirement sets. If not, they're likely getting the on-premises Exchange 2016 version.

**Comment by ElizabethSamuel-MSFT** [comment]
The Clients chart in the tutorial should be current now with Android still at 1.4.
