### ISSUE TITLE
Excel API - Worksheet or Named table copy?

### ISSUE THREAD

**Issue by asureshnair** [OfficeDev/office-js-docs#132]
Hi,

The API currently does not seem to provide a worksheet copy method or a named table copy method. For the table copy, I did an alternative way of reading the range and creating a table at the target location and inserting row by row and then applying format for each cell. I could not find a way to apply the data validation.
Any alternate way to copy so that we can get all the properties together including the data validation?

Thank you,
Anoop.

**Comment by skyms** [comment]
Hi asureshnair,

Unfortunately we don't have this API yet. But it is on our backlog.  Can you submit this feature request at officespdev.uservoice.com? Other people can vote for this suggestion if they agree with you and also you will get notification with any progress with this specific API. You can simply choose** Add-in: Excel** as the category and we routinely look at feature suggestions on uservoice.

Thanks,
Sky
