### ISSUE TITLE
insertFileFromBase64 header/footer issue in Word

### ISSUE THREAD

**Issue by IanPearce** [OfficeDev/office-js-docs#1320]
Hi

I have a problem, if you insert a file using insertFileFromBase64, and the base64 document contains a header and footer, on all pages, the call inserts the header and footer on a blank first page and then has the header and footer on the subsequent pages, where it actually inserts the document body.

it appears to insert a section page break (Next Page) at the top of the document.
[decodedbase64.docx](https://github.com/OfficeDev/office-js-docs/files/1747919/decodedbase64.docx)
[Base64DocxFile.txt](https://github.com/OfficeDev/office-js-docs/files/1747920/Base64DocxFile.txt)

I have attached both the base64 encoded document and the original file. If you open the original file in word, it opens with no blank page, but if you use insertFileFromBase64 to insert the file it does have this blank page with header and footer.

opened directly
![image](https://user-images.githubusercontent.com/9249691/36539824-fcfd9c6a-17cf-11e8-8a2b-144f32460785.png)

inserted with insertFileFromBase64 
![image](https://user-images.githubusercontent.com/9249691/36539863-2548eb7a-17d0-11e8-8491-2970f155152d.png)

Can this issue be fixed or is it possible for someone to supply code that would remove the additional section break and therefore the blank first page?

Kind regards

Ian

**Comment by Rick-Kirkham** [comment]
@IanPearce Looks like you've got a really interesting add-in there. Please raise this issue on StackOverflow and tag it "office-js". That's the best way to ensure that it's seen by experts. And people who have the same problem in the future will see it. 
The issues for this repo are really only intended for reporting problems with the documentation.
