### ISSUE TITLE
Ambiguous: WordApi 1.3 support in MSI versions of Office 2016

### ISSUE THREAD

**Issue by fergiemcdowall** [OfficeDev/office-js-docs#1342]
## Article URL
source -> https://github.com/OfficeDev/office-js-docs/blob/master/reference/requirement-sets/word-api-requirement-sets.md

published -> https://dev.office.com/reference/add-ins/requirement-sets/word-api-requirement-sets

## Issue
I am working at a Scandinavian Publisher that is developing an add-in for Word which requires WordApi 1.3

We are creating system requirements documentation for our customers. From the article above it is unclear to what extent WordApi 1.3 is supported in MSI versions of Office 2016. The linked article contains the note _"The build number for Office 2016 installed via MSI is 16.0.4266.1001. This version only contains the WordApi 1.1 requirement set."_

 * I think there are now other versions of Office 2016 installed via MSI- is WordApi 1.3 is supported on them?
 * If an organisation doesn't have a version of Office 2016 installed via MSI that supports WordApi 1.3, are any upgrade options available to them?

also

 * Perhaps **"Office 2016 installed via MSI"** should be a column in the requirement sets support matrix/table? (There is currently an empty column for **"Office Online Server"**)

**Comment by Rick-Kirkham** [comment]
@fergiemcdowall There is only one Office 2016 installed with MSI. It only supports Word 1.1. The next MSI version will likely be Office 2019. If they can't wait for that, then they should switch to the Office 365 Word that is installed with Click-to-Run.
