### ISSUE TITLE
Api 1.4 not open

### ISSUE THREAD

**Issue by hengchengfei** [OfficeDev/office-js-docs#1373]
## Article URL
https://dev.office.com/reference/add-ins/openspec

## Issue
<img width="805" alt="1" src="https://user-images.githubusercontent.com/3182964/38398594-5c3a9e08-3977-11e8-9be7-aa154ae27c25.png">
<img width="824" alt="2" src="https://user-images.githubusercontent.com/3182964/38398595-5c7a2d8e-3977-11e8-9c9e-5901c81b8955.png">

**Comment by kbrandl** [comment]
@hengchengfei -- thank you for reporting this issue. We are investigating and I'll update this issue thread when this problem has been resolved.

**Comment by kbrandl** [comment]
@hengchengfei, thanks again for reporting this issue. It's been determined that the content that link points to no longer exists. We're in the process of updating the [API open specifications](https://dev.office.com/reference/add-ins/openspec) page in the docs (to match what's seen here: https://github.com/OfficeDev/office-js-docs/blob/live/reference/openspec.md) and you should see changes to that page shortly. In the meantime though, here's the correct location of the Word API open spec:  https://github.com/OfficeDev/office-js-docs/tree/WordJs_OpenSpec.
