### ISSUE TITLE
Not able to handle the document object after create.

### ISSUE THREAD

**Issue by hengchengfei** [OfficeDev/office-js-docs#1374]
## Article URL
https://dev.office.com/reference/add-ins/openspec

## Issue
I want to operate the new created document, It doesn't work.(It is ok in the previous beta version)
In previous version,CreateDocument return Document Object,But in api 1.4,return DocumentCreated  Object.

```javascript
        document = context.application.createDocument(docxString);
        document.open();

        context.load(document);

        var tables; 
        return context.sync()
            .then(function () {
                tables = document.body.tables;
            })
            .then(context.sync)
            .catch(function (e) {
                console.log(e);
            });
```
<img width="356" alt="1" src="https://user-images.githubusercontent.com/3182964/38450371-3645ff2a-3a4f-11e8-8556-84a9a03d0514.png">

**Comment by kbrandl** [comment]
@hengchengfei -- thank you for your interest in the Excel JavaScript API. This GitHub repository (**OfficeDev/office-js-docs**) is for reporting errors/issues with the API *documentation*.  While there is certainly some overlap at times, errors/issues with the API itself should be posted to the **OfficeDev/office-js** repository, which members of the product team monitor for customer-reported API issues such as this. Can you please post this issue to **OfficeDev/office-js** instead?
