### ISSUE TITLE
CustomPropertyCollection#add method.

### ISSUE THREAD

**Issue by hengchengfei** [OfficeDev/office-js-docs#1377]
When Creates a new custom property with String type,but result is Date type.

## Article URL
https://dev.office.com/reference/add-ins/word/custompropertycollection

## Issue
```javascript
var customPros = document.properties.customProperties;
//...
customPros.add("ReportDate", "2018-04-10");
```
<img width="325" alt="2" src="https://user-images.githubusercontent.com/3182964/38552854-1161092c-3cf0-11e8-897a-11a5ab721c88.png">

<img width="1038" alt="1" src="https://user-images.githubusercontent.com/3182964/38552846-0b8432d6-3cf0-11e8-9114-d0a95f34c5f7.png">

**Comment by Rick-Kirkham** [comment]
I have responded to the StackOverflow question that you created for this issue:
[custompropertycollectionaddkey-value-method](https://stackoverflow.com/questions/49767164/custompropertycollectionaddkey-value-method/49767698#49767698)
Let's track the discussion there where the whole community can benefit:
 I'll close this issue.
