### ISSUE TITLE
getFileAsync on iPad

### ISSUE THREAD

**Issue by EdwinStraver** [OfficeDev/office-js-docs#1405]
Will getFileAsync be supported for Excel on iPad as well? 
And if so, is there a timeline?

**Comment by ElizabethSamuel-MSFT** [comment]
@EdwinStraver: getFileAsync is currently supported on iPad per [Common API requirement set](https://docs.microsoft.com/office/dev/add-ins/reference/requirement-sets/office-add-in-requirement-sets) (see entry for File requirement set) and [Host and platform availability](https://docs.microsoft.com/office/dev/add-ins/overview/office-add-in-availability#excel). We'll update the [reference documentation](https://docs.microsoft.com/javascript/api/office/office.document#getfileasync-filetype--options--callback-) accordingly.

**Comment by ElizabethSamuel-MSFT** [comment]
@EdwinStraver: We've updated the support details per these PRs (https://github.com/OfficeDev/office-js-docs-reference/pull/247, https://github.com/OfficeDev/office-js-docs-pr/pull/568) and the changes should go live soon. If you do notice any other discrepancies, please let us know. Thanks.
