### ISSUE TITLE
Example missing for sending email using getCallbackTokenAsync and REST

### ISSUE THREAD

**Issue by binarykitchen** [OfficeDev/office-js-docs#1419]
Hello Microsoft

Think a good example is missing on how to send an email using REST instead of SOAP. There is this SOAP example on how to forward one:
https://github.com/OfficeDev/Outlook-Add-in-ForwardEmail/blob/master/VB/OutlookEmailForwarderWeb/App/Home/OutlookEmailForwarder.js

Would be good to see the same but in REST.

Maybe it's already out in the wild, just haven't found one.

Thx :)

**Comment by mlafleur** [comment]
Take a look at https://github.com/OfficeDev/outlook-add-in-attachments-demo. This demo uses Microsoft Graph. You can use the same technique to do email forwarding using[ Graphs `//forward` endpoint](https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/message_forward).

**Comment by binarykitchen** [comment]
thanks
