### ISSUE TITLE
[Word] getTextRanges 

### ISSUE THREAD

**Issue by zqheartqq** [OfficeDev/office-js-docs#1425]
good afternoon, thanks for yours hard word~

## Article URL
https://github.com/OfficeDev/office-js-docs/blob/master/reference/word/paragraph.md#gettextrangesendingmarks-string-trimspacing-bool

## Issue
> The punctuation marks and/or other ending marks as an array of strings.
but the paragraph can only split by '/', other punctuation doesn't work, such as '。', ' ；', and other strings.

**Comment by mlafleur** [comment]
I'm sorry but I'm not sure I understand what you're asking. Could you provide a code example showing what problem you're running into?

**Comment by zqheartqq** [comment]
I'm sorry. 
I have a paragraph like `good afternoon, thanks for yours hard word~`. than I want to split the paragraph with ','. so I use paragraphObject.getTextRanges([',']) and expect to get two ranges. ranges[0].text will be `good afternoon,` and ranges[1].text will be ` thanks for yours hard word~`.
but the result has only one range, which contain the whole paragraph.

if the paragraph like `good afternoon/ thanks for yours hard word~`, and I use paragraphObject.getTextRanges(['/']), then I get two ranges. ranges[0].text will be `good afternoon/` and ranges[1].text will be ` thanks for yours hard word~`.

That's my question. Thank you~

**Comment by mlafleur** [comment]
Could you provide some sample code? I'm unable to replicate the issue you've described. 

I've created a document that contains your string `good afternoon, thanks for yours hard word~`.  After placing the cursor in the string, I executed the following code:

``` javascript
function run() {
    return Word.run(function (context) {
        const range = context.document.getSelection();
        const paragraphs = range.paragraphs;
        paragraphs.load();
        return context.sync()
            .then(() => {
                let ranges = paragraphs.items[0].getTextRanges([',']);
                ranges.load();
                return context.sync()
                    .then(() => {
                        ranges.items.forEach((range) => { 
                            console.log(range.text);
                        });
                    });
                
            });
    });
}
```

This resulted in the following two strings:

1. `good afternoon`
2. ` thanks for yours hard word~`
