### ISSUE TITLE
[word] officeui.dialog

### ISSUE THREAD

**Issue by zqheartqq** [OfficeDev/office-js-docs#1427]
## Article URL
https://github.com/OfficeDev/office-js-docs/blob/master/reference/shared/officeui.displaydialogasync.md

## Issue
In the newest office for mac(16.13)
1、 open a dialog `Office.context.ui.displayDialogAsync(_url, { height: 75, width: 80 }, callback);`. 
2、close the dialog by the dialog ui button 'X'.
3、open a dialog once again but it has an error `A dialog is already opened`.
4、even if I use the method `[dialogObject].close()`, but it also has the error `A dialog is already opened`

Do you have this problem there?

**Comment by Rick-Kirkham** [comment]
@zqheartqq The issues for this repo are used to track problems with the documentation. Please raise technical questions like this on StackOverflow and tag it "office-js". That way the whole community will benefit from the answers that you get.
