### ISSUE TITLE
Not documented: DialogHandler.sendMessage

### ISSUE THREAD

**Issue by jrop** [OfficeDev/office-js-docs#1428]
The method `DialogHandler.sendMessage` is not documented.

## Article URL

https://dev.office.com/reference/add-ins/shared/officeui.dialog

## Issue

Hello.  When I execute the following code, I notice that `dialog` posseses an undocumented function:

```js
window.Office.context.ui.displayDialogAsync(
  loc,
  Object.assign(
    {
      displayInIframe: true
    },
    options
  ),
  asyncResult => {
    const dialog = asyncResult.value;
    console.log(dialog)
    // displays "OSF.DialogHandler {close: ƒ, addEventHandler: ƒ, sendMessage: ƒ}"
  }
);
```

As you can see at the above documentation link, only the following methods on Dialog are documented:
* close
* addEventHandler

It would be good to have documentation for `sendMessage` as well, and also how to add handlers from within the child dialog to receive messages from the parent.

Thanks!

**Comment by jrop** [comment]
Furthermore if I add this code in the dialog:

```js
// in dialog:
window.addEventListener('message', console.log(JSON.parse(e.data)))
```

And this in the task pane:

```js
dialog.sendMessage(JSON.stringify({hello: 'World'}))
```

Then I see this logged in the console:

```json5
{
  _messageType: 1,
  _actionName: "executeMethod",
  _conversationId: "-bd8cd38_-70e7ac05_1527164401310",
  _correlationId: 5,
  _origin: "...",
  _data: { Error: 5000, Version: 1 },
  _errorCode: 0,
  _responseType: 0,
  _serializerVersion: 1
}
```

**Comment by jrop** [comment]
@Rick-Kirkham Thanks for the info.  I am including from this URL:

```txt
https://appsforoffice.microsoft.com/lib/1/hosted/Office.js
```

**Comment by Rick-Kirkham** [comment]
@jrop Yes. I found it too. It's definitely there. The question is whether we support its use. I'm investigating.

**Comment by Rick-Kirkham** [comment]
@jrop This method is only supported in OneNote. I will add it to the documentation.

**Comment by jrop** [comment]
@Rick-Kirkham Thanks for the info

**Comment by Rick-Kirkham** [comment]
@jrop Lastest word is that we do not support its use even in OneNote. It is "For internal use only".

**Comment by jrop** [comment]
@Rick-Kirkham I appreciate you looking into this for me.  Thank you for the detailed and timely information
