### ISSUE TITLE
Not able to get entities when using getEntities()

### ISSUE THREAD

**Issue by Sheikz** [OfficeDev/office-js-docs#1434]
When I try this snippet as explained in the documentation for 1.3

```
var item = Office.context.mailbox.item;
// Get an array of strings that represent postal addresses in the current item.
var addresses = item.getEntitiesByType(Office.MailboxEnums.EntityType.Contact);
// Continue processing the array of addresses.
```

I get the error: 

> TypeError: Office.context.mailbox.item.getEntitiesByType is not a function

I am trying to get the contacts associated with this Item.
I am in an "New Appointment" item

Version is : 1.3
Permissions in the manifest are: ReadWriteItem
I am running the outlook add-in in Outlook 365 Online

Thanks for helping

**Comment by ElizabethSamuel-MSFT** [comment]
@exextoc : Please take a look. Thanks.

**Comment by exextoc** [comment]
`Office.context.mailbox.item.getEntitiesByType` is not supported for Messages and Appointments in compose. They are only supported when viewing existing items in Read mode.
