### ISSUE TITLE
No error or response from  getAccessTokenAsync() in word online

### ISSUE THREAD

**Issue by kim4848** [OfficeDev/office-js-docs#1435]
No error or response from  getAccessTokenAsync() when add-in is used i Word online, but if it is used in Powerpoint the  token is returned

**Comment by Rick-Kirkham** [comment]
Let's track this issue on the StackOverflow question here: https://stackoverflow.com/questions/50639239/word-online-sso-getaccesstokenasync-no-respons-no-error?noredirect=1#comment88401760_50639239
 
The issues for this repo are really intended for reporting mistakes in the documentation.
