### ISSUE TITLE
[LOC] [VaaS] Invalid links in an article

### ISSUE THREAD

**Issue by OfficeGSX** [OfficeDev/office-js-docs#1444]
**Current:** links redirect to 404 error page
**Expected:** links should redirect to valid page or be removed from the article

**Repro steps:**
1. go to https://dev.office.com/reference/add-ins/office-mix/labs.sendmessagecommanddata (or GH: https://github.com/OfficeDev/office-js-docs/blob/live/reference/office-mix/labs.sendmessagecommanddata.md)
2. search for "Labs.CommandType.TakeAction" and "Labs.Core.IMessage"
3. click the link(s) --> 404 error page

![office-js-docs](https://user-images.githubusercontent.com/16706698/41523494-79222c24-72da-11e8-83b9-046edbc9d7fb.PNG)

**Comment by lindalu-MSFT** [comment]
@keyur32 Can you have a look at this topic and fix the URL? I believe you're the author? If not, assign back to me and I'll investigate further.

**Comment by AlexJerabek** [comment]
The doc referenced in this issue no longer exists in our docs.microsoft.com doc set, so I'll close the issue.
