### ISSUE TITLE
Missing Link

### ISSUE THREAD

**Issue by mlafleur** [OfficeDev/office-js-docs#1445]
Word API's `body.search()` docs reference a sample but the link itself is invalid.

https://github.com/OfficeDev/office-js-docs/blob/master/reference/word/body.md

>  Additional information The [Word-Add-in-DocumentAssembly][body.search] sample provides another example of how to search a document

**Comment by lindalu-MSFT** [comment]
@mlafleur I can't repo this. Can you tell me what line has the broken link?

**Comment by ElizabethSamuel-MSFT** [comment]
@mlafleur: Took a look at the current body.search documentation (https://docs.microsoft.com/javascript/api/word/word.body?view=office-js#search-searchtext--searchoptions-) and the URL to the sample seems to be valid (see final comment at the end of the first/JavaScript code example).
