### ISSUE TITLE
Incomplete list of Word.UnderlineType enumeration

### ISSUE THREAD

**Issue by cindymeister** [OfficeDev/office-js-docs#1450]
The list of Word.UnderlineType is not complete. Has the list been expanded since the documentation was written for Requirement Set 1.1?

## Article URL
https://github.com/OfficeDev/office-js-docs/blob/master/reference/word/enums.md
https://dev.office.com/reference/add-ins/word/font

## Issue
I was working in Script Lab, where there's IntelliSense, and at the same time comparing the list of Word.UnderlineType available there with that on the dev.office.com site. I noticed that there are many more entries available than listed in the documentation. And the list on GitHub is not complete, either.

**Comment by AlexJerabek** [comment]
Hi @cindymeister, 
Thanks for pointing this out. Accurate type definitions can be found at the [DefinitelyTyped repo](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/office-js/index.d.ts). 

FWIW, we're in the process of converting our reference documentation to an autogenerated system based on that d.ts. Those docs should be released soon.

**Comment by cindymeister** [comment]
Thanks. I'll be looking forward to the update.

**Comment by AlexJerabek** [comment]
Hi @cindymeister 

We're still implementing the redirects from the old API reference site, but the new docs are live. 
https://docs.microsoft.com/en-us/javascript/api/word/word.font?view=office-js

These docs are generated from the information in Definitely Typed. They should perfectly match the current TypeScript definitions. If you find any discrepancies, please let us know on the [new repo](https://github.com/OfficeDev/office-js-docs-reference).
