### ISSUE TITLE
More then one dialog can be opened from Add-in Command 

### ISSUE THREAD

**Issue by dmitriyyepishin** [OfficeDev/office-js-docs#1456]
Docs state that "An Office Add-in can have only one dialog box open at any time." However, if opened from a Add-In command, more then one dialog can be opened at one time by clicking on the add-in command button repeatedly.

## Article URL
[displayDialogAsync documentation](https://github.com/OfficeDev/office-js-docs/blob/cb166f02ff90bae93b9740436295c7c300376dec/reference/shared/officeui.displaydialogasync.md)

Details on how to reproduce see the issue I filed with [Office JS](https://github.com/OfficeDev/office-js/issues/188)

**Comment by hengchengfei** [comment]
I had the same questions.

**Comment by Rick-Kirkham** [comment]
@hengchengfei This was corrected in the documentation last summer: https://docs.microsoft.com/en-us/javascript/api/office/office.ui?view=office-js

Please note also, that this repo is no longer the source documentation for our reference content, except for APIs that are in preview. That is why it no longer has a master branch. Old Issues that were raised in the repo still appear in search results.
