### ISSUE TITLE
Dialog is sized as percentage of current window

### ISSUE THREAD

**Issue by dmitriyyepishin** [OfficeDev/office-js-docs#1457]
The docs state that the width parameter "Defines the width of the dialog box as a percentage of the current display." However, actually, the dialog is sized as percentage of the currently active window, not current display.

## Article URL
[displayDialogAsync documentation](https://github.com/OfficeDev/office-js-docs/blob/cb166f02ff90bae93b9740436295c7c300376dec/reference/shared/officeui.displaydialogasync.md)

Details on how to reproduce see the issue I filed with [Office JS](https://github.com/OfficeDev/office-js/issues/189)

**Comment by Rick-Kirkham** [comment]
@dmitriyyepishin 
I know that what the documentation says was true at one time. I will investigate. It might be

**Comment by Rick-Kirkham** [comment]
This is being tracked on office-js, so closing this.
