### ISSUE TITLE
context.applicationObject.createDocument does not return Document object

### ISSUE THREAD

**Issue by vmrathod** [OfficeDev/office-js-docs#1459]
## Article URL

https://github.com/OfficeDev/office-js-docs/blob/master/reference/word/application.md
## Issue

According to documentation "**context.applicationObject.createDocument**" should return the "**Document**" object but with the latest version of Office.js API it's return "**DocumentCreated**"object. 
I want to use "**getFileAsync**" method after creating in memory document but I am not able to find "**getFileAsync**" on "**DocumentCreated**" object.

**Comment by Rick-Kirkham** [comment]
The documentation is erroneous. We are in the process of moving to a new reference documentation system. When that goes live in the next few weeks, the method description will correctly say that it returns a **DocumentCreated** object. The **DocumentCreated** object does not  have a `getFileAsync` method. You may be thinking of the Document object in the Shared Office APIs (https://dev.office.com/reference/add-ins/shared/document) which does have a getFileAsync.
