### ISSUE TITLE
Requirement Set documentation is not up to date concerning hosts

### ISSUE THREAD

**Issue by weird-dreams** [OfficeDev/office-js-docs#1463]
When looking in the methods for Example `Document.goToByIdAsync` there is PowerPoint Online available.
In the Requirement Sets there is only PowerPoint noted.
Please could you update all sets to represent the current status for each host.

**Comment by Rick-Kirkham** [comment]
@weird-dreams 
Could you clarify the problem? When I look at the reference topic https://dev.office.com/reference/add-ins/shared/document.gotobyidasync, it says that the method is not in any Requirement Set.

**Comment by weird-dreams** [comment]
Here is another example. 

**Requirement Set:**
![image](https://user-images.githubusercontent.com/11518242/43069314-0db3087e-8e6d-11e8-9b3f-5fd4e03e45c9.png)
_so **Selection** schould not be available for **PowerPoint Online**_

The Documentation for each method says it is available for  **PowerPoint Online**:
![image](https://user-images.githubusercontent.com/11518242/43069324-13a974c0-8e6d-11e8-878d-04fac8e59691.png)

![image](https://user-images.githubusercontent.com/11518242/43069332-18022184-8e6d-11e8-84bb-27841c1aae65.png)

_**When we use the requirement set it seems that the method perspective wins - the add in is also visible in PowerPoint Online.**_

**Comment by ElizabethSamuel-MSFT** [comment]
@weird-dreams: Thanks for pointing this out. The issues that you raised have already been addressed - see [Document](https://docs.microsoft.com/javascript/api/office/office.document), [Host and platform availability](https://docs.microsoft.com/office/dev/add-ins/overview/office-add-in-availability), [Common API requirement sets](https://docs.microsoft.com/office/dev/add-ins/reference/requirement-sets/office-add-in-requirement-sets). However, we'll do another pass to ensure that we have consistent support details across the documentation.

**Comment by ElizabethSamuel-MSFT** [comment]
@weird-dreams: We've updated the details per these PRs (https://github.com/OfficeDev/office-js-docs-reference/pull/247, https://github.com/OfficeDev/office-js-docs-pr/pull/568) and the changes should go live soon. If you do notice any other discrepancies, please let us know. Thanks.

**Comment by weird-dreams** [comment]
@ElizabethSamuel-MSFT Thank you!
