### ISSUE TITLE
delete() method‘s param is neccesary in Range.

### ISSUE THREAD

**Issue by hengchengfei** [OfficeDev/office-js-docs#1468]
## Article URL
https://dev.office.com/reference/add-ins/excel/range

## Issue
Range#Delete Method.
<img width="838" alt="1" src="https://user-images.githubusercontent.com/3182964/43306641-623dfd4c-91ae-11e8-8531-c37cc108c491.png">

There is likely an error in The Examples about Delete Method,.
```js
range.delete();
```
I test it , the delete method's param is neccesary.

```js
range.delete("Left");
//or
range.delete("Up");
```

##No param  Errors:
<img width="444" alt="2" src="https://user-images.githubusercontent.com/3182964/43306647-69609b5c-91ae-11e8-9fcd-3e10a57de8bd.png">

**Comment by Rick-Kirkham** [comment]
@hengchengfei 
Thanks. I've fixed this in the source file for the code example. Because we are currently transitioning to a new system for generating our API reference, it may be a few weeks before the fix is in the published version of the reference article.
