### ISSUE TITLE
suspendApiCalculationUntilNextSync example code doesn't use suspendApiCalculationUntilNextSync

### ISSUE THREAD

**Issue by evantrimboli** [OfficeDev/office-js-docs#1469]
## Article URL
https://github.com/OfficeDev/office-js-docs/blob/master/reference/excel/application.md

## Issue
In the example code section for `suspendApiCalculationUntilNextSync`, it demonstrates loading the `calculationMode`.

**Comment by Rick-Kirkham** [comment]
@evantrimboli 
This misunderstanding has come up before. It is a side effect of the formatting of our API reference articles. 

The section "**Property access examples**" is a peer of the **calculate** and **suspendApiCalculationUntilNextSync** sections. It is _not_ a subsection of the **suspendApiCalculationUntilNextSync** section. The "**Property access examples**" section gives code examples of reading/writing to properties of the class. In this case, the application class has only one property, so there is only one example in the section. There is no code example in the **suspendApiCalculationUntilNextSync** section.

Within the next few weeks we will switch to a new API reference system where this shouldn't happen anymore.
