### ISSUE TITLE
Outlook Add-In: Email from address, on behalf of, and forwarded

### ISSUE THREAD

**Issue by smiles2424** [OfficeDev/office-js-docs#147]
I am currently developing an Outlook add in using the Office.js API.

Two things I'm trying to do:

Check and see if a email has been forwarded. This seemed like something simple but it appears there is no field or way to detect this they checking a subject line for a 'FWD' which is unreliable. Any suggestions for this?

In Outlook, there is this concept of 'on behalf of' where a delegate sends an email but the from address shows another user. Is there a way of getting both of these users email addresses? I cannot seem to extract the delegates email from the API. 

Let me know if any additional information would help with this.

**Comment by jasonjoh** [comment]
1. On the detecting FWD, there's not really a way to do this. There is no property set that says "this message was sent to you as a forward." Essentially the email client copies the body from the original message and sets the subject as "FWD: " + original subject. The sender can edit it to remove this, so yes, it isn't reliable. Now the original message does have a property set on it to indicate that it has been forwarded, but it sounds like you're asking about the forwarded message, not the original.

2. You can do this in the JS api. Compare the `from` and `sender` properties. See https://dev.outlook.com/reference/add-ins/Office.context.mailbox.item.html#sender.
