### ISSUE TITLE
Visio - DocumentLoadCompleteEventArgs and PageLoadCompleteEventArgs sample code not working on IE11

### ISSUE THREAD

**Issue by joelfmrodrigues** [OfficeDev/office-js-docs#1470]
Hi, 

The sample code provided on the articles below doesn't seem to work on IE11
Works on Chrome and Edge.

## Article URL
https://dev.office.com/reference/add-ins/visio/pageloadcompleteeventargs
https://dev.office.com/reference/add-ins/visio/documentloadcompleteeventargs

## Issue
A detailed description of the problem can be found on a separate issue that I created on the office-js repository:
https://github.com/OfficeDev/office-js/issues/208

**Comment by ElizabethSamuel-MSFT** [comment]
Closing this as snippets had been updated due to conversation on related office-js issue.
