### ISSUE TITLE
"Was this page helpful" bar is broken on https://dev.office.com/reference/add-ins/shared/office.context.auth.getAccessTokenAsync

### ISSUE THREAD

**Issue by xstos** [OfficeDev/office-js-docs#1493]
"Was this page helpful" bar is broken on https://dev.office.com/reference/add-ins/shared/office.context.auth.getAccessTokenAsync

## Article URL
https://dev.office.com/reference/add-ins/shared/office.context.auth.getAccessTokenAsync

## Issue
The "Was this page helpful" bar doesn't work. Clicking either of the two buttons throws an error in the browser's error console. Tested in latest Chrome and IE 11.

rating.min.js?v={3/string}:1 Uncaught ReferenceError: ga is not defined
    at HTMLButtonElement.<anonymous> (rating.min.js?v={3/string}:1)
    at HTMLButtonElement.dispatch (jquery-1.11.1.min.js:3)
    at HTMLButtonElement.r.handle (jquery-1.11.1.min.js:3)

**Comment by Rick-Kirkham** [comment]
I can reproduce. Seems to be happening on all pages in dev.office.com.

**Comment by Rick-Kirkham** [comment]
@xstos 
We are transitioning to a new system for publishing reference content. This error is a side effect of that process. When the process is complete, the error should be gone.
