### ISSUE TITLE
Not able to find the Id of date picker content control using office.js API

### ISSUE THREAD

**Issue by vmrathod** [OfficeDev/office-js-docs#1498]
when I try to fetch the Ids of all the content controls on document using below code

` var contentControls = context.document.contentControls;`
`context.load(contentControls, 'id,subtype,type');`

This code is fetching the all the content controls ids except those content controls shown as **date picker**.
Need a solution how to read the date picker content controls.

**Comment by kbrandl** [comment]
This GitHub repository (**OfficeDev/office-js-docs**) is for reporting errors/issues with the API *documentation*.  While there is certainly some overlap at times, errors/issues with the API itself should be posted to the **OfficeDev/office-js** repository, which members of the product team monitor for customer-reported API issues such as this. Can you please post this issue to the [OfficeDev/office-js](https://github.com/OfficeDev/office-js/issues) repository instead? Thank you.
