### ISSUE TITLE
Event Listener for when conditional formatting changes [Excel] [Feature Request]

### ISSUE THREAD

**Issue by achang0406** [OfficeDev/office-js-docs#1503]
There are currently event listeners for `worksheet.onChanged`, `worksheet.onSelectionChanged`, `worksheet.bindings.onDataChanged`, etc...

We fail to find a listener to detect when conditional formatting changes.

Our current workaround is to compare the conditional formatting tree at every 5 second interval to identify whether conditional formatting has changed. This is expensive and performs poorly.

Is there a better way to detect whether conditional formatting has changed?

Not sure if a similar feature is already in the development but can this feature be requested?

**Comment by weshi** [comment]
Would you please provide more detail on the requirements and scenarios for this conditional format change event? What information do you need to be included in the event arguments when this event is fired?

**Comment by achang0406** [comment]
Sure thing.

Essentially we will need a a listener to be triggered anytime a conditional formatting gets added, deleted or modified. The event arguments should return…
1. list of conditional formatting thats are changed
   - how they are being changed (added, deleted, modified)
   - Worksheet and range of cells affected
   - the updated conditional formatting rule
   - Formatting style (font color, cell color, font style, etc)

   - Previous conditional formatting rule (this could be helpful?)
   - timestamp (this could be helpful?)

At a minimum, we will just need to know anytime a conditional formatting changes (added, deleted or modified) so we don't have to check every 5 seconds to compare the conditional formatting tree

**Comment by weshi** [comment]
Thank you @achang0406 for the information. Sorry for replying late. I am at the Ignite 2018 conference this week. We will include this requirement in our planning and get back where there is update. Thank you very much!

**Comment by achang0406** [comment]
Any chance you can also take a look at these two other issues? These are somewhat related.
https://github.com/OfficeDev/office-js-docs/issues/1507
https://github.com/OfficeDev/office-js-docs/issues/1508

These are all critical to our development cycle and future planning. I really appreciate you for being responsive thus far. I am looking forward to your updates.  Please let me know if I can help clarify anything. Thank you!

**Comment by weshi** [comment]
@achang0406 Thank you very much for these good feedback. We are tracking this requests in our internal planning. Once there is more update, will replay back. Thanks for your patience.

**Comment by weshi** [comment]
Tracked internally via 
Product Backlog Item 2626622: [Customer Ask] Event Listener for when conditional formatting changes

**Comment by kbrandl** [comment]
if you haven't already done so, can you please log this as a feature request in [UserVoice](https://officespdev.uservoice.com/)? We'll be archiving this repository (OfficeDev/office-js-docs) soon.
