### ISSUE TITLE
Unique Identifier for a defined name (name range) [Excel] [feature Request]

### ISSUE THREAD

**Issue by achang0406** [OfficeDev/office-js-docs#1508]
There is currently no reliable way to uniquely identify a defined name.

We are currently juggling with a few workarounds.

**workarounds**

---

_#1_
use worksheet + cell range to uniquely identify a defined name
for example: 
```
{
  worksheet1!A1:C4: definedName1,
  worksheet1!D23:F8: definedName2,
  ...
}
```
_risks_
There can be multiple defined names in the exact same worksheet + cell range.

---

_#2_
use the name of a defined name for its ID

_risks_
the name of defined names can be renamed which makes it not unique. Client side will have to somehow detect the change and edit all corresponding defined name which is an open issue, https://github.com/OfficeDev/office-js-docs/issues/1507.

---

**Proposed Solution**

Excel generates a unique ID when a defined name is created. The ID will be independent from the path of the cell range and the name of the defined name. Then this ID would be accessible from an API or the defined name object.

**Comment by weshi** [comment]
Does binding object help in this case? Binding has unique ID exposed in the API (https://github.com/OfficeDev/office-js-docs/blob/ExcelJs_OpenSpec/reference/excel/binding.md).

**Comment by achang0406** [comment]
We are having trouble seeing how the binding object is able to provide a unique ID for a defined name object that is independent from the cell range and the name of the defined name.

The binding object seem to provide a way to tie event listeners and attributes to a group of cells or individual cells but does not actually add attributes to the defined name object.

**Comment by kbrandl** [comment]
@achang0406 if you haven't already done so, can you please log this as a feature request in [UserVoice](https://officespdev.uservoice.com/)? We'll be archiving this repository (OfficeDev/office-js-docs) soon.
