### ISSUE TITLE
[Important]Need events for Office Web versions of Word and Excel

### ISSUE THREAD

**Issue by hengchengfei** [OfficeDev/office-js-docs#1509]
## Expected Behavior
The following list of events found on the client version of Word and Excel would aid in development of apps that work the same as current client addin apps work.

Excel Open Event
Excel Close Event
Excel BeforeClose Event
Workbook activate event

Word Open Event
Word Close Event
Word beforeClose event
Document activate event

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: ___PC desktop___
* Host [Excel, Word, PowerPoint, etc.]: ___Excel,Word___
* Office version number: __Office2016 and later____
* Operating System: __Windows____
* Browser (if using Office Online): ______

**Comment by kbrandl** [comment]
@hengchengfei if you haven't already done so, can you please log this as a feature request in [UserVoice](https://officespdev.uservoice.com/)? We'll be archiving this repository (OfficeDev/office-js-docs) soon.
