### ISSUE TITLE
When support the Shape object?

### ISSUE THREAD

**Issue by hengchengfei** [OfficeDev/office-js-docs#1511]
In VBA,VSTO,there are Shape Objects or InlineShape Objects.

When supported in Office-js?

**Comment by AlexJerabek** [comment]
Hi @hengchengfei, 

Shapes are in development now. If you import the office-js beta libraries, you can try out these APIs.
https://appsforoffice.microsoft.com/lib/beta/hosted/office.js
https://appsforoffice.microsoft.com/lib/beta/hosted/office.d.ts

**Comment by hengchengfei** [comment]
Now it had not been support in Word.

**Comment by AlexJerabek** [comment]
Hi @hengchengfei,
If you'd like to see JavaScript support for shapes in Word, please head to [UserVoice](https://officespdev.uservoice.com/) and suggest that feature. That helps our engineers prioritize new feature work for the platform.
Thanks!
