### ISSUE TITLE
Range.find SearchCriteria parameter should be optional

### ISSUE THREAD

**Issue by AlexJerabek** [OfficeDev/office-js-docs#1519]
## Product
Excel

## Feedback
`Range.find` currently has this signature: `find(text: string, criteria: Excel.SearchCriteria): Excel.Range;`. My proposal would be to change it to `find(text: string, criteria?: Excel.SearchCriteria): Excel.Range;`. Since every property of `SearchCriteria` has a default value, it doesn't make sense to force users to put an empty struct (`{}`) to get default search behavior.

**Comment by kbrandl** [comment]
Closing this issue, as it's already been addressed.
