### ISSUE TITLE
Casing suggestions in Excel 1.9 APIs

### ISSUE THREAD

**Issue by AlexJerabek** [OfficeDev/office-js-docs#1521]
## Product
Excel

## Feedback

Some fields aren't camel cased correctly. Here are the ones I found in the new APIs and my suggested replacements.

`ChartBoxwhiskerOptions` -> `ChartBoxWhiskerOptions`
`ChartSeries.boxwhiskerOptions` ->`ChartSeries.boxWhiskerOptions` 
`ChartSeries.xerrorBars` -> `ChartSeries.xErrorBars` 
`ChartSeries.yerrorBars` -> `ChartSeries.yErrorBars` 
`FillPattern.crissCross` -> `FillPattern.crisscross`
`PaperType.csheet` -> `PaperType.cSheet`
`PaperType.dsheet` -> `PaperType.dSheet`
`PaperType.esheet` -> `PaperType.eSheet`
`PivotField.sortByValues(sortby […]` -> `PivotField.sortByValues(sortBy […]` (x2)
`PivotLayout.setAutosortOnCell(sortby […]` -> `PivotLayout.setAutosortOnCell(sortBy […]` (x2)

**Comment by kbrandl** [comment]
Closing this issue, as it's already been addressed.
