### ISSUE TITLE
pivotTable have support Insert Calculated Field

### ISSUE THREAD

**Issue by dinglicoding** [OfficeDev/office-js-docs#1534]
i create a pivotTable but i can not find how to insert Calculated Field,is support in office.js?

if support have the demo?

thanks

**Comment by ElizabethSamuel-MSFT** [comment]
@dinglicoding: Thanks for your interest in Office Add-ins! However, it seems that this feature is not currently supported. We recommend that you request or upvote this feature on [UserVoice](https://officespdev.uservoice.com/) as we consider those votes when we prioritize new APIs.

Also, note that the latest Office Add-ins documentation has been moved from this repo (office-js-docs) to [office-js-docs-reference repo](https://github.com/OfficeDev/office-js-docs-reference) and [docs.microsoft.com](https://docs.microsoft.com/javascript/api/overview/office).

I'll close this issue now but if this is still a problem, let us know and we'll reactivate it.
