### ISSUE TITLE
[excel] can taskpane display left side of excel

### ISSUE THREAD

**Issue by dinglicoding** [OfficeDev/office-js-docs#1537]
hi

when show taskpane default in right side of excel .

1、it's any api change the default side? like left side of excel.

2、taskpane's width can change?  don't use mouse.

**Comment by Rick-Kirkham** [comment]
There is no way to do either of these things programmatically at this time. But they are both good ideas. Please go to Office Developer Suggestion Box and vote for these two: 

[Display taskpane on left of document](https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/suggestions/36297892-display-the-taskpane-on-the-left-of-the-document)

[Adjust taskpane width](https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/suggestions/8892379-adjust-taskpane-width)
