### ISSUE TITLE
Compatibility with office Excel 2019

### ISSUE THREAD

**Issue by sebisebo** [OfficeDev/office-js-docs#1538]
Hi,
I developed an Excel addin using office.js and it work fine on excel 2013, 2016, 365 but on 2019 it just show a blank page on excel side panel. Any idea of this problem ?
I can put html code of the first page in case.
Thanks

**Comment by sebisebo** [comment]
The first page is very simple furthemore, it just show three links

**Comment by Rick-Kirkham** [comment]
@sebisebo The issues in this repo are only used to track problems with the preview APIs in the Office JavaScript library. Please raise technical issues on StackOverflow (tagged `office-js`). If you are pretty sure that you have found a bug, you can raise the issue on the [office-js](https://github.com/OfficeDev/office-js) repo.
