### ISSUE TITLE
WordJs-1.3-OpenSpec-NewApplicationObject

### ISSUE THREAD

**Issue by nickdekesel** [OfficeDev/office-js-docs#173]
I think it would be nice if there was also a .close() function

**Comment by MIchaelMainer** [comment]
@nickdekesel can you explain your scenario that would use your proposed .close()? 

Thank you for the feedback. We do appreciate it. We've let API owners know about your requested feature.

**Comment by nickdekesel** [comment]
@MIchaelMainer Thanks for your reply!
When I create a new document with application.createDocument() I would like to close the new Word instantance after some time. For me both closing current Word instance from taskpane, and closing the one created from an other Word instance that opens the new document would be ok. I think the first scenario would be the nicest way to do it.

**Comment by lindalu-MSFT** [comment]
@JuaneloJuanelo @MIchaelMainer I am currently in a GitHub "issues bash" with the team going through all the old open issues in this repo. This looks to me like there is no follow-up required so I'm going to go ahead and close it. Feel free to open a NEW issue if this requires action.
