### ISSUE TITLE
TaskPaneAppVersionOverridesV1_0 schema indicates FunctionFile not required but Excel online fails with "invalid manifest"

### ISSUE THREAD

**Issue by jimbarrett33** [OfficeDev/office-js-docs#179]
The schema for task pane overrides has the following for FunctionFile which means it's not required.
    <xs:element name="FunctionFile" type="bt:URLResourceReference" minOccurs="0">

However, uploading a manifest to Excel online (Office 365) without the FunctionFile element fails with "invalid manifest" error.

I think the schema is correct since you shouldn't have to use a function file if you don't want to. You can still have actions that open the Task Pane though which does not require a function file.

**Comment by lindalu-MSFT** [comment]
@sumurthy I am in a GitHub bash right now going through old open issues. This is over 1.5 years old. Has this bug been verified? Please confirm where I need to update the documentation to reflect this.

**Comment by lindalu-MSFT** [comment]
@sumurthy Sudhi, I'm going to go ahead and close this issue because I see we have updated to docs here: https://dev.office.com/reference/add-ins/manifest/functionfile and here: https://dev.office.com/reference/add-ins/manifest/versionoverrides.
