### ISSUE TITLE
Office 365 app & Angular 2 routing only works the first time

### ISSUE THREAD

**Issue by mwchan** [OfficeDev/office-js-docs#194]
I am trying to get Angular 2 routing to work with Office App. It only works the first time and after that, it stops working. I have managed to get the same code to work with ASP.Net5 but not with Office Apps.

I am using Visual Studio Enterprise 2015 Update 2 and Office 2016. I have attached the solution to reproduce the issue.

Link to the solution files: https://onedrive.live.com/redir?resid=1D346F6F0769D8C!991&authkey=!AGQlHsr70YHepv4&ithint=file%2crar

Steps to reproduce:

1) Compile and run the solution.

2) Click on Page 1.

3) It will navigate to Page 1.

4) Click on Page 2 and nothing happens.

Repeat the above with Page 2 first and it will show Page 2. Somehow, it stops working after the first time. I can't figure out what I am doing incorrectly as I can't get such a simple example to work.

Then, I added the following and managed to get routing to work but only by using the navigateByUrl method.

The app.component.html is now:

```
<nav>
    <a [routerLink]="['PageOne']">Page 1</a>
    <a [routerLink]="['PageTwo']">Page 2</a>
</nav>
<button (click)="pOne()">Page 1</button>
<button (click)="pTwo()">Page 2</button>
<router-outlet></router-outlet>
```
And the app.component.ts is now:

```
import {Component} from 'angular2/core';
import {RouteConfig, Router, ROUTER_DIRECTIVES} from "angular2/router";
import {PageOneComponent} from "./pageone.component";
import {PageTwoComponent} from "./pagetwo.component";

@Component({
    selector: "my-app",
    templateUrl: "app/app.component.html",
    directives: [ROUTER_DIRECTIVES]
})
@RouteConfig([
    {
        path: "/pageone",
        name: "PageOne",
        component: PageOneComponent
    },
    {
        path: "/pagetwo",
        name: "PageTwo",
        component: PageTwoComponent
    }
])
export class AppComponent {
    constructor(private _router: Router) { }

    public pOne() {
        //this._router.navigate(["PageOne"]);
        this._router.navigateByUrl("/pageone", true);
    }

    public pTwo() {
        //this._router.navigate(["PageTwo"]);
        this._router.navigateByUrl("/pagetwo", true);
    }
}
```
As mentioned above, the navigate method will only work the first time and the navigateByUrl method will only work if you set _skipLocationChange to true.

Thanks in advance!

**Comment by mwchan** [comment]
Hi,

I am just wondering if there are any updates to this issue?

Cheers!

**Comment by WrathOfZombies** [comment]
Based on my preliminary evaluation, an exception is thrown when the router fires the first time itself, which unsubscribes all observers to the routing mechanism and hence it runs only the first time. The issue is isolated to the browser context of the Add-in canvas. We will investigate further and get back to you. 

Thank you for bringing this to our notice.

**Comment by mwchan** [comment]
Thanks for the update!

**Comment by WrathOfZombies** [comment]
Update:

The routing works in the rc 1.0 version of Angular2. I have attached a modified version of your original sample that shows the same. Please rename the file by removing the '.txt' extension and then extracting the contents.

I have also taken the liberty of modifying your code to point to the new Angular2 libraries and concepts. 

To start the project run `npm install` on the folder `OfficeApp4Web` and then run `npm start`. You can then press F5 in visualstudio to start debugging the add-in in excel.

Let us know if you have any issues.
Cheers.
[OfficeApp4.rar.txt](https://github.com/OfficeDev/office-js-docs/files/271584/OfficeApp4.rar.txt)
