### ISSUE TITLE
Unable to Sideload Add-in on Office for Mac

### ISSUE THREAD

**Issue by sameera** [OfficeDev/office-js-docs#195]
I've followed instructions at 
https://github.com/OfficeDev/office-js-docs/blob/master/docs/testing/sideload-an-office-add-in-on-ipad-and-mac.md
However, I'm not seeing the add-in on My Add-ins drop down even after a restarting the OS.
Inserting add-ins from the store continue to work as usual.

**Comment by smaremanda** [comment]
Hi Sameera - Could you please share more info on the issue you are having?
1. What OS are you trying to sideload your add-in on - OSX or iOS? OS Version?
2. Screenshot of the folder path with the add-in manifest file in Terminal.
3. Is the xml file you are trying to sideload a valid add-in manifest file? Could you please try sideloading on Win32 to see if the sideloading succeeds?

**Comment by sameera** [comment]
Thanks. 
I dropped the same manifest.xml file that the .Office project had generated in to the folder which didn't have the manufacturer field set. Once updated it did show up in the menu. I'm also new to the Mac, so I didn't realize clicking the 'x' didn't actually quit Excel :) Maybe that could have been the reason as well.

But, the add-in does not load inside the task pane (I'm seeing a blank page). It does work properly when side loaded in Office 365 online.
This is on OSX El Capitan, Office for Mac v15.21.1
We are using the Office.js 1.1 APIs. But, given that our initial pages load up correctly even if the URL in the manifest is opened up in the browser directly, I think this isn't an API compatibility issue. 
Is there any more information I can get you regarding this?

On a side note: Is there an equivalent of [F12 debugging approach](https://dev.office.com/docs/add-ins/testing/debug-add-ins-using-f12-developer-tools-on-windows-10) on the mac?

**Comment by mlafleur** [comment]
I'm have this issue using v15.24. Unable to sideload add-ins into Word, Excel or PowerPoint that are known to be working on Win32. In my case none of the add-ins are showing up in My Add-ins at all.

**Comment by sureshjoshi** [comment]
@sameera Did you ever have success with this? I'm not even able to get my add in to show up in the Word for Mac (15.35) plugins location at all. This is using the manifests from the example code here.

**Comment by sameera** [comment]
@sureshjoshi Yes, this is worked for us after sometime. We've had few issues that are specific to Excel for Mac, but apart from that, from a add-in loading perspective, yes, it's working for us now.

**Comment by mlafleur** [comment]
Make sure you're using the drop-down rather than simply clicking the add-in button itself (little down-arrow on it's right). Side-loaded add-ins don't show up in the dialog on the Mac.
