### ISSUE TITLE
office.js is down currently?

### ISSUE THREAD

**Issue by smiles2424** [OfficeDev/office-js-docs#199]
Not sure if this is the right place to post this but https://appsforoffice.microsoft.com/lib/1.1/hosted/office.js is currently down and potentially breaking javascript apps for anyone referencing it. Version 1 is not working either.

**Comment by TimMcMSFT** [comment]
I'm not currently seeing this issue--could you provide more details about how you're loading the files? Could you get a network trace?

**Comment by TimMcMSFT** [comment]
Looks like the issue has been resolved.
