### ISSUE TITLE
Needs specific Office build numbers

### ISSUE THREAD

**Issue by MJZawacki** [OfficeDev/office-js-docs#209]
I see Office 2013 specified on some of the RequirementSets. But what Office 2013 updates are required to use the new RequirementSets? The same thing can be said for Office 2016 when it is indicated as supported. I have multiple customers that are trying to test add-ins but aren't given any indication that they need to update their installation before these can be used.

**Comment by keyur32** [comment]
Thanks for the feedback. We will see how we can add the appropriate version numbers to our documentation and the [add-in availability](https://dev.office.com/add-in-availability) page.

**Comment by keyur32** [comment]
Hi there, these are all added in the relevant documentation now.
