### ISSUE TITLE
How do I generate a GUID?

### ISSUE THREAD

**Issue by giorgio79** [OfficeDev/office-js-docs#21]
Thx for the fantastic tutorial at https://github.com/OfficeDev/office-js-docs/blob/master/word/word-add-ins.md

How do I generate a GUID at step 5? I hope I dont have to install Visual Studio for that. Can I use some of the tools mentioned here? http://stackoverflow.com/questions/105034/create-guid-uuid-in-javascript

PS I am playing with this one https://www.guidgenerator.com

**Comment by MIchaelMainer** [comment]
@giorgio79 Thank you for the feedback! We really value it! Yeah, you can use any tool to generate the GUID.
