### ISSUE TITLE
Images broken on Office Dev center

### ISSUE THREAD

**Issue by dougperkes** [OfficeDev/office-js-docs#211]
The images for https://github.com/OfficeDev/office-js-docs/blob/master/docs/testing/debug-add-ins-using-f12-developer-tools-on-windows-10.md are broken on the office dev center http://dev.office.com/docs/add-ins/testing/debug-add-ins-using-f12-developer-tools-on-windows-10.

**Comment by Lauragra** [comment]
I don't repro this in IE or Chrome. What browser are you using?

**Comment by dougperkes** [comment]
Very strange...they were broken a few minutes ago on Edge. I guess it's a no-repro issue.
