### ISSUE TITLE
Is the network folder necessary in the tutorial?

### ISSUE THREAD

**Issue by giorgio79** [OfficeDev/office-js-docs#22]
Step 7 talks about a network folder. Can I use a local C:\... folder? 

https://github.com/OfficeDev/office-js-docs/blob/master/word/word-add-ins.md

PS Looks like it is as Office only accepts URLs for trusted addin locations...This helped http://windows.microsoft.com/en-us/windows-vista/share-files-and-folders-over-the-network-from-windows-vista-inside-out

**Comment by MIchaelMainer** [comment]
@giorgio79 No, a network folder is not really necessary. I'm considering an update to the walkthrough that will use a simple http server since many people may not have network shares available to them.

**Comment by MIchaelMainer** [comment]
Added link to https://technet.microsoft.com/en-us/library/cc770880.aspx to provide access to manifest files on the local machine.
