### ISSUE TITLE
Invalid parameter in Office.context.ui.messageParent

### ISSUE THREAD

**Issue by dougperkes** [OfficeDev/office-js-docs#222]
There appears to be a documentation bug in for the [`Office.context.ui.messageParent` method](https://github.com/OfficeDev/office-js-docs/blob/master/reference/shared/officeui.md).

The documentation states that messageParent receives and object as the parameter, however when I attempt to send an object as the parameter I get the error message "Function messageParent has invalid parameters.". If I convert my object to a string, the method call succeeds. 
##### Example Code

``` Javascript
var oauthResult = { success: true, token: tokenStored };
//This call fails with error "Function messageParent has invalid parameters."
Office.context.ui.messageParent(oauthResult);
//This call succeeds
Office.context.ui.messageParent(JSON.stringify(oauthResult));
```

**Comment by dougperkes** [comment]
@LezaMax Could you check this out?

**Comment by LezaMax** [comment]
This was fixed already on the docs.

**Comment by craigomatic** [comment]
I realise this is an older issue, however the wording of the current docs are a little misleading with their use of 'object' and 'any' on the param:

**messageParent(messageObject)**

 `messageParent(messageObject: any): void;`

Parameters
`messageObject any `

Accepts a message from the dialog to deliver to the add-in.

https://docs.microsoft.com/en-us/javascript/api/office/office.ui?view=office-js#messageparent-messageobject-
