### ISSUE TITLE
Is the only use for document.Open() to follow on from the application.createDocument() method?

### ISSUE THREAD

**Issue by Falkayn** [OfficeDev/office-js-docs#224]
There is not much context given in the docs for how the document.Open() method is intended to be used. Right now it seems to only be useful after using the application.createDocument() method - which leaves you with a temp document that does not yet show in the UI for the user.

Are there any other scenarios where this is likely to be useful? Can this please be added to the docs?

Thanks,
Angus

**Comment by keyur32** [comment]
Hi there,  can you provide a link to the topic? Are you referring to the Office Javascript API or was this question about the COM object model (use by VSTO add-ins).

**Comment by Falkayn** [comment]
This is the one I was looking at:
https://github.com/OfficeDev/office-js-docs/blob/WordJs_1.3_Openspec/word/resources/document.md#open

I'm only interested in the OfficeJS API.

**Comment by JuaneloJuanelo** [comment]
Well, kind of. you need to use document.open, with a document created with application.createDocument.

The idea behind these methods is that you can actually create a temporary document (by using application.createDocument)  you can optionally start with a base64 docx.  then you can use the API to manipulate the temp doc (for instance, to add more paragraphs, search, formatting, etc). Finally you call document.open on that temp object. at that point the document will be visible to the user, however, you cannot longer use that document handle, at this point is lost.

There are thousands of scenarios for this, but a very common one is to "redact" a document. so basically the user wants to redact portions of an existing document, and create a new one with the redacted text (the text is actually removed on the new doc, but preserved on the original one).

Another is to just open another document that comes from a template gallery.

hope this helps.

**Comment by Falkayn** [comment]
Can you open a task pane within the document that you are opening - so it is already open when the user sees it?

**Comment by JuaneloJuanelo** [comment]
yes if the provided base64 encoded includes and embedded task pane add-in. if you have commands defined they will also show up in the opened document.

**Comment by hengchengfei** [comment]
I want to fill content to the new document(myNewDoc ), not the context.document.

But the follows code ,fill content to the context.document.

How can I fill content to the new document(myNewDoc ).

```js
    function hightlightLongestWord() {
        Word.run(function (context) {
 
            var myNewDoc = context.application.createDocument(getDocumentAsBase64());

            context.load(myNewDoc);

            var range = myNewDoc.getSelection();
            range.insertText("<h1>Hello world.</h1>", Word.InsertLocation.start);

            return context.sync().then(function () {
                myNewDoc.open();

                context.sync();
            }).catch(function (e) {
                console.log(e);
            })
             
        })
        .catch(errorHandler);
    } 
```

**Comment by kbrandl** [comment]
Closing this issue, as it seems the original inquiry has been addressed. Also, on a related note -- the `open()` method exists on the [DocumentCreated](https://docs.microsoft.com/en-us/javascript/api/word/word.documentcreated?view=office-js#open--) object (which is returned by [Application.createDocument](https://docs.microsoft.com/en-us/javascript/api/word/word.application?view=office-js#createdocument-base64file-)).
