### ISSUE TITLE
would like to be able to search just the docs

### ISSUE THREAD

**Issue by jbarr33** [OfficeDev/office-js-docs#231]
search all of dev.office.com makes finding things more difficult

**Comment by Lauragra** [comment]
Thanks for the feedback. We have filed a bug and will update the Search functionality on the site to include a scoped search of the doc set.

**Comment by keyur32** [comment]
Hi Jim, hope you're well. We made a fix awhile back to put the docs up at the top most link for now. That said, we realize the site search is not a great experience and we're working on plans to evolve this.  Over the course of the next 6 months, you will start to see some of our documentation start to leverage the docs.microsoft.com platform, which in turn will bring both contextual site search, as well as the ability to quickly filter the table of contents based off keywords, copy buttons on snippets, etc.  Once our docs there, we will be using that search experience for both dev.office.com and graph.microsoft.io.  Thanks!
