### ISSUE TITLE
Possibility to host a service within an Office Add-In

### ISSUE THREAD

**Issue by andry-tino** [OfficeDev/office-js-docs#236]
Hello. I posted this question here on StackOverflow as well: [Exposing a service endpoint from within an Office Add-In](http://stackoverflow.com/questions/37366652/exposing-a-service-endpoint-from-within-an-office-add-in).

Concisely, I am trying to create an add-in. Inside it, I want to expose a service endpoint so that I can call it from some other application (it would be an HTTP binding reachable over TCP/IP).

    --------------------------          -----------
    | Add-In || Service:port | <======= | Process |
    --------------------------          -----------

Is this possible?

### Alternatives
I searched a bit, but it seems like the API are not including components to define services. This kinda seems reasonable as a whole hosting environment would be needed.

However, we are talking about Javascript API, so I was hoping that maybe [WebSockets](https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API) could be used. My point here is to be able to contact the add-in from outside avoiding the add-in to poll for messages to a whatever service endpoint.

What options do I have to achieve this?

**Comment by andry-tino** [comment]
This might be related to [Can i use WebSocket or Socket.io in add-ins?](https://github.com/OfficeDev/office-js-docs/issues/70), however I am asking if, before getting there, it is possible to access API which allow developers to host a service within an add-in, so not exactly a duplicate of this issue I referenced.

**Comment by mlafleur** [comment]
Add-ins just web pages run within a browser context. In the web clients they are hosted within an IFRAME and with fat-clients they are hosted within an embedded browser instance. As such, you they live within the browser's sandbox. It also operates exclusively over HTTPS. 

I'm not 100% clear on the scenario here but it sounds like you have a local application that you wish to communicate directly with the add-in? You may be able to accomplish this by using the add-in's web host as a proxy between the two but I image this become rather complex rather quickly. 

In most cases where I've run into a scenario like this, the native app is better served by connecting to the Graph API and interactive with the mailbox directly.

**Comment by keyur32** [comment]
I'm not sure I understand the scenario here, but I think Marc's comments are on point above. Please re-activate if you have any follow up questions. thank you.

**Comment by andry-tino** [comment]
Hi all. Yes the replies actually answered my question :) Thanks
