### ISSUE TITLE
The long insertion in Word Online

### ISSUE THREAD

**Issue by ArtemZinenko** [OfficeDev/office-js-docs#237]
I use Word API 1.1 to insert text into a document in Word Online. It works but the inserting takes a very long time (10-15 seconds) and spinner toggles 6 times during this time (see attached pic).
Did I do something wrong? Or is it an api bug?

```
        Word.run(function (context) {
            var sections = context.document.sections;
            context.load(sections, 'body/style');
            return context.sync().then(function () {
                var section = sections.items[sections.items.length-1];
                var header = section.getHeader("primary");
                var body = section.body;
                var footer = section.getFooter("primary");
                header.clear();
                footer.clear();
                header.insertOoxml(ooxmlHeader, Word.InsertLocation.end);
                body.insertOoxml(ooxmlBody, Word.InsertLocation.end);
                footer.insertOoxml(ooxmlFooter, Word.InsertLocation.end);
                return context.sync().then(function () {
                    //app.showNotification("Successful");
                });
            });
        }).catch(function (error) {
            console.log(error);
            app.showNotification("Error: Invalid OOXXL");
        });
```

![1](https://cloud.githubusercontent.com/assets/18261451/15474962/0a5a6e3c-2110-11e6-958b-9f1af89efd79.png)

**Comment by AlexYovenko** [comment]
Maybe it's because you try to insert header\footer and body of the document in separate call?

Office-JS team, is this possible to insert header\footer and body in one insertOoxml call or by using other method?

**Comment by OleksiiD** [comment]
Experiencing the same issue.

Cannot find solution for now. Very upset, as it is a real showstopper for my project.

**Comment by weshi** [comment]
The behavior here is expected. Currently the insertOoxml call needs to go to server side, which is a costly call and the latency is several seconds. We recommend that you only call this method for operations that cannot be achieved via other client side methods, such as insertText() or insertParagraph, etc.

**Comment by AlexYovenko** [comment]
Weshi, please advice how we can found what method is server side  and what is client side?
Few more questions:
1)We want to insert formatted text to header\footer\body, with using insertText and insertParagraph we will lose formatting, I am right?

2)Is this possible to insert into document header&footer&body section by one call insertOoxml or similar function that support formatting?

**Comment by weshi** [comment]
All the insertOoxml(), insertFileFromBase64() are implemented using server side solutions. Others are mainly implemented in client side. 

In most cases, you can prepare a starting document template and get the ooxml representation of the whole whole template, then call insertOoxml just once to insert that ooxml representation into the document. And then you can call other methods to manipulate it. 

Because we need to return the Range object of each insertOoxml() call, we cannot combine the operations into a single call. 

We are working on the support of insertHtml() method to insert formatted text into document. You can also change the format by set the font or style properties of various objects such as Range, Paragraph, etc.

**Comment by Jias-MS** [comment]
Hi, Alex.

If you use insertText\insertParagraph to insert some text\paragraph to header\footer\body, the formatting of inserted text will keep the same as those content around depending on the arguments you provide.

As weshi said, insertHtml can be used to inserted formmatted text.

**Comment by AlexYovenko** [comment]
weshi,
We use exactly the same use case that you descibe, so we have get template and based on template create document, then get OOXML of it and send to API, like result only body part will be updated. Header and footer stay untached. 

Jias-MS ,

we try to create solution that will help to reuse already created set of templates in Office online and Office for IPad, so get text as plain text from template\document then assign format arguments will be not very good ides, or if I do not understand you please advice.

**Comment by weshi** [comment]
I see. Right now the OOXML related API has this performance limitation in Word Online. We will continue to look at the improvements. If you can share your sample code with me, I'll try to see if it's possible to optimize the calls.

**Comment by AlexYovenko** [comment]
I am using similar code as from initial comment. Take 3 sections and call insertOoxml for each of them.

Maybe I miss something and exist some other method in API that will allow me to insert formatted text from template\document to hole document from one call? 

Or maybe other client side methods that can insert formatted text exist in API?

Please advice.

**Comment by Jias-MS** [comment]
InsertHtml can be used to insert formatted text and InsertHtml is implemented on client side. You can try to use html to achieve your goal. 

However, InsertHtml isn't able to support all the formatting now.

**Comment by AlexYovenko** [comment]
Thank you for reply @Jias-MS,
but how I will get HTML from MS Word template\document?

**Comment by Jias-MS** [comment]
You can design the HTML content with inline formatting depending on your needs.
Such as:
' <p>This is <sup>superscripted</sup> text.</p><p>This is <sub>subscripted</sub> text.</p><p>My favorite <ins>color</ins> is red.</p><p>My favorite color is <del>blue</del> red.</p><h2>HTML <mark>Marked</mark> Formatting</h2><h2>HTML <small>Small</small> Formatting</h2><p><em>This text is emphasized.</em></p><p><i>This text is italic.</i></p>'

**Comment by Jias-MS** [comment]
You can design the HTML content with inline formatting depending on your needs.

I suggest you can call insertOoxml to insert the original template\document firstly, and then choose to use insertHtml to replace the partial content with formatted text.

In this way, the HTML that you need to provide should be simple, so you can directly design it.

**Comment by AlexYovenko** [comment]
I see your point now, but the problem here that all templates already exist and I just need re-use them, without conversion to HTML format.

Any other idea to make it faster then currently or avoid 3 server base calls?

**Comment by weshi** [comment]
Currently there is no better way to do it. If you want to reuse the templates, you have to use getOoxml() to get the OpenXML representation of the template, and then call insertOoxml() to insert it into the documents you want to create. However, once the starting doc is created, you should avoid using too many insertOoxml() calls. Instead please use insertText/insertParagraph/insertHtml etc. to do small changes. You can also set the paragraph or range styles, fonts with the corresponding style or font properties.

**Comment by AlexYovenko** [comment]
Thank you @weshi. But in next API version we will have a method that will load content of whole documet and applyt it currently opened on the screen with all sections and data, right?

**Comment by ArtemZinenko** [comment]
@weshi, Can I call the methods header.insertOoxml(...), body.insertOoxml(...) and footer.insertOoxml(...) asynchronously and thereby make insertion more quickly?

**Comment by mlafleur** [comment]
@ArtemZinenko Are you asking if you could break each insertOoxml() into separate command queues to execute all three methods in parallel? Unfortunately no, that won't work. The first context.sync() will block execution until it returns. If anything this will slow down the process.

**Comment by weshi** [comment]
@AlexYovenko I guess you meant the createNewDocument() API? That will not be available for Word Online in the short term. Although insertOoxml() has its performance limitation, but the good thing is that it supports all contents that may not be available in Word Online. You can view it as a high fidelity solution.

**Comment by AlexYovenko** [comment]
@weshi can you be more specific, 
_>not be available for Word Online in the short term_

it's means in next 3 month or 6|9|12 month?

**Comment by weshi** [comment]
@ArtemZinenko No, you cannot execute any commands in parallel. The calls are executed in the order as they appear in the queues, and the operations are applied to the document sequentially. However your idea of parallel operations is interesting to me. Besides the reason that you want to make it faster, what are the scenarios you want to enable?

**Comment by weshi** [comment]
@AlexYovenko For Word Online, the createNewDocument() API may not be available at least in the next 6 months. This will be in a separate requirement set. We will plan on it.

**Comment by ArtemZinenko** [comment]
@weshi, it would be great if I could change the different sections or parts (header, body, footer etc.) of a document at the same time. In theory it will not lead to a conflict of data but will speed up the work of inserting and editing the document.

**Comment by weshi** [comment]
@ArtemZinenko I like your idea of running the commands in parallel. We will consider this in the improvement planning. Thanks.

**Comment by OleksiiD** [comment]
Parallel edits of different sections sounds very good, where I can vote for this improvement?:)

**Comment by weshi** [comment]
@OleksiiD Sorry I missed your question here. There is no place to vote for this now. But thank you for your suggestion. We will consider this when we do the planning.

**Comment by kbrandl** [comment]
Closing this issue, as the original inquiry has been addressed. For future reference, you can log (and vote for) Office.js feature requests in [UserVoice](https://officespdev.uservoice.com/).
