### ISSUE TITLE
Office.context.document.getFileAsync not working on excel

### ISSUE THREAD

**Issue by AJYadav** [OfficeDev/office-js-docs#242]
Hi,
I am using Office.context.document.getFileAsync to upload the current document in word. In excel it says 'undefined'. I checked online documentation it says its not support for excel desktop. 
Is it supported in some beta release ?
Do we have any alternative for it ?

**Comment by brian-2447** [comment]
I have the same issue. Please at least provide a work around. It's urgent. Thanks

**Comment by tacticiankerala** [comment]
I also faced the same issue with Office.js v1.1. Any update on this issue will be appreciated.

**Comment by mimisasouvanh** [comment]
It is not yet supported. You can use Excel.js to load data into worksheets and tables. See https://github.com/OfficeDev/Excel-Add-in-JS-QuarterlySalesReport for a sample on how to load data. To load an xlsx file, you can load one on startup. See the Excel Humongous insurance sample: https://github.com/OfficeDev/Excel-Content-Add-in-Humongous-Insurance
Hope this helps!

**Comment by lushanbo** [comment]
This API already can be used, you can reference : https://dev.office.com/reference/add-ins/shared/document.getfileasync  for more detail.

**Comment by mimisasouvanh** [comment]
@lushanbo Apologies - I misread. Thought @AJYadav meant insertFile. Will close this, as its resolved.

**Comment by stijnkiers** [comment]
When trying to use the getFileAsync function from Excel the request fails with error code 7000 and message "You don't have sufficient permissions for this action.". According to the documentation (https://github.com/OfficeDev/office-js-docs/blob/master/reference/javascript-api-for-office-error-codes.md) error code 7000 means invalid ID. I cannot find which ID though.
I use exactly the same code in Word, Powerpoint and Excel Online, where it all works.

If getFileAsync now works in the Excel client, could you update the documentation accordingly (https://github.com/OfficeDev/office-js-docs/issues/1089) and perhaps help me find out what I am doing wrong?

**Comment by stijnkiers** [comment]
Apparently the function works in version 1708, which is not yet available with an dev subscription. At least my problem is solved.

**Comment by yihuax** [comment]
This API was implemented in late May and shipped later (July?). So I guess the API is not supported in the old version of Excel you were using.

**Comment by yihuax** [comment]
This API requires the permission of reading whole document.
