### ISSUE TITLE
Is Worksheet Visibility a read-only property (Excel)?

### ISSUE THREAD

**Issue by erinreily** [OfficeDev/office-js-docs#244]
I'm trying to hide the active worksheet in an open Excel workbook with an add-in and JavaScript. I edited the Sheet Switcher Sample (Home.js file) at https://github.com/OfficeDev/Excel-Add-in-JS-SheetSwitcher and added a hideSheet() function. Here is the snippet:

	function hideSheet() {
	    Excel.run(function (ctx) {
	        var activeWorksheet = ctx.workbook.worksheets.getActiveWorksheet();
	        activeWorksheet.visibility = "Hidden";
	        return ctx.sync().then(function () {
	            app.showNotification(activeWorksheet.visibility);
	        });
	    })
	    .catch(function (error) {
	        app.showNotification("Error: " + error);
	        console.log("Error: " + error);
	        if (error instanceof OfficeExtension.Error) {
	            console.log("Debug info: " + JSON.stringify(error.debugInfo));
	        }
	    });
	}

If I replace "visibility" with "name," the other string property, it works. Is visibility inaccessible this way? Is there a workaround?

**Comment by sumurthy** [comment]
Which version of Excel are you running the add-in on? At one point, we had visibility as read-only - but it was changed in the 1.2 version of the API set. If you wish to take advantage, then you need to use the recent Excel versions.

**Comment by erinreily** [comment]
I played around with it a bit and looked through the documentation but I couldn't find anything helpful. I am running the latest version of Excel 2016. Do I need to specify in my code to use the 1.2 API? I tried adding a requirements section in he XML file and tried using a runtime check in the .js file. Neither of those worked.

**Comment by erinreily** [comment]
Not sure what happened but the same code is now working. I'll close this.
