### ISSUE TITLE
Discrepancy between spec and implementation of paragraph object.

### ISSUE THREAD

**Issue by chbighammsft** [OfficeDev/office-js-docs#246]
It looks like there is a discrepancy between the spec and the implementation of the paragraph object. 

In the spec, it says that the paragraph object has a "getTextRanges" method. That method is actually on the range object. To access the text ranges in a paragraph, you have to call

paragraph.getRanges().getTextRanges([string].bool);

**Comment by kbrandl** [comment]
@chbighammsft thanks for the feedback and apologies for the slow response on this. According to current docs, the `getTextRanges` method is supported on both the Paragraph object and the Range object.

- https://docs.microsoft.com/en-us/javascript/api/word/word.paragraph?view=office-js#gettextranges-endingmarks--trimspacing-

- https://docs.microsoft.com/en-us/javascript/api/word/word.range?view=office-js#gettextranges-endingmarks--trimspacing-

We'll make sure the code example for `Paragraph.getTextRanges` gets updated to show the method being used on the Paragraph object. Thanks again for the feedback.
