### ISSUE TITLE
Get wrong parent content control from selection

### ISSUE THREAD

**Issue by yuanwei0525** [OfficeDev/office-js-docs#259]
To Whom It May Concern,
There seems an issue of getting correct parent content control when selecting an image inside picture content control.
Here is the way of how to reproduce this issue:
1. Create a rich text content control with tag to "RichTextTag"
2. Type some characters in content control "RichTextTag" and insert a picture content control (tag "ImageTag") inside this "RichTextTag" content control. This is very important, another rich text content control here is OK, so far I only found problem with picture content control.
3. Insert an image (123.png) to this image content control "ImageTag"
4. Make sure that current selection is on image (123.png) only. I opened VBA editor and 
? selection.range.parentContentControl.tag
"ImageTag"
5. Run sample javascript to getSelection().parentContentControl, and load
6. In callback function, the parent content control tag is "RichTextTag" instead of "ImageTag"
Cheers
Wei

Another issue might be related to this one:
1. I saved this docx into word open xml file, and get <w:sdtPr>/<w:id w:val="12345"> of "ImageTag" content control
2. Run context.document.contentControls.getById(12345) and load
3. sync gives exception instead of loading content control properties

**Comment by keyur32** [comment]
Hey, @JuaneloJuanelo, looks like I missed assigning this to you earlier this, can you help with this one?

**Comment by keyur32** [comment]
Hi there, it appears the WordJS API is not aware of any content control other than rich text content controls. You will need to parse the OOXML to get the information they want.   

To send feedback, please log this request in [User Voice](https://officespdev.uservoice.com/). Thank you.
