### ISSUE TITLE
Feature request: Passing in a regular expression instead of plain text for search

### ISSUE THREAD

**Issue by giorgio79** [OfficeDev/office-js-docs#26]
Hello,

Would love to pass in a regular expression instead of plain text for search (https://github.com/OfficeDev/office-js-docs/blob/master/word/word-add-ins-javascript-reference/body.md#searchsearchtext-string-searchoptions-paramtypestringssearchoptions)

**Comment by MIchaelMainer** [comment]
Thank you @giorgio79. I've passed on your feedback.

@JuaneloJuanelo
