### ISSUE TITLE
Inserting of firstPage and evenPages header/footer does not works

### ISSUE THREAD

**Issue by ArtemZinenko** [OfficeDev/office-js-docs#268]
I use Word API 1.1 to insert header and footer into a document in Word 2016 (desktop version). Insert only works for primary headers and footers. The code runs without error. What can be wrong?

```
            Word.run(function (context) {
                var sections = context.document.sections;
                context.load(sections, 'body/style');
                return context.sync().then(function () {
                    var section = sections.items[0];
                    //
                    var primaryHeader = section.getHeader("primary");
                    var firstPageHeader = section.getHeader("firstPage");
                    var evenPagesHeader = section.getHeader("evenPages");
                    var primaryFooter = section.getFooter("primary");
                    var firstPageFooter = section.getFooter("firstPage");
                    var evenPagesFooter = section.getFooter("evenPages");
                    //
                    primaryHeader.insertText("primaryHeader", Word.InsertLocation.start);
                    firstPageHeader.insertText("firstPageHeader", Word.InsertLocation.start);
                    evenPagesHeader.insertText("evenPagesHeader", Word.InsertLocation.start);
                    primaryFooter.insertText("primaryFooter", Word.InsertLocation.start);
                    firstPageFooter.insertText("firstPageFooter", Word.InsertLocation.start);
                    evenPagesFooter.insertText("evenPagesFooter", Word.InsertLocation.start);
                    return context.sync().then(function () {
                        // console.log("Completed");
                    });
                });
            }).catch(function (error) {
                console.log(error);
            });
```

**Comment by XuejiSun** [comment]
Hey Artem, I ran your code in my desktop and found the code works. After running the code, you can double click the header/footer area to bring out the tab of "Header & Footer Tools -- Design" on ribbon .Then inside the tab, under "options" area, please check "Different First Pages" and "Different Odd & Even Pages". then you will see the result showed out inside the footer/header area. Hope this is what you are looking for.

**Comment by ArtemZinenko** [comment]
@XuejiSun , you're right, thank you. But as I understand it, I can't change the settings (see attached pictures) via Word API, is it?
![2](https://cloud.githubusercontent.com/assets/18261451/15866230/75629862-2ce6-11e6-80f6-dc308dbbe036.png)

**Comment by XuejiSun** [comment]
As far as I know you are right, on API level you can't change that setting instead of the content of header/footer.:)

**Comment by ArtemZinenko** [comment]
@JuaneloJuanelo , please tell me, is there any way to solve my problem?

**Comment by mlafleur** [comment]
At the moment, there isn't a way to programmatically change the Header & Footer options using Web Add-ins. 

The only option I'm aware of for changing the default options is to make those changes to the [Normal template](https://support.office.com/en-us/article/Change-the-default-settings-for-new-documents-430B4132-E129-46E4-97D2-19C326352C7F). If you're only deploying to internal users you could distribute this updated Normal to the users. If you are deploying to external users (i.e. publishing to the Office Store) then you would have to provide documentation explaining to users how to make this change themselves.
