### ISSUE TITLE
Missing text from "Tip" in 

### ISSUE THREAD

**Issue by Rick-Kirkham** [OfficeDev/office-js-docs#270]
The file create-better-add-ins-for-word-with-office-open-xml.md has a "Tip" about half way down that ends with the sentence "To remove RSID tags from an existing document, try the following shortcut with the document open in Office Open XML:"  But there is nothing below this in the tip. The shortcut isn't there.

**Comment by Lauragra** [comment]
Thanks; I just updated the file to include the content that was dropped.
