### ISSUE TITLE
Link on "Outlook add-in APIs" is incorrect

### ISSUE THREAD

**Issue by dalemy** [OfficeDev/office-js-docs#273]
On this page: http://dev.office.com/docs/add-ins/outlook/apis right at the bottom there is an additional resources section. The first link "Outlook Add-in API" currently points to http://dev.office.com/reference/add-ins/outlook/index but should either be removed since that page doesn't exist, or point to http://dev.office.com/reference/add-ins/outlook/1.2/index (the most recent version of the API)

**Comment by Lauragra** [comment]
Thank you for the feedback. I have removed the broken link from the topic. Note that the latest version of the API is 1.3. We will work toward making this more clear on the site.
