### ISSUE TITLE
Mislabelled link in https://dev.office.com/docs/add-ins/develop/bind-to-regions-in-a-document-or-spreadsheet

### ISSUE THREAD

**Issue by Rick-Kirkham** [OfficeDev/office-js-docs#276]
In https://dev.office.com/docs/add-ins/develop/bind-to-regions-in-a-document-or-spreadsheet

Near the top is this sentence:
"The Bindings object exposes a getAllAsync method that gives access to the set of all bindings established on the document or spreadsheet. An individual binding can be accessed by its ID using either the Bindings.getBindingByIdAsync or Office.select methods."
The link "Bindings.getBindingByIdAsync" near the end of the sentence should be "Bindings.getByIdAsync". The latter is what it actually links to.

**Comment by Lauragra** [comment]
Fixed!
