### ISSUE TITLE
InlinePicture object

### ISSUE THREAD

**Issue by Joylim** [OfficeDev/office-js-docs#277]
Hello, I want to get the imagebase64 string of image in word when developing an add-ins.
But I log output of picbase64.value is undefined and what's wrong with the code as follows:

var pictures = paragraphs.items[0].inlinePictures;
context.load(pictures);
return context.sync().then(function () {
                    var picture = pictures.items[0];
                    context.load(picture);
                    var picbase64 = picture.getBase64ImageSrc();
                    console.log("base64 string is " + picbase64.value);
});

Many thanks!

**Comment by mlafleur** [comment]
Looks like the documentation for getBase64ImageSrc() is a bit sparse/off. It should mention that this call requires the context to re-sync before it populates the value. I'll update it to better reflect how this works. 

In the meantime, your example should look more like this:
```js
var pictures = paragraphs.items[0].inlinePictures;
context.load(pictures);
return context.sync().then(function () {
     var picture = pictures.items[0];
     context.load(picture);
     var picbase64 = picture.getBase64ImageSrc();
     return context.sync()then(function () {
          console.log("base64 string is " + picbase64 .value);
     });
});
```

**Comment by Joylim** [comment]
Thanks a lot!!!!
