### ISSUE TITLE
Excel Commands Manifest - using &amp; in the group name fails to add the group to the ribbon

### ISSUE THREAD

**Issue by jbarr33** [OfficeDev/office-js-docs#279]
As an XML file the ampersand character must be escaped in the manifest file.  However, if you try to use it for the group name the group is never added to the ribbon.
 Ex.  <bt:String id="id_label_GroupName" DefaultValue="This &amp; That"/>

workaround is to use the long name "This and That" instead of "This & That" but many other group names on the Excel Ribbon use the ampersand to separate words (presumably to save space).

**Comment by keyur32** [comment]
Thanks for the feedback @jbarr33.  We are thinking about ways to make the manifest file a bit easier. Along with both the Office add-in and Microsoft Graph docs easier to find and use.  We'd love to chat offline. If you're intereste, ping me at kepatel@microsoft.com.
