### ISSUE TITLE
ImageCoercion not enabled in Excel 2016/Excel online

### ISSUE THREAD

**Issue by brucemcpherson** [OfficeDev/office-js-docs#289]
I'm trying to use ImageCoercion as in 

```
  Office.context.document.setSelectedDataAsync (png, {
        coercionType:Office.CoercionType.Image,
        imageLeft:offx ,
        imageRight:offy 
      } .... etc.
```

However this is refused by Excel 2016 & Excel Online. I did this to see what was supported (im using api v1.1)

```
   ['TextBindings','TextCoercion','TableCoercion','TableBindings','Settings',
        'MatrixBindings','MatrixCoercion','ImageCoercion','DocumentEvents',
        'BindingEvents','ExcelApi'].forEach(function (d) {
          console.log(d+':'+Office.context.requirements.isSetSupported(d,'1.1'));
        });
```

and it confirmed that ImageCoercion is not supported

```
TextBindings:true
TextCoercion:true
TableCoercion:true
TableBindings:true
Settings:true
MatrixBindings:true
MatrixCoercion:true
ImageCoercion:false
DocumentEvents:true
BindingEvents:true
ExcelApi:true
```

If I make it a requirement, the add-in fails to load at all.

```
 <Requirements>
    <Sets DefaultMinVersion="1.1">
      <Set Name="ImageCoercion" MinVersion="1.1"/>
   </Sets>
   <Methods>
      <Method Name="Document.getSelectedDataAsync"/>
   </Methods>
</Requirements>
```

The docs suggest that Excel should support ImageCoercion (https://dev.office.com/reference/add-ins/shared/document.setselecteddataasync)

> Base64 encoded image stream (Office.CoercionType.Image) - Applies to Excel, PowerPoint, Word and Word Online only.

Should ImageCoercion actually work in Excel ?

Additional info. For testing I fell back to the sample project created by  yeoman with yo office and confirmed that ImageCoercion is not supported. I then created the sample project that comes  with Visual Studio, added the same code, and ImageCoercion is supported. I then copied the manifest from VS to the Yo sample and it still shows as unsupported. So the issue is somehow between the VS environment and the simple YO environment. The same result for both content and taskpane.

**Comment by brucemcpherson** [comment]
I realize now that this may be a yo  office generator issue rather than  a general api issue, and that they have their own repo. - Ive cross posted it to there https://github.com/OfficeDev/generator-office/issues/168

**Comment by nokafor** [comment]
Hey @brucemcpherson I have confirmed that ImageCoercion is not currently available in Excel. We are currently fixing the doc you highlighted. For future reference, we will be maintaining [this page](https://dev.office.com/add-in-availability) to reflect where APIs and features are available.

**Comment by tarunmangukiya** [comment]
Any update on this?
My Add-In is failed for submission for this issue?
