### ISSUE TITLE
(Overview )Tutorial examples, copy/paste error

### ISSUE THREAD

**Issue by JohnAustin-MSFT** [OfficeDev/office-js-docs#29]
The last example before the error code table is copied exactly from the example before it.  It should show the application of a formula across a range. Instead, it shows the application of a value across the range - the same as the previous example.

**Comment by sumurthy** [comment]
Good catch. We'll fix it as soon as possible.

**Comment by umasubra** [comment]
The code snippet is now fixed...Thanks for bringing it to our attention.
