### ISSUE TITLE
Can not find drop down content controls

### ISSUE THREAD

**Issue by yuanwei0525** [OfficeDev/office-js-docs#290]
Hello,
I might find an issue of unable to get content control object of drop down content control by looping through all content controls in document.

Steps to reproduce:
1. Create a rich text content control with tag "RichTextTag"
2. Type something inside and create a drop down content control in document with tag "DropDownTag" inside rich text content control "RichTextTag"
2. run sample javascript of getting all content controls in document
3. loop through content control one by one and console.log tag
4. drop down content control (DropDownTag) is not logged but RichTextTag is

**Comment by keyur32** [comment]
Hi @JuaneloJuanelo, can you help with these please?

**Comment by keyur32** [comment]
Hi there, it appears the WordJS API is not aware of any content control other than rich text content controls. You will need to parse the OOXML to get the information they want.   

To send feedback, please log this request in [User Voice](https://officespdev.uservoice.com/). Thank you.
