### ISSUE TITLE
Using the browser control in the taskpane?

### ISSUE THREAD

**Issue by giorgio79** [OfficeDev/office-js-docs#30]
I noticed the snippets catch console errors, but wondered if we could somehow enable the browser console. I find the browser version much better :)

**Comment by MIchaelMainer** [comment]
@giorgio79 I'm confused. All of the snippets in the documentation use console.log(). Do you mean the snippets in office-js-snippet-explorer? Yeah, the snippet explorer overrides console.log.

**Comment by giorgio79** [comment]
When using the desktop Word 2016 how does one view the console output in the task pane (without catching the errors and outputting them in a textarea or some div)? :) Maybe I am just making a rookie mistake, and I missed sg. 
I imagine in Office Live the console errors appear just fine with console.log.
According to this blog entry, these new js apis are only available in the desktop versions so far http://dev.office.com/blogs/Office-js-Public-Preview

**Comment by MIchaelMainer** [comment]
Use [Visual Studio](https://www.visualstudio.com/en-us/products/visual-studio-community-vs.aspx) and attach the script debugger to the IE process that hosts the add-in.  To make it easier to find the process, close all instances of IE from your desktop, and then look for the x86 IE process in the Attach to Process window.
![image1](https://cloud.githubusercontent.com/assets/8527305/10531658/5ac4aa2c-7369-11e5-8632-4ee90388d154.png)
![image2](https://cloud.githubusercontent.com/assets/8527305/10531718/1450d498-736a-11e5-8b08-17340ded6b16.png)
