### ISSUE TITLE
Manifest designer no longer comes up

### ISSUE THREAD

**Issue by JVimes** [OfficeDev/office-js-docs#305]
I'm on Update 3 RC of Visual Studio Community 2015 (v14.0.25402.00 Update 3 RC), and I just installed the latest Office Developer tools (v14.0.23928.0 in Programs and Features). I'm creating new Outlook web add-in projects. The manifest designer no longer comes up for newly created projects. It comes up for Mail projects, as they used to be called, created in an older version of the Office Developer Tools (from sometime around Aug. 2015). I think this must either be a bug or the documentation are out of date since they [still talk about](https://github.com/OfficeDev/office-js-docs/blob/master/docs/get-started/create-and-debug-office-add-ins-in-visual-studio.md) the manifest designer. I hope it's not going away.

**Comment by mlafleur** [comment]
This was intentionally removed (I believe in Update 2). The existing designer was unable to accommodate the newer manifest elements (i.e. version overrides and add-in commands). This presents a problem as many of these new features have become required for submitting to the Store. 

I'll leave it to the product team to comment on when/if a designer will come back but for the time being the manifest XML needs to be edited directly.

**Comment by keyur32** [comment]
Yes, I believe this was intentional as we added Add-in commands. I don't know if there are any current plans for this but you can leave feedback on [User Voice](https://officespdev.uservoice.com/). 

Marc, already removed the references to the designer a few weeks ago. thanks @mlafleur.
