### ISSUE TITLE
File not found Outlook 2016 Mac javascript api

### ISSUE THREAD

**Issue by zzOzz** [OfficeDev/office-js-docs#319]
When including https://appsforoffice.microsoft.com/lib/1.1/hosted/office.js
Outlook complement try to load https://appsforoffice.microsoft.com/lib/1.1/hosted/outlook-mac-16.00.js
that is not longer available on Microsoft servers (404)

source file joined

[index.html.zip](https://github.com/OfficeDev/office-js-docs/files/331540/index.html.zip)

**Comment by mlafleur** [comment]
Looking at the attached code, you're making several references that are either invalid or outdated. 

Try removing the following:
```js
<script src="https://appsforoffice.microsoft.com/lib/1.1/hosted/office.js" type="text/javascript"></script>
<script type="text/javascript" id="HOST" src="https://appsforoffice.microsoft.com/lib/1.1/hosted/outlook-mac-16.00.js"></script>
<script type="text/javascript" id="OFFICESTRINGS" src="https://appsforoffice.microsoft.com/lib/1.1/hosted/fr-fr/office_strings.js"></script>
```
and replace it with 
```js
<script src="https://appsforoffice.microsoft.com/lib/1/hosted/Office.js" type="text/javascript"></script>
```

This should always grab the latest 1.x library and handle loading the proper string resources for the user's current language. See [Outlook Add-in APIs](http://dev.office.com/docs/add-ins/outlook/apis) for additional detail.

**Comment by nokafor** [comment]
This issue seems to be resolved, so I am closing it. Please reopen if more help is needed!
