### ISSUE TITLE
Excel object is not documented

### ISSUE THREAD

**Issue by JohnAustin-MSFT** [OfficeDev/office-js-docs#32]
The Excel object exposes a run method but it is not clear what (if any) value such as a promise is returned. Are other methods exposed on Excel?  It would be good to document it.

**Comment by sumurthy** [comment]
Thanks for your question. 
Excel.run() provides a batch environment for commands to run. It's main goal is to automatically clean-up references created within the batch. .sync() method synchronizes the client/Excel document states and returns the promise.
Programming overview has the details.. We'll make this more clear in the next iteration. 
https://github.com/OfficeDev/office-js-docs/blob/master/excel/excel-add-ins-programming-overview.md
Let us know if you have any question.
