### ISSUE TITLE
Ribbon shows in Excel Online but not offline

### ISSUE THREAD

**Issue by jonasrk** [OfficeDev/office-js-docs#321]
I have an Add-In with its own Ribbon that works fine in Excel online but does not show the Ribbon in Excel (locally). There, it only shows the default task-pane.

Why could that be?

**Comment by Lauragra** [comment]
Hi jonasrk, 
Can you let us know what version of Excel you are running locally?

Thanks,
Laura

**Comment by jonasrk** [comment]
Thanks for your reply. This is a duplicate now of this: https://github.com/OfficeDev/Office-Add-in-Commands-Samples/issues/14 where I provided more detailed info.

**Comment by Lauragra** [comment]
Okay, great; I'll close the issue here then. Thanks.
