### ISSUE TITLE
Support for custom worksheet functions in Excel?

### ISSUE THREAD

**Issue by jimmcslim** [OfficeDev/office-js-docs#328]
The XLL API in desktop Excel allows an XLL add-in to define its own custom worksheet functions such that the calculation engine in Excel can be extended (this can also be done via VBA). It would be fantastic if the JavaScript API also supported this type of extension.

**Comment by sumurthy** [comment]
Please track here: https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/suggestions/6936956-add-user-defined-function-support-to-the-apps-for

Custom functions are part of the roadmap.

**Comment by jimmcslim** [comment]
Awesome. It would be great if Microsoft could share the roadmap with us, for a rough idea of when this feature might be delivered (as part of an Office 2016 update, or Office 2017/2018?)... I'm trying to figure out a strategy for an energy analysis tool.
