### ISSUE TITLE
Wrapping OOXML APIs Needed

### ISSUE THREAD

**Issue by ronjonesjr** [OfficeDev/office-js-docs#333]
The API makes it very very difficult to wrap content in the underlying OOXML with additional OOXML. 

SUGGESTION: It would be great if there were a range.insertComment, range.insertBookmark that worked exactly like range.insertContentControl does!  Or please give us a method to get the current OOXML fragment represented by a range.  I'm trying to insert bookmarks and I've seen others trying to insert comments, around the selected text.  The getOoxml() methods are great if you're writing copy/paste functionality, but that doesn't help you if you're trying to manipulate/wrap the fragment.

**Comment by mlafleur** [comment]
Hi @ronjonesjr, these are very interesting ideas. This particular repo however is focused only on the documentation set. I'd recommend posting your suggestion in the [Office Dev UserVoice](https://officespdev.uservoice.com/) so it can reach the proper audience.

**Comment by ronjonesjr** [comment]
Thanks for the great direction and pointer!  Here's a link to the [suggestion](https://officespdev.uservoice.com/forums/224641-general/suggestions/15055839-wrapping-ooxml-apis-needed-insertcomment-insert).

**Comment by Lauragra** [comment]
Thanks, all! I'll close this issue for now.
