### ISSUE TITLE
What is the expected release date for v1.3 office.js  preview version?

### ISSUE THREAD

**Issue by pradeepgaba** [OfficeDev/office-js-docs#335]
https://github.com/OfficeDev/office-js-docs/tree/WordJs_1.3_Openspec

**Comment by AlexJerabek** [comment]
Apologies for the lack of response. Version 1.3 of the Word JavaScript API was released last year. You can find more information on our [requirement set page](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/requirement-sets/word-api-requirement-sets?view=office-js#whats-new-in-word-javascript-api-13).

Closing the issue
