### ISSUE TITLE
Add-In Commands Ribbon shows in Excel Online but not in Excel for Windows

### ISSUE THREAD

**Issue by jonasrk** [OfficeDev/office-js-docs#336]
I have an Add-In with its own Ribbon that works fine in Excel online but does not show the Ribbon in Excel on Windows [1]. There, it only shows the default task-pane.

To make sure it does not have to do with my own manifest, I verified this with the OfficeDev simple Sample manifest [2]. The only two modifications I did to the xml file are replacing 2 instances of `Document` with `Workbook`.

Also, I have verified this on two computers.

Why could that be?

[1] Microsoft Excel 2016 MSO (16.0.4266.1003) 32-Bit on Windows 10
[2] https://github.com/OfficeDev/Office-Add-in-Commands-Samples/blob/master/Simple/Manifest/SimpleAddin.xml

**Comment by MIchaelMainer** [comment]
Answered here
http://stackoverflow.com/questions/38205471/add-in-commands-ribbon-shows-in-excel-online-but-not-in-excel-for-windows/38208590#38208590
