### ISSUE TITLE
Could we use OneDrive to host the addon? (ssl / https requirement)

### ISSUE THREAD

**Issue by giorgio79** [OfficeDev/office-js-docs#34]
I noticed the SourceLocation requires an https location. SSL can be pain to setup and maintain (until this comes out https://letsencrypt.org/ :) ), so it would be great if we could host addons on onedrive. Or maybe Azure with a discount? :P

**Comment by MIchaelMainer** [comment]
@giorgio79 That would be a great question for StackOverflow! Make sure to use the office-js and onedrive tags.
