### ISSUE TITLE
add(type: string, sourceData: Range, seriesBy: string)

### ISSUE THREAD

**Issue by alastairUK** [OfficeDev/office-js-docs#341]
For the "type" parameter you have:

Represents the type of a chart. Possible values are: ColumnClustered, ColumnStacked, ColumnStacked100, BarClustered, BarStacked, BarStacked100, LineStacked, LineStacked100, LineMarkers, LineMarkersStacked, LineMarkersStacked100, PieOfPie, etc.

Can you list ALL the options for this rather than using etc.? Or add a link to Excel.ChartType?

**Comment by jozefizso** [comment]
@Lauragra @danielmgalan @davidchesnut

**Comment by umasubra** [comment]
Thanks for the feedback! We've now updated the parameter description with all of the possible values. 

Copying them here as well:

Below are the valid chart types:

ColumnClustered, ColumnStacked, ColumnStacked100, _3DColumnClustered, _3DColumnStacked, _3DColumnStacked100, BarClustered, BarStacked, BarStacked100, _3DBarClustered, _3DBarStacked, _3DBarStacked100, LineStacked, LineStacked100, LineMarkers, LineMarkersStacked, LineMarkersStacked100, PieOfPie, PieExploded, _3DPieExploded, BarOfPie, XYScatterSmooth, XYScatterSmoothNoMarkers, XYScatterLines, XYScatterLinesNoMarkers, AreaStacked, AreaStacked100, _3DAreaStacked, _3DAreaStacked100, DoughnutExploded, RadarMarkers, RadarFilled, Surface, SurfaceWireframe, SurfaceTopView, SurfaceTopViewWireframe, Bubble, Bubble3DEffect, StockHLC, StockOHLC, StockVHLC, StockVOHLC, CylinderColClustered, CylinderColStacked, CylinderColStacked100, CylinderBarClustered, CylinderBarStacked, CylinderBarStacked100, CylinderCol, ConeColClustered, ConeColStacked, ConeColStacked100, ConeBarClustered, ConeBarStacked, ConeBarStacked100, ConeCol, PyramidColClustered, PyramidColStacked, PyramidColStacked100, PyramidBarClustered, PyramidBarStacked, PyramidBarStacked100, PyramidCol, _3DColumn, Line, _3DLine, _3DPie, Pie, XYScatter, _3DArea, Area, Doughnut, Radar

Thanks!

**Comment by umasubra** [comment]
Addressed the feedback. Closing the issue.
