### ISSUE TITLE
Event Batch API questions

### ISSUE THREAD

**Issue by mikaa123** [OfficeDev/office-js-docs#342]
Hello,

First, apologies if this is not the best place to ask.

I'd like to know if the upcoming Event Batch API addresses problems such as (http://stackoverflow.com/questions/33571914/new-outlook-api-2015-mail-add-in-send-event), namely, being able to hook on events such as 'ItemSend'?

Also, it would be awesome to have an idea of when this API is going to start rolling out!
Thanks

**Comment by jasonjoh** [comment]
@mikaa123 Which Event Batch API are you referring to? I'm not familiar :).

**Comment by mikaa123** [comment]
@jasonjoh hi ! To this open-spec: https://github.com/OfficeDev/office-js-docs/tree/EventApi_BatchSyntax_OpenSpec, I guess I wasn't using the correct name :)

**Comment by jasonjoh** [comment]
Ok. Let me check with the engineering folks and get back.

**Comment by jasonjoh** [comment]
@mikaa123 This method won't enable catching item send type events. The Outlook team is working on a solution for this, but this API isn't it :). I don't have an ETA to share on this at this time.

**Comment by mikaa123** [comment]
@jasonjoh Ok, thanks :) Good to know it's in the pipe!

**Comment by mikaa123** [comment]
Hey there,
just checking in to see if progress is being made on the subject :)
