### ISSUE TITLE
Boilerplate Add-in Doesn't Show in 

### ISSUE THREAD

**Issue by joshglenn** [OfficeDev/office-js-docs#347]
Following the instructions on this page: https://dev.office.com/docs/add-ins/word/word-add-ins

Trying to install the Boilerplate addin on Microsoft Word v 15.22.1. After following the instructions step-by-step, I hit a wall. 

When I try this step:

> Open Word 2016 on the Mac and click on the Insert tab > My Add-ins drop down. You should see the add-in listed in the drop down. Select it and it will load the add-in.

My add-in does not show up. Any idea why?

**Comment by joshglenn** [comment]
So, as it turns out, I was using a file location in the:

```<SourceLocation DefaultValue="/Users/[username]/path/to/file" />```

That did not work for me. I had to use an actual http address (connecting to an instance of python's SimpleHTTPServer) like this instead:

```
<SourceLocation DefaultValue="http://127.0.0.1:8000/home.html" />
```

It should probably be noted in the docs that that is a http endpoint and not a filesystem endpoint

**Comment by Lauragra** [comment]
Hi joshglenn, thank you for your comment. We'll look into clarifying this in the docs.

**Comment by joshglenn** [comment]
Thanks very much. Closing this now.
