### ISSUE TITLE
Issue with Office.context.mailbox.item.attachments

### ISSUE THREAD

**Issue by YannickGagnon** [OfficeDev/office-js-docs#350]
I'm currently prototyping a small Outlook Add-in which I'm able to retrieve most everything except attachments.

**Office.context.mailbox.item.attachments** is always undefined even if I did add attachments to my email.

**Test environment:**

- Project built with Yeoman generator-office
- Served with gulp serve-static locally
- Run in OWA

Thanks,

**Comment by YannickGagnon** [comment]
Just realized attachments property is only available in Read context, what if I want to validate attachment name, type before sending the email, thus in compose context, is there a way around this?

Thanks,

**Comment by Lauragra** [comment]
Hi Yannick, 
Thanks for contacting us. This repo is primarily for issues with the documentation. I suggest that you try posting this question to [Stackoverflow](http://stackoverflow.com/questions/tagged/office-js) and tag it with "office-js". I'll close this issue for now. Please feel free to reopen if we can be of further assistance. Thanks.
