### ISSUE TITLE
Link issue from MailBox to permissions

### ISSUE THREAD

**Issue by YannickGagnon** [OfficeDev/office-js-docs#354]
The link **Specify permissions for mail add-in access to the user's mailbox.** from [https://dev.outlook.com/reference/add-ins/Office.context.mailbox.html#makeEwsRequestAsync](url) is dead even though it works in github

**Comment by Lauragra** [comment]
Thanks! We'll get this fixed shortly.

**Comment by Lauragra** [comment]
The link is fixed now! Thanks.
