### ISSUE TITLE
Task pane app not keeps the paragraph number

### ISSUE THREAD

**Issue by techvenky** [OfficeDev/office-js-docs#355]
I am using the below code to get selected text as HTML, but in result html the paragraph number is always starts new.

Example:
If i select paragraph from 2.4 and in html it shows 2.1.

Using Word 2013, Offices JS (1.1)

`  Office.context.document.getSelectedDataAsync(Office.CoercionType.Html, {
            asyncContext: text
        },
            function (result) {
                if (result.status === Office.AsyncResultStatus.Succeeded) {
                    selectHTML = result.value;                   
                } else {
                    app.showNotification('Error:', result.error.message);
                }
            }
            );`

**Comment by Lauragra** [comment]
Hi techvenky, thanks for contacting us. This repo is primarily for issues with the documentation. I recommend that you try posting your question to [StackOverflow](http://stackoverflow.com/questions/tagged/office-js), tagged with office-js. If you have a suggestion for how we can help clarify the documentation, please feel free to reopen this issue. Thanks!
