### ISSUE TITLE
local reference to Office.js for offline debugging not working

### ISSUE THREAD

**Issue by jonasrk** [OfficeDev/office-js-docs#356]
Hi!

I'm developing Excel Add-Ins using the yo generator provided by MS.

When I comment out the online office.js import and uncomment the offline one, office.js does not load.

I've been testing this on a freshly generated `yo office` project (Task-Pane, Excel, HTML/CSS/JS) and encounter the same behavior on Microsoft Excel for Mac Version 15.23.2 (160624) as well as Excel Online in Chrome.

Here's what I tried:

- replace the capital O in the Office folder of the path to a lower case o since this is how it is stored in my file-system: didn't work

- renaming that folder in my file system to capital O: didn't work

- moving the file office.js into the project root and adjusting the import reference: didn't work

- replacing the office.js provided by the generator with the file that is referenced in the online reference (`appsforoffice.microsoft.com/lib/1/hosted/office.js`): didn't work

It would be really nice if someone could look into this as it would be super nice to have offline debugging working ... thanks!

**Comment by Lauragra** [comment]
Hi jonsark, I see that you have posted this question to StackOverflow, so I'll close the issue here. This repo is primarily for feedback on the documentation. If we can clarify the documentation to help resolve your issue. please feel free to reopen. Thanks!
