### ISSUE TITLE
IndexedDB/WebSQL is unsupported in Office for Mac

### ISSUE THREAD

**Issue by sameera** [OfficeDev/office-js-docs#361]
We have a fairly complex AddIn that depends on IndexedDB/WebSQL for local storage. This works on all environments except for Office for Mac and Safari (likely iPad too). 

The error that's thrown is DOM Exception 18 and on Safari it can be worked around by setting the cookie and local data storage to "Allways Allow" in settings. 
Is there a workaround for Office for Mac?

**Comment by smaremanda** [comment]
hi Sameera - Unfortunately this is a known issue and a bug on the Office for Mac add-ins platform and we are actively working to resolve it. We could suggest some potential workarounds, if you can elaborate on your scenario.

**Comment by sameera** [comment]
Hi,
Thanks for confirming the issue. We are using YDN-DB to abstract the storage mechanism and it would have automatically fallen back to local storage if the either Indexed DB or Web SQL were not supported. Unfortunately, in this case it seems that the environment declares WebSQL is supported (I can see that in Vorlon's mondernizer tab as well as if I load a html5 test page inside an addin). Because of this the automatic fallback doesn't happen. 

We can force YDN-DB to use a specific mechanism as well (eg in a `catch` block). So, we can workaround this. However, the ideal case is that we do have either IndexedDB or WebSQL support as it would perform better with indexed queries.

Regrading the issue with Safari:
Safari's default preferences are set to allow "Cookies and Website data" from "websites I visit". Unless this setting is changed to Always Allow, the local storage will also fail. I'm guessing that this is because the add-ins get served from an iframe and Safari treats the add-in the same way it would treat a banner advert coming from a third party website. If so, is there anything the Office team can do about this?
