### ISSUE TITLE
Excel UDF support

### ISSUE THREAD

**Issue by sumigoma** [OfficeDev/office-js-docs#364]
When will we finally get support for JS user-defined functions in office.js? Google Docs add-ons have supported custom formulas for a long time and are now even usable on Android. UDF support is a strong requirement for us and cannot come soon enough.
https://excel.uservoice.com/forums/274580-excel-online/suggestions/10243059-support-udf-user-defined-function-in-excel-online

**Comment by mlafleur** [comment]
This forum is focused on documentation issues rather than feature requests. User Voice is a much better forum for feature requests and I can attest to it being actively followed by the product teams. 

As an aside, this suggestion just got 3 votes from me. ;)
