### ISSUE TITLE
would like to be able to get/set document variables

### ISSUE THREAD

**Issue by ArtemZinenko** [OfficeDev/office-js-docs#367]
If it were possible to get/set variables in the settings part of document it would be great.
This possibility exists in the Shared API but it stores variables in other document part (see atached screen)

My dream:
![mydream](https://cloud.githubusercontent.com/assets/18261451/17364911/ba801088-598b-11e6-94c0-01d33198baf6.png)

Realities (using Shared API):
![realities](https://cloud.githubusercontent.com/assets/18261451/17364916/beff993a-598b-11e6-9a2e-8bdf1cd13f31.png)

**Comment by keyur32** [comment]
Hi there, thanks for the suggestion. Can you log this issue in our user voice please at  http://officespdev.uservoice.com? This will allow others to see it and vote on the suggestion, which will help us prioritize this request.  Thank you.

**Comment by keyur32** [comment]
Also, in your user voice post, can you describe your goal and how storing the settings in a different part of the file format will help achieve that?  Thanks and feel free to re-activate if you have any follow up questions.
