### ISSUE TITLE
Menu links for Excel/ChartTitleFormat and Excel/TableRowCollection are broken

### ISSUE THREAD

**Issue by cgcai** [OfficeDev/office-js-docs#375]
From the API reference at `http://dev.office.com/reference/add-ins/excel/application`,

1. Clicking on Excel/ChartTitleFormat redirects to a "notfound" page. However, a direct link to ChartTitleFormat works: `http://dev.office.com/reference/add-ins/excel/charttitleFormat`
2. Clicking on Excel/TableRowCollection redirects to a "notfound" page. Similarly, a direct link works: `http://dev.office.com/reference/add-ins/excel/tablerowCollection`

The root cause is those links trying to load those respective pages from `devofficecdn.azureedge.net` over `https`. Loading the links of `http` resolves the issue.

**Comment by Lauragra** [comment]
Thanks; I'll look into this.

**Comment by Lauragra** [comment]
The fix has been published live; closing this issue.
