### ISSUE TITLE
Add and delete NamedItem in Excel?

### ISSUE THREAD

**Issue by chewspot** [OfficeDev/office-js-docs#376]
I've had a look at Excel API v1.3, but other than the new namedItemCollection.getItemOrNull(), there's nothing in the API to support adding/deleting named items.

Is this functionality hidden somewhere else in the API? If not, can I suggest it be added?

    // Adding new names?
    let name: Excel.NamedItem = ctx.workbook.names.add("accountNum", "Sheet1!B3");
    let name: Excel.NamedItem = ctx.workbook.names.add("accountNum", rangeObject);

    // maybe with a parameter object for future extension?
    let name: Excel.NamedItem = ctx.workbook.names.add({ name: "accountNum", refersTo: rangeObject });

    // Deleting names
    name.delete();

**Comment by Lauragra** [comment]
Thank you for the suggestion! We have added this to our product backlog.

**Comment by chewspot** [comment]
Thanks for the reply. I have a few more questions/suggestions. Should I create a new issue for each one (Excel.Range.style, Excel.Range....) or group them by class (eg, Excel.Range)?
