### ISSUE TITLE
Get/set Excel.Range.style

### ISSUE THREAD

**Issue by chewspot** [OfficeDev/office-js-docs#377]
Currently, Excel.Range exposes the `format` property, where individual properties can be set:

    let format = rn.format;
    format.font.name = "Calibri";
    format.font.color = "#00ff00";
    format.font.size = 12;

It would be nice if we could get/set a range's style using one of the preset (or custom) styles.
e.g, "Accent 1", "40% -  Accent 1", "Accent 2"

Like what is already done for Excel.Table `Excel.table.style`   

    // Just like Excel.Table.style
    let table:Excel.Table;
    table.style = "TableStyleLight1";

    // Do the same for Excel.Range?
    let rn:Excel.Range = ctx.workbook.getSelectedRange();
    rn.style = "Accent 1";

On a side note, it would be nice to query the list of available styles in the workbook, ie `Workbook.Styles` in VSTO.

**Comment by chewspot** [comment]
I have a few more questions/suggestions. Should I just tack them on  here? Or create new issues for each?

 - Excel.Range.group()
 - Excel.Range.insertIndent(indentLevel:number)
 - Excel.Table.resize(range:Range)

**Comment by Lauragra** [comment]
Please open a new issue for each as we'll treat them as separate requests; thanks!

**Comment by Lauragra** [comment]
I've logged a bug internally for this request. Thank you!
