### ISSUE TITLE
Excel.Table.resize()

### ISSUE THREAD

**Issue by chewspot** [OfficeDev/office-js-docs#383]
Would be nice if we can resize a table

The matching vsto interface would be:

    /**
     * The resize method allows a ListObject object to be resized over a new range
     * @param range
     */
    resize(range:Excel.Range):void;

At the moment, I'm working around this by 
  - converting the list object to a range, 
  - adding a new list object over the new range
  - set the new list object's name to the previous name

This kinda works, as it does not break any references to it. 
However, some formatting and styling settings are lost when done this way.

**Comment by Lauragra** [comment]
Logged this request internally as well - thanks for submitting!

**Comment by Hongbo-Miao** [comment]
The API design has been started.
