### ISSUE TITLE
Excel.Range.group()

### ISSUE THREAD

**Issue by chewspot** [OfficeDev/office-js-docs#384]
Would be nice if we could use `Range.Group()` again.

    let range:Excel.Range;
    range.getEntireRow().group();
    range.getEntireColumn().group();

![image](https://cloud.githubusercontent.com/assets/4828474/17538491/78b85fc8-5ed8-11e6-8bd8-7c53fd90b99e.png)

**Comment by Lauragra** [comment]
Got this one too. ;)

**Comment by hengchengfei** [comment]
When support?
