### ISSUE TITLE
OpenSpec-application-createDocument

### ISSUE THREAD

**Issue by jiaqing123** [OfficeDev/office-js-docs#385]
I was trying to create a new Word document using downloaded data using Office.js in Word Desktop for Windows. 

Before calling createDocument on context.application in Word.run(function (context) {}), I use 
Office.context.requirements.isSetSupported("WordApiDesktop", "1.3") to check whether the method is available or not. 

In the production environment, Office.context.requirements.isSetSupported("WordApiDesktop", "1.3") 
returns true. But context.application is undefined. 

The issue here is: either Office.context.requirements.isSetSupported("WordApiDesktop", "1.3") gives the wrong result, or context.application is not properly initialized.

Environment:
Operating System: Windows 10.
Application: Microsoft Word 2016 for Windows
Office.js: https://appsforoffice.microsoft.com/lib/1/hosted/office.js

**Comment by keyur32** [comment]
Hi @jiaqing123, sorry for the delay on this but you can use the stackoverflow question here for more info on how to fix this: http://stackoverflow.com/questions/40655463/context-application-is-undefined-when-using-wordapi-1-3.

I'd also recommend you wrap the call into a document.ready function to ensure Office.js has loaded.

hope that helps and let us know if you still see an issue.

**Comment by Hekuma** [comment]
I'm trying call createDocument as per the  documentation

function openWord() {

    	Word.run(function (context) {
    		var myNewDoc = context.application.createDocument(getDocumentAsBase64());
    		context.load(myNewDoc);

    		return context.sync()
				.then(function () {
					var myParagraph = myNewDoc.body.insertParagraph("Hello World This is a new Document!!!", "end");
					myParagraph.font.bold = true;
					myParagraph.font.name = "Courier new";

					myNewDoc.open();
					context.sync();
				}).catch(function (myError) {
					//otherwise we handle the exception here!
					showNotification("Error", myError.message);
				})

    	}).catch(function (myError) { showNotification("Error", myError.message); });
    }


But for me also I'm getting context.application undefined. I've registered button click inside document ready.

**Comment by Rick-Kirkham** [comment]
@Hekuma 
I'm not sure this will solve the issue, but your second "context.sync();" line needs to have "return" in front of it: "return context.sync()". Also,

**Comment by Hekuma** [comment]
I was able to resolve the issue. The issue was with wrong version of Office installed. Thanks @Rick-Kirkham for suggestion  though.

**Comment by sirifgagan** [comment]
Hi,

I am facing the same Issue. @Hekuma, Could you please share your exact build version. And also confirm if you are using the beta version of the office JS (https://appsforoffice.microsoft.com/lib/beta/hosted/office.js) or is it the production version (https://appsforoffice.microsoft.com/lib/1/hosted/office.js). Have you tried this API with Word Online?

**Comment by Hekuma** [comment]
Hi Sirifgagan, 
I'm using beta version of the Office JS. I've not tried with Word online.

**Comment by sirifgagan** [comment]
Please share your office build version. Thanks

**Comment by MikkoKoskinen** [comment]
I'm facing the same issue. If I use beta version of the office JS ([(https://appsforoffice.microsoft.com/lib/beta/hosted/office.js])  context.applicationis found and createDocument() is working.

But with production version ([https://appsforoffice.microsoft.com/lib/1/hosted/office.js]) I'm getting context.application undefined error.

I just updated my Office client and I tested this with Version 1705 (Build 8201.2136 Click-to-run)

**Comment by hengchengfei** [comment]
![1](https://user-images.githubusercontent.com/3182964/38455774-8b0b6378-3aaf-11e8-94f9-cea42a469bc5.jpeg)

Api 1.4 had added the createDocument method,but return type is  DocumentCreated Object rather than  Document Object.

**Comment by cindymeister** [comment]
It would help if LINKS were posted with pictures. I have no idea, for example, how to find the information in hengchenfei's comment!

**Comment by vmrathod** [comment]
Office.API document says return type of  "createDocument" is "Document" but I am getting return object "DocumentCreated". 
Is there any changes or update?
