### ISSUE TITLE
Incorrect / incomplete info topic BreakType (Enum)

### ISSUE THREAD

**Issue by cindymeister** [OfficeDev/office-js-docs#39]
This page: https://github.com/OfficeDev/office-js-docs/blob/master/word/word-add-ins-javascript-reference/breaktype.md
1. The last three entries (section break types) "String" is in the second column instead of a description about what it does
2. The second and third entries for the "Line" type (ClearLeft and ClearRight) the explanation is incomplete - it doesn't really say how they differ from one another or the first. And since these are not options in the Word Object model we can't look it up there, either.

**Comment by lindalu-MSFT** [comment]
Fixed broken table and merged. Content updated.
