### ISSUE TITLE
Outlook JS API?

### ISSUE THREAD

**Issue by giorgio79** [OfficeDev/office-js-docs#40]
Any plans for Outlook JS API like Word and Excel?

I would love to enable my adding for Outlook messages as well in addition to Word.

**Comment by MIchaelMainer** [comment]
Hello @giorgio79 - I'm unaware of any plans for such an API.

**Comment by MIchaelMainer** [comment]
Just to clarify, you can use OfficeJS to work on Outlook messages. There isn't an Outlook API model like the one you see for Word and Excel. 

https://msdn.microsoft.com/EN-US/library/office/fp161135.aspx
