### ISSUE TITLE
Can't "side-load" Add-In for Powerpoint on MacOS

### ISSUE THREAD

**Issue by krebbl** [OfficeDev/office-js-docs#403]
I created a custom Add-In and wanted to "side-load" it. So I copied the manifest.xml to `/Users/<username>/Library/Containers/com.microsoft.Powerpoint/Data/documents/wef`. (described like [here](http://dev.office.com/docs/add-ins/testing/sideload-an-office-add-in-on-ipad-and-mac)). But the Add-In doesn't show up in the Add-In list. 
I am using Powerpoint 15.24
Any help?

**Update**: I figured out when I use a manifest for a "TaskPaneApp" the Add-In is shown. For type "ContentApp" it isn't.

**Comment by mlafleur** [comment]
Side-loaded add-ins won't show up within the normal add-in dialog. You'll notice that the button for inserting add-ins is a drop-down button. Does your add-in show up in that drop down list?

**Comment by krebbl** [comment]
yes, when I set the manifest to type TaskPaneApp the addin shows up in the dropdown list under "developer" but when I set the type to ContentApp it doesnt. 

Can you send me a working manifest for a ContentApp?

**Comment by krebbl** [comment]
Ok, I found a working solution. The problem was the manifest XML namespace version. Seems like Powerpoint for MacOS only supports version 1.1 for ContentApps.

So when trying to sideload a ContentApp use [this manifest](https://github.com/OfficeDev/Excel-Add-in-JavaScript-CommunicationBetweenAddIns/blob/master/CommunicationBetweenAddInsContent/CommunicationBetweenAddInsContentManifest/CommunicationBetweenAddInsContent.xml) as base.
