### ISSUE TITLE
Can a Storage Plugin be written ?

### ISSUE THREAD

**Issue by matthiasg** [OfficeDev/office-js-docs#41]
Where can i find information about writing a storage plugin, similar to google drive ?

![image](https://cloud.githubusercontent.com/assets/231889/11163533/b25c8dfa-8ad3-11e5-97ea-98f78cfbd7c9.png)

**Comment by MIchaelMainer** [comment]
@matthiasg I'm sorry about the tardy reply. I don't know the answer to this but do have a question out to learn what the story is for a storage plugin.

**Comment by matthiasg** [comment]
@michaelmainer thanks for following up. Our customers would love to integrate the office save dialogs into our system. They can directly edit and save already but creating new documents is always easier with a clear icon . WebDAV is not really intuitive for users.

**Comment by MIchaelMainer** [comment]
@matthiasg I don't have any specific guidance on how you might this do this. I'm not familiar with this area but here is where I'd start to look into this. 

[Office Primary Interop Assemblies](https://msdn.microsoft.com/en-us/library/15s06t57.aspx)
[Word Object Model Overview](https://msdn.microsoft.com/en-us/library/kw65a0we.aspx)
https://msdn.microsoft.com/en-us/library/microsoft.office.interop.word.application.aspx
[How to call web Service in Excel Using VSTO](https://code.msdn.microsoft.com/How-to-call-web-Service-in-3e082197/view/SourceCode#content)

I'm hoping this leads you in the right direction. With regards, Michael
