### ISSUE TITLE
Incorrect Hosts documentation for OfficeApp element

### ISSUE THREAD

**Issue by Thiez** [OfficeDev/office-js-docs#412]
The officeapp.md file links to hosts.md, but this is not the correct documentation. It appears there are two types of `<Hosts>` elements, the one under `<OfficeApp>`, and the one under `<VersionOverrides>`. The former has children that look like `<Host Name="Document"/>`, while the latter has children that look like `<Host xsi:type="Document"><!-- many child elements here --></Host>`. The first type appears to be undocumented, and officeapp.md incorrectly links to the documentation for the second type of `<Hosts>` element.

**Comment by mlafleur** [comment]
Excellent catch, thank you.

**Comment by Thiez** [comment]
My pleasure, thank you for the quick fix!
