### ISSUE TITLE
ContentControl's method load() does not work in Word Online

### ISSUE THREAD

**Issue by ArtemZinenko** [OfficeDev/office-js-docs#415]
I have tried to execute code in word online:

```
            Word.run(function (context) {
                var contentControls = context.document.contentControls;
                context.load(contentControls, 'text');
                return context.sync().then(function () {
                    console.log(contentControls.items.length);
                });
            }).catch(function (error) {
                console.log(error);
            });
```

And got an error:
`TypeError: contentControls.items is undefined`

In Desktop Word it works well.

P.S. Same error was thrown by all code examples from http://dev.office.com/reference/add-ins/word/contentcontrol

**Comment by mlafleur** [comment]
Hello,

WordAPI is currently only supported with Word for Windows 2016, Word for iPad and Word for Mac 2016. It is unsupported on Word Online at the moment. 

For a list of which APIs are available on which platforms, please see [Office Add-in host and platform availability](http://dev.office.com/add-in-availability)

**Comment by weshi** [comment]
WordApi 1.1 & 1.2 are in preview mode in Word Online. If you run below code in Word Online, you can run below sample code to test. It will show you the number of content controls and the text of the first content control. Please note that we currently only support Rich Text Content Control whose placeholder text is default.

Word.run(function (context) {
  var contentControls = context.document.contentControls;
  context.load(contentControls, "text");
  return context.sync().then(function() {
    console.log("Total content controls: " + contentControls.items.length);
    if (contentControls.items.length>0) {
      console.log("First content control text: " + contentControls.items[0].text);
    }
  });
})
.catch(function(error) {
  console.log("Error: " + JSON.stringify(error));
  if (error instanceof OfficeExtension.Error) {
    console.log("Debug info: " + JSON.stringify(error.debugInfo));
  }
});

**Comment by weshi** [comment]
The Word 1.1 & 1.2 APIs are GA now. You can test the Rich Text Content Controls in Word Online now.

**Comment by ArtemZinenko** [comment]
@weshi, Thanks I got it

**Comment by ArtemZinenko** [comment]
I found a bug in the Word Online which concerns this issue.
The contents of the document, which was created in the Word Desktop and opened for editing in Word Online can not be cleaned (If there is a content control in the document). There is no possibility to do this manually or by using api.
[Combo box content control.docx.zip](https://github.com/OfficeDev/office-js-docs/files/597767/Combo.box.content.control.docx.zip)

**Comment by weshi** [comment]
Only Rich Text Content Control created with the APIs are supported in Word Online. Combo box content control is not supported in Word Online.

**Comment by ArtemZinenko** [comment]
I got it. Thanks
