### ISSUE TITLE
Office js 1.1 / Beta - PDF stream in MAC word - throw error - "Internal error"

### ISSUE THREAD

**Issue by VimalKumarS** [OfficeDev/office-js-docs#421]
Office js 1.1v to have the capability of get file async as PDF on Mac word.
The mac version 15.24 (160709) and the office js version 1.1 and beta , throw error "Internal error" on mac word, when try to read the PDF stream.

thanks
Vimal

**Comment by kbrandl** [comment]
Apologies for the delayed response. This issue has been fixed; please try again and re-open this issue if you still have trouble.
