### ISSUE TITLE
Outlook.com sandboxing (No "allow-popups-to-escape-sandboxing" flag?)

### ISSUE THREAD

**Issue by rubenanton90** [OfficeDev/office-js-docs#423]
Hi, don't really know if this is the correct place to comment on this issue, but it's the closest thing I found.

As per documentation, in outlook.com Office-js runs its add-ins in an HTML5 Sandboxed iframe, which cannot execute modal windows such as the ones generated by window.confirm() by not using the allow-modals sandbox flag. This is completely logical, expected behavior.

However, these permissions are inherited to new tabs opened by the add-in, which means any new window opened through the add-in (For example, a simple link to another page, a support page, or the homepage of an ad clicked by the user) cannot open modals, or will otherwise behave unexpectedly! For example, in our outlook add-in, when the user wants to visit the home page of our app by clicking on a link in the add-in, the home page will not work properly, without the user having any clue of why this is happening.

Both Chrome 46+ and the upcoming Firefox 49 immediately added the "allow-popups-to-escape-sandbox" flag when they added the modals restriction to prevent this situation from happening. However, as of today, Outlook.com does not have the "allow-popups-to-escape-sandbox" flag in its add-in iframe. 

I don't believe this is a security feature, since the allow-popups-to-escape-sandbox flag was conceived exactly for this sort of situation where the user willingly opens a link from a sandboxed page (It cannot be used to bypass sandbox security and open unwanted modals, since in modern browsers window.open will only work through direct user agent interaction, or Trusted Events).

Looks like a thing that can cause massive issues in very common use cases for an add-in (An advertisement within the add-in, any sort of link to another page, etc), and would have a very easy fix. In our case, it's causing our application to become unstable in Chrome, and will cause it to fail in the same way in the foreseeable future for Firefox.

**Comment by jasonjoh** [comment]
Thanks for the feedback @rubenanton90! To answer your first question, you're right, this isn't really the correct place to leave feedback or suggest changes to the API/framework. We try to limit the issues in this repository to issues with the documentation itself. For feedback on the product/API, go to https://officespdev.uservoice.com/.

However for this particular issue, I chatted with our add-in engineering team and this is something they were already investigating adding! I can't promise anything at this point, but they are aware of the new flag and the issues you're reporting, and it's being considered.

**Comment by rubenanton90** [comment]
@jasonjoh Hi. As we expected, Firefox has implemented this behavior, as well as the "allow-popups-to-escape-sandbox", thus also breaking our add-in in Firefox. Has the add-in engineering team decided on something about this issue? 

Thanks for your time!
