### ISSUE TITLE
The dropdowns on MSDN don't seem to work as intended

### ISSUE THREAD

**Issue by GabRoyer** [OfficeDev/office-js-docs#44]
The dropdown on every headings on MSDN (e.g. "Properties" on https://msdn.microsoft.com/EN-US/library/office/mt598672.aspx) don't do anything. Collapsing them doesn't hide anything which makes me think the hierarchy between the headings and the content isn't properly set up.

**Comment by MIchaelMainer** [comment]
Thank you @GabRoyer. I'll open an issue on the GH to MSDN publishing pipeline.
