### ISSUE TITLE
Typescript and RxJS

### ISSUE THREAD

**Issue by sumigoma** [OfficeDev/office-js-docs#45]
These two Microsoft technologies are already used heavily in Angular2, which we are currently designing around, and we would love to have support for them in this API as well.

**Comment by MIchaelMainer** [comment]
@sumigoma Thank you for the feedback. TypeScript and Angular2 are both on our radar. Are you requesting code snippets and samples that use TypeScript, Angular2, and RxJS?

**Comment by sumigoma** [comment]
That would be great! Ideally, it would be nice to have this library as a package on npm, so we could add it as a dependency and integrate it into our app with intellisense support, etc.

**Comment by htryggva** [comment]
+1

**Comment by MIchaelMainer** [comment]
Thank you for that feedback too. I'll make sure I pass it along.

**Comment by sumigoma** [comment]
Hi @MichaelMainer, has there been any development on this issue?

**Comment by WrathOfZombies** [comment]
We are currently in the process of developing a sample showcasing Angular 2, TypeScript and RxJS. 
Considering Angular 2 just went RC 1.0 we will have some updates for you soon.

**Comment by sumigoma** [comment]
Does this mean the OfficeJS API will have typescript type definitions in typings (https://github.com/typings/typings)? Was typescript applied throughout the entire project?

And for RxJS support, are you just wrapping the promises in Rx.Observable.from()?

Looking forward to the updates.

**Comment by WrathOfZombies** [comment]
OfficeJS API does have definitions in typings. You can get it by using `typings install dt~office-js --global --save`. Also regarding the RxJS Support, current we are wrapping using the native promises as is but you can definitely wrap them into an Observable. Although the wrapper we considered was to create a new Observerable manually and not just use `.from()`

**Comment by Lauragra** [comment]
It looks like this issue has been resolved so closing for now. Feel free to reopen if you have additional questions. Thanks.
