### ISSUE TITLE
Missing code examples manipulating multiple Word elements

### ISSUE THREAD

**Issue by alexkieling** [OfficeDev/office-js-docs#48]
All code examples showing how to read/write data from content controls manipulate only the first element of the list. Please provide examples manipulating multiple elements. For example: get all content controls HTML, insert HTML into a group of content controls, etc.

**Comment by MIchaelMainer** [comment]
@alexkieling Thank you for your feedback. The [Word-Add-in-SillyStories](https://github.com/OfficeDev/Word-Add-in-SillyStories) sample shows how to manipulate all of the content controls in the document. We have links to this sample in the documentation. If you didn't find these links, then I need to make them more discoverable. There are links in the contentControl and contentControlCollection topics. I hope this helps.
