### ISSUE TITLE
Office.css unclear

### ISSUE THREAD

**Issue by handylearn** [OfficeDev/office-js-docs#50]
The html file references a file "Office.css", but later there is only code for Common.css. Is Office.css something predefined, or was it just forgotten in the description?

File: build-your-first-excel-add-in.md

**Comment by umasubra** [comment]
Office.css is available with the Visual Studio Office add-ins template and defines custom styling. We found it useful to include it in our Code Editor projects as well. You can just copy it from the code sample and use it in your code.

**Comment by handylearn** [comment]
Thanks you for the help. This helps me. 

This text still does not mention office.css. The text is supposed to be a tutorial. 
So for me, this is a still open bug: 
If you follow the tutorial step by step, your html does not render correctly because of the missing reference. 
The title of the text is "Build your first Excel add-in" so the reader is expecting that everything is a least mentioned in the text. I have reported the bug so that the quality of the text gets improved for all future readers.
