### ISSUE TITLE
Editing a Excel cell while loading taskpane app causes a error (5004)

### ISSUE THREAD

**Issue by SivalenSivalingam** [OfficeDev/office-js-docs#534]
Hi

I am currently experiencing a error, when I edit a cell while the excel task pane app loads. It returns a 5004 error code, which is "Invalid API call in the current context". 

I manage to replicate this bug with the following code using the API Tutorial (Taskpane) app:

function displayAllBindingNames() {
    Office.context.document.bindings.getAllAsync(function (asyncResult) {
		if (asyncResult.status !== Office.AsyncResultStatus.Succeeded) {	
			console.log('failed!');
		}
        });
}

var interval = setInterval(displayAllBindingNames, 500);
setTimeout(function() {
	clearInterval(interval);
}, 3000);

I need some help please, to find a solution to this bug.

**Comment by Lauragra** [comment]
Hi Silvalen, thanks for contacting us. This repo is primarily for issues with the documentation. For support for your code, we recommend that you post your issue on StackOverflow for a faster response. If we can assist with documentation, please feel free to reopen. Thanks!
