### ISSUE TITLE
When will command add-ins be available through sharepoint?

### ISSUE THREAD

**Issue by Thiez** [OfficeDev/office-js-docs#541]
[This page](https://github.com/OfficeDev/office-js-docs/blob/a313465e5c7abe750bee35765fbebf4c7f6727c5/docs/publish/publish.md) mentions that command extensions are not available through sharepoint catalogs. When will sharepoint catalogs support this feature? If this limitation is intentional, why is it there? I find it very surprising that the exact same xml works when loaded from a shared folder, but not from sharepoint. It looks like Office is discriminating for no good reason. If there is a good reason, perhaps it should be added to the page I linked to.

**Comment by PhilSmail** [comment]
Thiez, There currently is no support for Add-In Commands for Add-Ins uploaded to the SharePoint Add-In Catalog. Our future direction re deploying Add-Ins is via the Centralized Deployment feature: https://support.office.com/article/Deploy-Office-Add-ins-in-the-Office-365-new-Admin-Center-737e8c86-be63-44d7-bf02-492fa7cd9c3f

However we appreciate the feedback re SharePoint Add-In Catalog and will factor this into planning in the future.

Thanks
Phil Smail
Microsoft
