### ISSUE TITLE
Is there any way to consume Excel/word REST APIs outside add-ins?

### ISSUE THREAD

**Issue by sanjaybhagia** [OfficeDev/office-js-docs#543]
Is it possible to consume workbook REST API without add-in? I want to consume excel apis in azure functions where i don't have Excel Context as in add-in. I can do it using REST calls but was wondering if i can use the sdk as one can while creating the add-ins?

Thanks

**Comment by mlafleur** [comment]
Office.js is used to extended Office applications (Word, Excel, Outlook, etc.), it cannot be used outside of that context. 

Depending on what functionality you are looking for, you may be able to use the Excel APIs available in [Microsoft Graph](https://graph.microsoft.io/en-us/docs/api-reference/v1.0/resources/excel). These APIs allow you programmatically work with Excel files.

**Comment by sanjaybhagia** [comment]
Thanks Marc,

Yes im using the graph API at the moment.
