### ISSUE TITLE
Office.context.mailbox.item.saveAsync crashes addin and closes dialog (New Appointment, OWA)

### ISSUE THREAD

**Issue by figgsoftware** [OfficeDev/office-js-docs#547]
In the web version of Outlook:
Office.context.mailbox.item.saveAsync(function (result) {
                       app.showNotification(result.value);
        });
Is not returning the itemid anymore, but rather some strange string (ex: CLCID:M9_1473129000000_1473130800000__Busy_false_false) and then the whole addin and appointment dialog is closing. Seems to be a bug introduced by a OWA update? Works fine in the Outlook desktop version.

**Comment by mlafleur** [comment]
Just to clarify, is it saving and then failing to return the Id or is it failing to save entirely?

**Comment by figgsoftware** [comment]
It looks like the save is going through before the appointment dialog window just closes.

**Comment by rbarten** [comment]
Same issue here! Any news on this issue?

**Comment by figgsoftware** [comment]
This seems to have been fixed now
