### ISSUE TITLE
DocumentProperties_OpenSpec

### ISSUE THREAD

**Issue by AhmedVali** [OfficeDev/office-js-docs#562]
Hi,
I am relatively new to Office 365 and I am exploring the ways to set/get properties(custom properties also). With the new Word JS API 1.3, I heard it is possible and I found the beta office.js (https://appsforoffice.microsoft.com/lib/beta/hosted/office.js). Is adding this JS file  enough in the html pages to get the new features. I did so, but Visual Studio intellisense doesn't recognize it and also I am unable to retrieve the properties using the below code

Excel.run(function (ctx) { 
    var properties = ctx.workbook.properties;
    properties.load('author');
    return ctx.sync().then(function() {
        console.log(properties.author);
    });

Do i have to include any other settings  ? Also will this work for Word??

I am testing on office 2016 and office online

Thanks,

**Comment by sumurthy** [comment]
Hi Ahmed, 

Few things: 
1. the document properties API in JavaScript are not available yet. It is under testing at the moment. Your code looks right.. we just need this exposed under beta endpoint. 
2. As part of publishing, we'll update the typescript definition and VSDOC files. This will allow you to see the intellisense. 
3. Timing wise - We are probably 3-4 weeks away from publishing this for Win32 clients. 
4. Custom properties can be modified/accessed through [custom-xml](https://github.com/officedev/office-js-docs/tree/CustomXMLParts_OpenSpec). This part is still in design and we hope to publish beta API in the coming months.
