### ISSUE TITLE
Will RangeView object work on a table to show only the filtered rows?

### ISSUE THREAD

**Issue by jbarr33** [OfficeDev/office-js-docs#579]
I'm interested in getting the just the filtered rows of a table with all the same properties returned by  table.getRange(). I want the user to be able to filter a table, capture the filtered data, then have the user filter again and capture the new filtered data. If this is not planned please consider it.

Also, is there an approximate time frame for 1.3 release?

Thanks,
Jim

**Comment by sudhiseattle** [comment]
Hello, 

Range view  can be accessed by getting the underlying range object using tableObj.getRange().
The Excel 1.3  is available on beta as of yesterday. You can point to https://appsforoffice-edog.microsoft.com/lib/1/hosted/office.js to get the latest. 

Please check the docs here: 
https://github.com/OfficeDev/office-js-docs/tree/ExcelJs_1.3_OpenSpec

We'll promote this to GA in the coming weeks. 

Thanks

**Comment by jbarr33** [comment]
Thanks for the reply.  Just tried it out and it works great. Look forward to the release.

Jim
