### ISSUE TITLE
Problem with different types of runtime environments (Word Desktop & Word Online)

### ISSUE THREAD

**Issue by ArtemZinenko** [OfficeDev/office-js-docs#583]
I'm trying to get the Ooxml of the document (I am interested in the header, body and footer).
I use the following code to this:
```
Word.run(function (context) {
    var body = context.document.body.getOoxml();
    return context.sync().then(function () {
        console.log(body.value);
    });
}).catch(function (error) {
    console.log(error);
});
```

The problem is that the result is different depending on the runtime environment. Desktop version returns the headers, body and footers but the online version returns only the body.
Is It possible to solve this problem?

[BugSample.docx.zip](https://github.com/OfficeDev/office-js-docs/files/566403/BugSample.docx.zip)

![word desktop](https://cloud.githubusercontent.com/assets/18261451/19927083/d75e9c08-a100-11e6-8bba-d75de4c64e5a.png)
[Word Desktop.xml.txt](https://github.com/OfficeDev/office-js-docs/files/566390/Word.Desktop.xml.txt)

![word online](https://cloud.githubusercontent.com/assets/18261451/19927105/f9d1ffb4-a100-11e6-88f4-8940c63298ef.png)
[Word Online.xml.txt](https://github.com/OfficeDev/office-js-docs/files/566386/Word.Online.xml.txt)

**Comment by mlafleur** [comment]
The code sample you provided _should_ only return the body of the document. Based on what you're reporting, it sounds like you're seeing much more than the body on the desktop. 

Which desktop version of Word are you seeing this result (2013/2016? Mac/Windows?)?

**Comment by ArtemZinenko** [comment]
I saw this result on the MS Word 2016 (Version 1609 (Build 7369.2038)).
If I have understood you right, there is no ability to get all document (with all sections, headers and footers), is it?

**Comment by mlafleur** [comment]
You can retrieve the entire document as OOXML using (document.getFileAsync())[https://dev.office.com/reference/add-ins/shared/document.getfileasync]. This sounds like what you're looking for.

**Comment by ArtemZinenko** [comment]
I found a bug in the Word Online which concerns this issue.
The contents of the document, which was created in the Word Desktop and opened for editing in Word Online can not be cleaned (If there is a content control in the document). There is no possibility to do this manually or by using api.
[Combo box content control.docx.zip](https://github.com/OfficeDev/office-js-docs/files/597698/Combo.box.content.control.docx.zip)

**Comment by nokafor** [comment]
It seems that this issue is resolved, so I am going to close it. Please reopen if more help is needed!
