### ISSUE TITLE
Office Initialize is not initializing in outlook 2013 windows native client

### ISSUE THREAD

**Issue by hentry** [OfficeDev/office-js-docs#585]
Office initialize is not initializing in outlook 2013 but it is intializing properly in rest of the clients(Mac, OWA). Following is the code snippet I used to initialize the office context.

Office.initialize = function() {
   console.log(Office.context.mailbox.item.attachments);
}

My webapp is implemented in angular js(1.3.14). Is anything wrong from my side or is this an issue in office js?

**Comment by mlafleur** [comment]
That looks fine to me. Could you provide the path for Office.js that you are use? 

Also, make sure Outlook 2013 is fully updated. There have a been a lot of additions to the platform since it was released back in 2012.  I've seen a number of cases where malfunctioning add-ins could be traced back to unpatched versions of Office.

**Comment by hentry** [comment]
Hi @mlafleur,
Thanks for replying. This is the script, I am using to download the office js.

`<script src="https://appsforoffice.microsoft.com/lib/1/hosted/Office.js" type="text/javascript"></script>`

Also, My office 2013 client version is **2013(15.0.4569.1503) MSO (15.0.4569.1506) 64 bit**

**Comment by mlafleur** [comment]
You're version of Office is seriously out of date. That build was released in March 2014. Please make sure your copy is fully patched. See [Update history for Office 2013](https://support.office.com/en-us/article/Update-history-for-Office-2013-19214f38-85b7-4734-b2f8-a6a598bb0117?ui=en-US&rs=en-US&ad=US&fromAR=1) for more details.

**Comment by hentry** [comment]
Hi @mlafleur,
Thanks for the update. After updating my office windows client to 2013 latest build, its working.
