### ISSUE TITLE
Header Content Controls

### ISSUE THREAD

**Issue by mberacochea** [OfficeDev/office-js-docs#586]
I'm trying to obtain the content controls of the header but I can't get them:

```js
function getContenControlHeader(tag) {

        // Run a batch operation against the Word object model.
        Word.run(function (context) {

            // Create a proxy sectionsCollection object.
            var mySections = context.document.sections;

            // Queue a commmand to load the sections.
            context.load(mySections, 'body/style');

            return context.sync().then(function () {

                var myHeader = mySections.items[0].getHeader('primary');
                return context.sync().then(function () {

                    var contentControl = myHeader.contentControls.getByTag(tag);

                    // Queue a command to load the text property for a content control.
                    context.load(contentControl, 'text');

                    // Synchronize the document state by executing the queued commands, and return a promise to indicate task completion.
                    return context.sync().then(function () {
                            console.log(contentControl.items[0].text);
                    });
                });
            });
        });
    }
```

This snippet does not work.

**Comment by douglasware** [comment]
Any update on this serious bug? I can confirm loading content controls from the header or footer yields no results and throws no errors in 1.3.

**Comment by Rick-Kirkham** [comment]
@mberacochea 
We use the GitHub issues for this repo to raise issues with the documentation. For your bug, please ask a question on stackoverflow and tag the question with "office-js"

**Comment by mberacochea** [comment]
@Rick-Kirkham
OK I will ask it on stackoverflow. 
But if it is a bug where can I report this? 

Thanks

**Comment by douglasware** [comment]
I was able to do it. The key is that they must be rtf content controls. Plain text isn't supported for whatever reason.

**Comment by Rick-Kirkham** [comment]
@mberacochea There is no public place where you can report a bug. If you create a question on StackOverflow, and the community cannot solve it, a MS employee will take a look and create a bug internally as needed.
@douglasware When @mberacochea creates his question on StackOverflow, please respond with your discovery.

**Comment by mberacochea** [comment]
Ok, thanks!
