### ISSUE TITLE
ExcelJs-1.2-OpenSpec-range-autofit

### ISSUE THREAD

**Issue by ShaunLoganOracle** [OfficeDev/office-js-docs#59]
The page [here](https://github.com/OfficeDev/office-js-docs/tree/ExcelJs_1.2_OpenSpec/excel
) with new Excel 1.2 features list has an entry: "Row Height, Column Width and Autofit".  The link on that item seems to be incorrect, it reads: https://github.com/OfficeDev/office-js-docs/blob/ExcelJs_1.2_OpenSpec/excel/resources/range.md#mergeacross-boolean

Note the "mergeacross-boolean".

I could not find any doc on "Row Height, Column Width and Autofit" in the Range or Worksheet doc.

**Comment by sumurthy** [comment]
Hi Shaun, I fixed the link for merge API. 

the row/col height and width are properties of the Range object. You can directly set the values. 
Also, you can use autofit API available on the Range object.
