### ISSUE TITLE
shape-name

### ISSUE THREAD

**Issue by IRRDC** [OfficeDev/office-js-docs#594]
It would be very useful to have a shape-master-name property, too, to search for all shapes based on the same master.

**Comment by keyur32** [comment]
Hi @IRRDC, currently we don't have any Javascript API support for names, but you can get at them through Office Open XML in the  Word API.

Can you help me understand the specific ask and the scenario you're trying to accomplish? We can then put the issue in our backlog in uservoice to help us prioritize this request.

**Comment by IRRDC** [comment]
Hi @keyur32,
there are many use cases especially when displaying drawings of process diagrams starting with filtering all process elements by type, knowing when the user selected an e.g. decision shape and reacting differently to that than to the selection of an e.g. sub-process shape.
Without easy access to a shape's master name the next best way to handle such things would be for us solution developers to add an identifying shape data property to each master shape. This has the huge drawback that we have to work with custom stencils and cannot use any build-in Visio shapes.

**Comment by IRRDC** [comment]
I'm not sure if it was clear from my initial post that this issue concerns the Visio shapes. I created the issue by following a feedback link on the shape-name documentation page but that just seems to have set the issue's title and not created a relationship to the documentation page I was reading (https://github.com/OfficeDev/office-js-docs/blob/VisioJs_1.1_Openspec/reference/visio/shape.md).

**Comment by rahul-mi** [comment]
Thanks for your feedback.
We understand that having Shape.MasterName property would be useful for your scenario.
And we will plan to include it in the continuous improvements post the first version of the APIs.
