### ISSUE TITLE
displayReplyAllForm is not working in mac native app

### ISSUE THREAD

**Issue by hentry** [OfficeDev/office-js-docs#596]
Hi,
The displayReplyForm method is not working in mac native client. Following is the code I used to trigger the form,

`Office.context.mailbox.item.displayReplyAllForm({'htmlBody' : 'Attachment attached', 'callback' :function(response) {
console.log('working');
}});`

It's working in all other clients like 'OWA', windows native client 2016, 2013. 

My mac native client version is - 15.27 (161010)

Is this a bug in office JS??

Thanks,
Hentry.

**Comment by Lauragra** [comment]
Hi Hentry, thanks for reaching out. This repo is primarily for feedback on the documentation. For support for your code, please post your issue to StackOverflow and tag with [[office-js]](http://stackoverflow.com/questions/tagged/office-js). If you have suggestions for how we can improve our documentation, please feel free to reopen.
