### ISSUE TITLE
WorksheetCollection.getItemOrNull() throws error

### ISSUE THREAD

**Issue by jozefizso** [OfficeDev/office-js-docs#597]
Calling `WorksheetCollection.getItemOrNull()` method in Office.js Excel 1.2 API throws error "Object doesn't support property or method 'getItemOrNull'."

Expected behavior: Excel 2016 (Windows Desktop) supports calling WorksheetCollection.getItemOrNull() as documented.

**Comment by sumurthy** [comment]
Please check the version of Excel you are using. This requires requirement set #1.3 or higher. 

https://github.com/OfficeDev/office-js-docs/blob/master/reference/requirement-sets/excel-api-requirement-sets.md
