### ISSUE TITLE
report a possible bug: Word Online does not fully support office.js v1.1

### ISSUE THREAD

**Issue by he-yang** [OfficeDev/office-js-docs#60]
I am testing my add-in on different platforms

my add-in contains the following code to do runtime checks in my JavaScript code

`if (Office.context.requirements.isSetSupported("WordApi", 1.1)
{
   // Code 
}`

my test shows that the above if statement receives a TRUE in Word Online, meaning Word Online fully supports office.js version 1.1 , which i don't believe is true.

my add-in also contains the following code

`var searchResults = context.document.body.search('to*n', {matchWildCards: true});`

this code works perfectly in Office 2016, but does not in  Word Online, this code can only get me an error like this :`{"name":"OfficeExtension.Error","code":"GeneralException","me
ssage":"This browser does not support the requested
API.","traceMessages":[],"debugInfo":{},"stack":"GeneralExcepti
on: This browser does not support the requested API.\n at
Anonymous function `

I went to check Word online, and i found Word Online does not support WildCards search as Office 2016, so I guess maybe this is the reason why I got the above error message.

Is there a way to detemine wherther this code is running in Word 2016 or Word Online, so that I could let my code fail in Word Online

source code of my add-in can be found in my repository "text-effect-autocorrection"

**Comment by MIchaelMainer** [comment]
@he-yang I've been told that you can get the host information (Word 2016, Word Online, Word 2016 for Mac) from the query string that is sent by the add-in. I haven't tried this yet so I can't give you instructions on how to do this, at this time.

**Comment by he-yang** [comment]
here are several examples I obtained

_host_Info=Word|Win32|16.01|en-US
_host_Info=Word|Win32|16.00|zh-CN
_host_Info=Word|Web|16.00|EN-US|22820280-3514-2dda-64b8-17beadb6f11a
_host_Info=Word|Win32|16.00|zh-CN
_host_Info=Word|Web|16.00|EN-US|2e780e70-3518-506f-c303-9f275bdde344
_host_Info=Word|Web|16.00|ZH-CN|4817ab3f-2518-43ab-cc93-74435545c043

I guess the Win32/Web can tell me about platform

**Comment by MIchaelMainer** [comment]
Yes, the Word|**Web**|16.00|ZH-CN part of the host_info is what you'll want to detect to determine whether the add-in is running in Word Online
