### ISSUE TITLE
Excel Range.select() throws error

### ISSUE THREAD

**Issue by jozefizso** [OfficeDev/office-js-docs#605]
This code throws error on Excel 2016 (Microsoft Excel 2016 MSO (16.0.4266.1003) 32-bit):

```
Excel.run((ctx) => {
  var sheet = ctx.workbook.worksheets.getActiveWorksheet();
  var range = sheet.getUsedRange();

  return ctx.sync().then(() => {
    range.select();
    return ctx.sync().then(() => {
        ...
    });
  });
}).catch((error) => {
  console.log(JSON.stringify(error.debugInfo));
});
```

Error: ```{ "errorLocation": "Range.select" }```

Expected behavior: Excel will select the range represented by `range` object.

**Comment by Lauragra** [comment]
Hi, this repo is primarily for feedback on the documentation. For help with your code, we recommend that you post your question to StackOverflow and tag with [office-js]. Closing this issue for now but feel free to reopen if we can help clarify the documentation. Thanks.
