### ISSUE TITLE
Visio-documentView-disableHyperlinks

### ISSUE THREAD

**Issue by JohnGoldsmith** [OfficeDev/office-js-docs#608]
Does this remove the hyperlink icon or prevent any hyperlinks from working at all?  I can imagine scenarios where the icon is not required / wanted but link functionality should otherwise work as normal.

**Comment by rahul-mi** [comment]
Thanks for your feedback. 'DisableHyperlinks' will remove the hyperlink itself. 
We understand the need to not show the icons for some diagrams. We are planning to have a switch in UI to show/hide the icons. At the time, we will add similar thing in API as well.

**Comment by thorild** [comment]
Hi, any news on this? @rahul-mi  I have a customer who really would like the icon to go away and we would love to see an option for this in the API. Additionally when using a macro enabled visio we would need an option in the API to remove the yellow warning at the very top

**Comment by rahul-mi** [comment]
Hi @thorild, the option to hide the icons in the UI and API is in our backlog but is not planned for near visible future. If it is really a must for the customer, can I suggest that the customer raises a hotfix request for this?
Regarding hiding of warnings through API, we have noted your feedback and would plan to work on it in upcoming months.

**Comment by thorild** [comment]
Thanks for that and for the quick response @rahul-mi! Yes it seems to be a must have - can they request the hotfix via the O365 Admin portal or what should they do?
