### ISSUE TITLE
Merge Cells in Excel??

### ISSUE THREAD

**Issue by bedwar2** [OfficeDev/office-js-docs#61]
Is this possible maybe with the RangeFormat?   Been trying to figure out, need to convert an old VBA application and can't tell if merging cells is supported or not.

**Comment by sumurthy** [comment]
Hi, 
Merge Cell is supported with the new API that is in beta trial now. 
https://github.com/OfficeDev/office-js-docs/blob/ExcelJs_1.2_OpenSpec/excel/resources/range.md#mergeacross-bool

You'll need Excel online or Excel 2016 latest build (desktop) to achieve this.

**Comment by bedwar2** [comment]
Thank you sumurthy.   Very excited that this API keeps getting further developed!
