### ISSUE TITLE
range.getVisibleView() hangs for ranges that are too large; should abort and return Col an Row counts like .getRange()

### ISSUE THREAD

**Issue by jbarr33** [OfficeDev/office-js-docs#610]
The code below just hangs when the range is too large (for example the entire sheet) since getVisibleView() seems to want to return the range anyway.  It should work like the getRange() method in that if the range is too large it doesn't hang but still returns the columnCount and rowCount properties to let you know that the range is too large. This helps alot with validation/error handling. 

If the getVisibleView() just hangs without checking for too large a range (and returning col and row counts) then devs have to first validate the range with ctx.sync() and then make another call for the visibleRange() with ctx.sycn(). If getVisibleView() does check for too large a range and return col/row counts, then existing validation code will just work.  Either way, it probably shouldn't hang.

Excel.run((ctx: Excel.RequestContext) =>
{
  var range = ctx.workbook.worksheets.getItem(sheet).getRange(addr);
  var rangeVis = excelRange.getVisibleView().load(["values", "columnCount", "rowCount"]);
            return ctx.sync().then(() =>
            {
...

Thanks,
Jim

**Comment by sumurthy** [comment]
Bug 1340772
