### ISSUE TITLE
Setting cellFormat for entire row crashes with "internal error" in Excel Online; Excel client is OK

### ISSUE THREAD

**Issue by jbarr33** [OfficeDev/office-js-docs#618]
Don't know if it's just the alignVertical format but probably not.

{ cells: { rows: 14 }, format: { alignVertical: "top"} },

Setting format for an entire column seems to work OK.

If there is an Excel Online limitation maybe docs could mention it.

Thanks,
Jim

**Comment by sumurthy** [comment]
Hi @jbarr33 - We'll take a look and get back.

**Comment by sumurthy** [comment]
Bug 1340752
Will follow-up after the bug is addressed.
