### ISSUE TITLE
How to add a filter to remove (Blanks) from a column?

### ISSUE THREAD

**Issue by renil** [OfficeDev/office-js-docs#622]
I have a table with 140 columns. Trying to add a filter to remove all the rows with (Blanks) in all of those columns. How to add a filter for (Blanks)?

**Comment by Lauragra** [comment]
Hi, this question has been answered on StackOverflow: http://stackoverflow.com/questions/40749429/how-to-add-a-filter-to-remove-blanks-from-a-column. Closing this issue for now. Thanks.
