### ISSUE TITLE
Insert a table with the specified number of rows and columns into a content control - ContentControl Object (JavaScript API for Word)

### ISSUE THREAD

**Issue by ApsaraSanjeewani** [OfficeDev/office-js-docs#624]
`contentControlObject.insertTable(rowCount, columnCount, insertLocation, values);`

I tried to use this method to add a table into a content controller.

` function createContentControlForTable(tableName, number_columns, number_header, number_body, number_footer) {
        Word.run(function (context) {
            var range = context.document.getSelection();
            var myContentControl = range.insertContentControl();
            myContentControl.tag = "Table name:" + tableName;
            myContentControl.title = "Table name:" + tableName;
            myContentControl.appearance = "Tags";
            myContentControl.style = "Normal";

            myContentControl.insertTable(number_header, number_columns,'End');
            myContentControl.insertText("", 'replace');
            myContentControl.cannotEdit = false;

            context.load(myContentControl, 'id');

            return context.sync().then(function () {
            myContentControl.tag = myContentControl.tag + " id:" + myContentControl.id;
            myContentControl.title = myContentControl.title + " id:" + myContentControl.id;
            showNotification("Table", "Table added successfuly");
            console.log('Created content control with id: ' + myContentControl.id);
            return context.sync().then(function () {
            //showNotification("Success", "Section added succesfully.")
                });
            });
        })
       .catch(function (error) {
           console.log('Error: ' + JSON.stringify(error));
           errorHandler(error)
           if (error instanceof OfficeExtension.Error) {
               console.log('Debug info: ' + JSON.stringify(error.debugInfo));
           }
       });
    }`
, but I am having a run time error saying 
> JavaScript runtime error: Object doesn't support property or method 'insertTable' 'iexplore.exe' 

The documentation is also not having a code example for this method. Please help me with this.

Thank you.

**Comment by kbrandl** [comment]
@ApsaraSanjeewani apologies for the lack of response on this. Are you still having trouble? The Office.js API and platform has evolved quite a bit since this issue was opened, so this may no longer be an issue. I'm going to close this issue, but please feel free to re-open it or log a new issue in the [OfficeDev/office-js](https://github.com/OfficeDev/office-js) repo if you're still having trouble.
