### ISSUE TITLE
Recalculate Bug in Excel-JS

### ISSUE THREAD

**Issue by FastExcel** [OfficeDev/office-js-docs#627]
I cannot make Office-JS recalculate dirty formulas in a workbook when in Manual mode: this code does not recalculate dirty formulas the way it should
// calculate - equivalent of F9 or Application.Calculate
context.workbook.application.calculate("Recalculate");
await context.sync();

**Comment by sumurthy** [comment]
Please track the feature from here: https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/suggestions/17720146-excel-js-re-calculation-mode-to-only-calc-dirty-ce
