### ISSUE TITLE
Visio-boundingBox-x

### ISSUE THREAD

**Issue by JohnGoldsmith** [OfficeDev/office-js-docs#628]
Can you say whether this is the left or right edge please?  I assume left for x, but is ambiguous for y, which would be bottom for Desktop but perhaps Top for Online?

**Comment by rahul-mi** [comment]
The origin of the Cartesian coordinate system for x and y is the bottom left corner of the drawing page; x increases in value from left to right, and y increases in value from bottom to top.

**Comment by Lauragra** [comment]
It looks like this issue is resolved so closing for now. Let us know if you have additional questions. Thanks.
