### ISSUE TITLE
Add-in not loading in catalog if it contains European language character in office 2016 

### ISSUE THREAD

**Issue by abaidurrehman** [OfficeDev/office-js-docs#633]
I have one manifest works fine loading from"office 365 app Catalog" site with English character in description and name,  but when I add **German or any other European characters** it **stop** loading from the catalog; basically it does not render in "My Add-ins" >> "My Organization" apps. it works fine with Word 2013 but does not work with word 2016.

If I used file share as catalog it loads fine for both 2013 and 2016 
[SampleManigestFile.zip](https://github.com/OfficeDev/office-js-docs/files/621045/SampleManigestFile.zip)

I have attached sample manifest file.
Encoding for the manifest file is "unicode (utf-8 with signature) - codepage 65001"

I am not sure I will have the same issue when we submit it to "Office Store"

**Comment by PhilSmail** [comment]
I was able to repro this. It's definitely the ü in the german text that causes the issue. If you remove it then it works in 2016. 
This seems to be a very specific issue with the Add-In catalog in 2016 so I doubt it'll be an issue with the store but we'd recommend that you test using a shared folder

**Comment by abaidurrehman** [comment]
Thank you for acknowledging it. 

I have tried it with Shared folder it works fine, Our app is also correctly showing in Store with German characters.

However It would be great if this issues get fixed in Catalog for office 2016.

**Comment by Lauragra** [comment]
Thanks for raising this issue. We'll log this as a bug internally. Feel free to reopen if you have additional issues.
