### ISSUE TITLE
Getting Access Denied error with message (You do not have permissions..)

### ISSUE THREAD

**Issue by premchandpl** [OfficeDev/office-js-docs#634]
When trying to access office.js library for word add in, I am getting "You do not have permissions". I have set the permissions to "ReadWriteDocument" in the maniest file and below is the code I am using

Office.context.document.getFileAsync("compressed", {sliceSize:100000},  function (asyncResult) {
                    if (asyncResult.status === Office.AsyncResultStatus.Succeeded) {
                        //Get the file object from the result
                        var myFile = asyncResult.value;
                        var state = {
                            file: myFile,
                            counter: 0,
                            sliceCount: myFile.sliceCount
                        }
                        //getSlice(state);
                    }
                });

I have hosted this Office manifest file in Sharepoint office catalog. Let me know if any solution is there for this issue

**Comment by Lauragra** [comment]
Hi,
Thanks for reaching out. This repo is primarily for feedback on the docs. For more specific help with your code, we recommend that you post your question to StackOverflow and tag with [office-js]. I'm closing this issue for now but feel free to reopen if you have a suggestion for how we can clarify our documentation. Thanks!
