### ISSUE TITLE
Unable to access the reference in github for WordJs_1.3_Openspec (New API for Word)

### ISSUE THREAD

**Issue by ApsaraSanjeewani** [OfficeDev/office-js-docs#635]
I am unable to find the page [https://github.com/OfficeDev/office-js-docs/blob/WordJs_1.3_Openspec/reference/word/contentcontrol.md](url) and it is giving 404 error.
![image](https://cloud.githubusercontent.com/assets/8555293/20875442/e1e25d50-bae0-11e6-9f32-314791e1d17a.png)
Please let me know where I can find the reference for the new API for word(1.3 version).

Regards,
Apsara

**Comment by jorgenho** [comment]
Same goes for 1.4 😐

**Comment by Lauragra** [comment]
Hi, you can find the Word JS 1.3 Open Specs here: [https://github.com/OfficeDev/office-js-docs/tree/WordJs_1.3_Openspec](https://github.com/OfficeDev/office-js-docs/tree/WordJs_1.3_Openspec,) and the Word JS 1.4 here: [https://github.com/OfficeDev/office-js-docs/tree/WordJs_1.4_OpenSpec](https://github.com/OfficeDev/office-js-docs/tree/WordJs_1.4_OpenSpec).

If you're still having issues, feel free to reopen. Thanks.
