### ISSUE TITLE
Word App API 1.3 - Status Quo?

### ISSUE THREAD

**Issue by ThorstenHans** [OfficeDev/office-js-docs#636]
According to this page [https://dev.office.com/reference/add-ins/openspec](https://dev.office.com/reference/add-ins/openspec) version `1.3` is mentioned as **implemented**. But the page links to [https://github.com/OfficeDev/office-js-docs/tree/WordJs_1.3_Openspec/word](https://github.com/OfficeDev/office-js-docs/tree/WordJs_1.3_Openspec/word). 

Also [https://dev.office.com/reference/add-ins/requirement-sets/word-api-requirement-sets](https://dev.office.com/reference/add-ins/requirement-sets/word-api-requirement-sets) seems to be a kind of outdated. 

I would like to access document properties from my Word AddIn and address two scenarios

- grab basic metadata about the document
- persist custom property from the app inside of the document

Is there anything you can shared about alternative solutions or timeframe for `1.3` availability?

**Comment by jeanie77** [comment]
any news on this topic?

**Comment by mariusmuntean** [comment]
I'm also interested in editing the document properties. 

Any update is appreciated.

**Comment by JuaneloJuanelo** [comment]
Thanks.
Regarding your first comment on this URL:   https://dev.office.com/reference/add-ins/openspec the information there is accurate in the sense that the API is implemented and its in PREVIEW mode, this means you need to have the[ latest office install ](https://dev.office.com/docs/add-ins/develop/install-latest-office-version)and use the BETA Office.js CDN to use it, namely https://appsforoffice.microsoft.com/lib/beta/hosted/office.js.


Regarding your second question on this URL  https://dev.office.com/reference/add-ins/requirement-sets/word-api-requirement-sets that information is also correct as the 1.3 is still in preview.


You can definitely try the preview as described on the first paragraph and you can definitely also use the preoperties object to both, get doc metadata, and also to create and read custom properties.

here is an example of getting doc metadata: 

`  Word.run(function (context) {
                var builtInProperties = context.document.properties;
                context.load(builtInProperties)
                return context.sync()
                    .then(function () {
                        console.log(builtInProperties.author);
                        console.log(builtInProperties.title);
                        console.log(builtInProperties.applicationName);
                        console.log(builtInProperties.category);
                        console.log(builtInProperties.comments);
                        console.log(builtInProperties.creationDate);
                        console.log(builtInProperties.keywords);
                        console.log(builtInProperties.lastPrintDate);
                        console.log(builtInProperties.lastSaveTime);
                        console.log(builtInProperties.template);
                        console.log(builtInProperties.subject);
                        console.log("And visit https://github.com/OfficeDev/office-js-docs/blob/WordJs_1.3_Openspec/reference/word/documentproperties.md  for a complete list");
                    })
            })
`
Here is an example of how you can create custom properties:
`  Word.run(function (context) { 
         context.document.properties.customProperties.add("PropertyName", 1234);
         return context.sync()
     }) `

**Comment by AhmedVali** [comment]
Hi,
Has anyone tried the above approach ?
I'm unable to retrieve the properties.

Br\\

**Comment by kbrandl** [comment]
Closing this issue, as support for [Document.properties](https://docs.microsoft.com/en-us/javascript/api/word/word.document?view=office-js#properties) was included in WordAPI 1.3, which is [available on multiple platforms](https://docs.microsoft.com/en-us/office/dev/add-ins/overview/office-add-in-availability#word), and the docs have been updated accordingly.
