### ISSUE TITLE
OpenSpec-Doc-Properties

### ISSUE THREAD

**Issue by ThorstenHans** [OfficeDev/office-js-docs#637]
Are these the document properties mentioned in spec `1.3` of the Word Add-In API? Can they be used in the fat clients listed here [https://dev.office.com/reference/add-ins/requirement-sets/word-api-requirement-sets](https://dev.office.com/reference/add-ins/requirement-sets/word-api-requirement-sets)

Some clarification here would be great

**Comment by sumurthy** [comment]
Hi @ThorstenHans: the document properties are coming as part of Word1.3 version. The reference page you mentioned lists the earliest version that Word1.3 is available. 

The Document Properties were added in one the recent updates. I'm adding @JuaneloJuanelo to the issue to update you on the exact build# to use.

**Comment by kbrandl** [comment]
Closing this issue, as support for [Document.properties](https://docs.microsoft.com/en-us/javascript/api/word/word.document?view=office-js#properties) was included in WordAPI 1.3, which is [available on multiple platforms](https://docs.microsoft.com/en-us/office/dev/add-ins/overview/office-add-in-availability#word).
