### ISSUE TITLE
Visual Studio project type in "Host an Office Add-in on Microsoft Azure"

### ISSUE THREAD

**Issue by spcrux** [OfficeDev/office-js-docs#647]
on Host an Office Add-in on Microsoft Azure (https://dev.office.com/docs/add-ins/publish/host-an-office-add-in-on-microsoft-azure) page, in Step 4: Create an Office Add-in in Visual Studio - in my Visual Studio 2015 the add-in project types are different. There's no Office Add-in but there separate add-in projects for Outlook, Excel, Word and PowerPoint. I think the instructions in Step 4 need to be updated to reflect the latest versions of all.

**Comment by keyur32** [comment]
Hi @spcrux, you're right in that we have a documentation issue here. We're going to address it to be more clear and call out you will need.

**Comment by mvpkenlin** [comment]
Is there any other way to publish Office Addin without VS?

**Comment by Reezaali** [comment]
Hi @spcrux, sorry for the late reply. The documentation was updated a couple of months ago. Thanks!

**Comment by kbrandl** [comment]
Closing this issue, since the docs have been updated.
