### ISSUE TITLE
Same versions of Office.js hosted on 'beta' and '/1/'?

### ISSUE THREAD

**Issue by subodh737** [OfficeDev/office-js-docs#654]
The production hosted office.js api library at  "https://appsforoffice.microsoft.com/lib/1/hosted/office.js "
shows 
/* Office JavaScript API library */
/* Version: 16.0.7625.1000 */

and 

The beta hosted office.js api library at "https://appsforoffice.microsoft.com/lib/beta/hosted/office.js"
also shows the same 
/* Office JavaScript API library */
/* Version: 16.0.7625.1000 */

Is there something missing on the preview channel updates?

**Comment by subodh737** [comment]
This has also happened earlier.

You can view the comment by "Miro J" at the bottom of this page.
http://stackoverflow.com/questions/39500918/change-value-of-a-table-in-content-control

It appears the Office API team put an older version on their CDN as pre-release. Now, things are back to 16.0.7424.1000. I wonder if someone knows a place where I can see what and when changes - the smaller commits? – Miro J. Oct 21 at 14:29

**Comment by Zlatkovsky** [comment]
Please see a very similar question at:  http://stackoverflow.com/questions/41130272/same-versions-of-office-js-hosted-on-beta-and-1/41132928#41132928

We are investigating the best way for making a simpler way of knowing what changes are being made to the CDN...

**Comment by Lauragra** [comment]
Thanks. I'm closing the issue here as we're tracking this on stackoverflow. Feel free to reopen if we can help clarify this issue in the documentation.
