### ISSUE TITLE
Whitespace in markdown causes incorrect link rendering

### ISSUE THREAD

**Issue by Blackbaud-BobbyEarl** [OfficeDev/office-js-docs#655]
On https://dev.office.com/docs/add-ins/develop/referencing-the-javascript-api-for-office-library-from-its-cdn, the markdown link for "Update the version of your JavaScript API for Office and manifest schema files" has a space between the brackets and parenthesis, which appears to cause the renderer for your website to not handle it correctly.

![bad-markdown-syntax](https://cloud.githubusercontent.com/assets/4612419/21237601/a3cd7604-c2cd-11e6-8945-744a7269ee1e.jpg)

**Comment by Lauragra** [comment]
Good catch - thanks! I merged your PR.
