### ISSUE TITLE
excel-1.4

### ISSUE THREAD

**Issue by jkpieterse** [OfficeDev/office-js-docs#665]
I would like some consistency between with how things are named in VBA and how very similar things are to be named in JS. I don't see why one would use totally different names for methods and properties unless the current VBA names for them are illogical.

**Comment by zbarresse** [comment]
Agreed. It's can be very confusing.

**Comment by sumurthy** [comment]
Thanks for the feedback. Generally, the names are the same or very similar. 

In some cases where we think the names could be more clear, we have changed. 
Example: "interior" is "fill". This also applies to some of the relations. Range has a format object, which groups all formatting related items such as fill, font, borders. 
Example : ListObject is confusing and most users would recognize and use `table` instead. 
Also, the JavaScript naming convention plays a part too such as camel-casing. 

We'd like to take this opportunity to make the names better and in the long run this will serve the community better, at the cost of some mental translation at the beginning.
