### ISSUE TITLE
excel-1.4 getboundingrange

### ISSUE THREAD

**Issue by FastExcel** [OfficeDev/office-js-docs#666]
if you are using more than 2 objects then GetRangeBetween does not make sense, GetBoundingRange is better

**Comment by Zlatkovsky** [comment]
@FastExcel:  would GetBoundingRange have made sense to you, if you were looking for a functionality to get a range using two ranges?

The case for 3 or more ranges seems very much like a 1% corner-case -- so if you think "GetRangeBetween" made the most sense, and if you agree that intersecting 3 or more ranges is rare, I'm fine changing the API to only take a start and end range.

**Comment by FastExcel** [comment]
If you limit to 2 I don't have a strong preference

**Comment by Zlatkovsky** [comment]
Is there another name you would find more intuitive, that you do have a clear preference on?  If we're going to be doing the renaming from range.getBoundingRect(anotherRange) to something else, we want to make sure that it is indeed better!

**Comment by FastExcel** [comment]
On balance I think GetBoundingRange is the best name ...
