### ISSUE TITLE
excel-1.4 getRangeR1C1

### ISSUE THREAD

**Issue by FastExcel** [OfficeDev/office-js-docs#667]
Range Row and Column numbers should start with 1 not zero because thats the way the Excel grid works
Arrays should start with zero since thats the way JS does it.

So If you choose getRangeR1C1 then the row and column have to be 1-based row and column numbers as in Excel R1C1 mode rather than indexes.

If you want to use zero-based indexes then you should use getRangeByIndexes

GetCells is not a good choice because its inconsistent naming a Range should always be called Range and not Cells

**Comment by Zlatkovsky** [comment]
@FastExcel, the thought here was that the WIDTH and HEIGHT are one-based (a la R1C1).
With GetRangeByIndexes, I think that what gets lost is the desire to says "I want a 5x10 rectangle starting at cell xyz).  It suddenly feels like you need to supply indexes for parameters #3 and #4, whereas I felt like those -- for ease of use -- would be better to have as counts.

Thoughts?

**Comment by FastExcel** [comment]
If you want to call it R1C1 you need to use row numbers for #1 and #2 because thats the way R1C1 XL mode works, otherwise its confusing.

For GetRangeByIndexes I would understand that the number of rows and columns is a count but the indices are zero-based
