### ISSUE TITLE
Table 'show' properties, Excel 1.4

### ISSUE THREAD

**Issue by zbarresse** [OfficeDev/office-js-docs#668]
A few proposed Table properties have inconsistent naming conventions. For example _highlightFirstColumn_ and _highlightLastColumn_. These are boolean settings. So are _showBandedRows_, _showBandedColumns_, and _showFilterButton_. They should be prefaced with "show" as well.

**Comment by sumurthy** [comment]
Hello, 

The first word "show" and "highlight" indicates both the current setup and also acts as a "verb" for set action. Since highlight doesn't have the impact of show/hide, it is named with "highlight" prefix.
