### ISSUE TITLE
OpenSpec-tableRowCollection-add

### ISSUE THREAD

**Issue by zbarresse** [OfficeDev/office-js-docs#672]
We need to be able to specify the location of the rows to add. If not specified it should add to the end of the table. We also need to be able to specify the number of rows to add.

**Comment by sumurthy** [comment]
Hello @zbarresse, Please review the table rows [add](https://github.com/OfficeDev/office-js-docs/blob/ExcelJs_1.4_OpenSpec/reference/excel/tablerowcollection.md#addindex-number-values-boolean-or-string-or-number) method. I think this meets the needs you have mentioned. 
If you see any issues, please re-open the issue. 

Thank you
