### ISSUE TITLE
NamedItem.getRefersTo

### ISSUE THREAD

**Issue by FastExcel** [OfficeDev/office-js-docs#676]
There does not seem to be a way of getting the RefersTo string or the RefersToLocal string for a NamedItem?

**Comment by sumurthy** [comment]
Based on the type (if type == 'Range'), you could get the range address using name1.getRange.address and name1.getRange().addressR1C1, .addressLocal, etc.

**Comment by FastExcel** [comment]
But how do you get the refersto if its not a Range

**Comment by FastExcel** [comment]
Yes I see that but 
a) it does not help if you have a range and want to find out its name (read name of range object)
b) if you have a range and you want to give it a name its very long-winded to get its address and then create a name using that as the refersto - much better to simply name it (write name of range object)
