### ISSUE TITLE
NamedItem Formulas not found

### ISSUE THREAD

**Issue by FastExcel** [OfficeDev/office-js-docs#677]
NamedItems do not seem to support named formulas. says it cannot find them

**Comment by sumurthy** [comment]
This will support formulas in named item such as "=MAX(Sheet1!A:A)". Is that what is being asked. Sorry if I didn't understand the question correctly.

**Comment by FastExcel** [comment]
I am only testing 1.3 - if you have a defined name containing a formula 1.3 says the name cannot be found.
A named formula can be any formula and can return any native data type or a range or an array (think IF, OFFSET, INDIRECT, INDEX or CHOOSE)

**Comment by sumurthy** [comment]
The ability to create named item is available with 1.4.
