### ISSUE TITLE
NamedItem.Evaluate

### ISSUE THREAD

**Issue by FastExcel** [OfficeDev/office-js-docs#678]
Does not seem to be an Application.Evaluate or Worksheet.Evaluate method for defined names?

**Comment by sumurthy** [comment]
Hello, do you mean worksheet evaluate() method in general? That is something on the roadmap and when available, it should work on defined names too, no? thanks.

**Comment by FastExcel** [comment]
You probably need both application and Worksheet Evaluate (and possibly Chartsheet.evaluate too)
OK - if its in the roadmap beyond 1.5 thats fine

**Comment by dcu-sharepoint** [comment]
right! it would be nice if they fixed the broken crap....

**Comment by sumurthy** [comment]
duplicate #684
