### ISSUE TITLE
Word: Replacing text turns bulleted paragraph into numbered paragraph

### ISSUE THREAD

**Issue by NickAtk** [OfficeDev/office-js-docs#68]
I have used both context.document.body.insertOoxml) and paragraph.insertOoxml() to replace text in a paragraph successfully.

However if the paragraph is originally bulleted then I find that Word changes it to a numbered list paragraph when some text in the paragraph is replaced.  In other word the list/numbering information is not preserved correctly.

This happens on Windows, Mac and iOS.

Has anyone experienced this?  Is it a known issue?  Is there a workaround?  Is there any preprocessing I can perform on the Ooxml to prevent this from happening?

**Comment by MIchaelMainer** [comment]
Thank you @NickAtk for reporting this issue. Does this occur with any OOXML you insert into the paragraph that is part of a bulleted list?

@JuaneloJuanelo

**Comment by NickAtk** [comment]
The sort of thing I am doing is simple replacement of some text with some other text.  However even if the text is unchanged it happens.  Every time.  Very consistent.

I have tried OOXML with (and without) the numbering.xml data (relationship http://schemas.openxmlformats.org/officeDocument/2006/relationships/numbering) which I haven't altered from what Word gives me (except removing the mc:Ignorable attribute).  

Word appears to change the information in the numbering.xml data in a way that doesn't preserve the appearance of the paragraph.

**Comment by JuaneloJuanelo** [comment]
@NickAtk  thanks for reporting this. I have a quick question, if you are just replacing text why not use insertText method? or why is it that you need OOXML or HTML ? thanks!

**Comment by JuaneloJuanelo** [comment]
@NickAtk  btw this was a known issue and was fixed and will be available soon.
This is the code that i tried in the updated build and it just replaces the text. Tried it in a list context and also works ok. (just replaces the text without modifying the list format). Would be great if you can share the HTML and the OOXML you are trying to insert to verify  it. thanks!

`  function replaceWithText() {
        Word.run(function (ctx) {
            var myRange = ctx.document.getSelection().insertText("This is the Text!", "replace");
            return ctx.sync();
        });



    }

    function replaceWithHTML() {
        Word.run(function (ctx) {
            var myRange = ctx.document.getSelection().insertHtml("<b>some bold text!</b>", "replace");
            return ctx.sync();
        });

    }

    function replaceWithOOXML() {
        Word.run(function (ctx) {
            var myRange = ctx.document.getSelection().insertOoxml("<w:p xmlns:w='http://schemas.microsoft.com/office/word/2003/wordml'><w:r><w:rPr><w:b/><w:b-cs/><w:color w:val='FF0000'/><w:sz w:val='28'/><w:sz-cs w:val='28'/></w:rPr><w:t>Hello world (this should be bold, red, size 14).</w:t></w:r></w:p>", "replace");
            return ctx.sync();
        });


    }
`
