### ISSUE TITLE
Range.Name missing

### ISSUE THREAD

**Issue by FastExcel** [OfficeDev/office-js-docs#680]
There does not seem to be a Name property for a Range object or a Range.getName method:
a) if you have a Range object you want to find out its Name (read RangeName)
b) If you have Range object you want to Name you need a simple way to set its name (write RangeName), and of course before you do that you want to find out if its already got a Name.
c) In theory you could loop thru the Names collection looking for a refersto that matches the Range Address but thats fairly horrible and inefficient if you have 10000 or 100000 names.

**Comment by sumurthy** [comment]
Hello, 
Thanks for the feedback. I'll get back on the priority of this feature.

**Comment by sumurthy** [comment]
Please track this feature here: https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/suggestions/17720068-excel-js-api-property-on-range-object-to-read-the
