### ISSUE TITLE
Question about APIs

### ISSUE THREAD

**Issue by sparkxxxxxx** [OfficeDev/office-js-docs#687]
I have seen the project published on github: https://github.com/OfficeDev/PowerPoint-Add-in-Microsoft-Graph-ASPNET-InsertChart, the project could insert an image of a chart into a PowerPoint slide.

I want insert charts, and get selected chart using office.js. But i can't find relevant APIs, does APIs not provide enough relevant APIs now?

Thanks in advanced

a big fan of office develop

**Comment by dcu-sharepoint** [comment]
I'm having a problem following the OfficeDev/Word-Add-in-JavaScript-InvoiceManager found in github. can somebody please direct me to a forum or dev center office where I can ask questions.

the specific problems I'm having are: 
1) how to bind the controls in the word document to a SharePoint list. 
2) how to create a dynamic table control collections so it can be filled from list items.

these are critical as I have a customer waiting for a solution and I have not been able to find anything on the subject anywhere!

Thanks for your help

**Comment by keyur32** [comment]
Hi @sparkxxxxxx, great you found the sample. Today, the apis for building charts aren't available in PowerPoint through Office.js. If you wanted to generate presentations with chart, I'd look to use the Office Open XML SDK to generate presentations: https://github.com/OfficeDev/Open-XML-SDK.

Hope that helps!
