### ISSUE TITLE
Variable Print Quality with HTML5 Components in Powerpoint

### ISSUE THREAD

**Issue by pmckenna** [OfficeDev/office-js-docs#689]
Hi Team,

We've been exploring embedding dynamic (HTML5,D3 Based) charting in Powerpoint using office.js. However, we've found that the print quality varies quite wildly depending on OS, and also appears to be influenced quite heavily by zoom level of the document. For instance, zooming a slide to 400% results in a great rasterization result in Powerpoint for Mac (version 15.x) but when at 100% the result is quite blurry. We've tried both saving to PDF, printing to PDF, and playing with stated image compression controls. Strangely only slide zoom has any effect on quality.

Trying the same test on a PC running Windows 10, Office 2016, actually results in the web page becoming extremely zoomed out at 400% or zoomed in at 50%. Note that both the above tests were performed with the "Web Viewer" component from the office 365 store as a test harness. 

We are essentially looking to reliably control the rasterization of the components across different operating systems. Are there any options available for this?

Thanks

**Comment by dcu-sharepoint** [comment]
it would be nice if your team fix what is broken already instead of creating more broken crap

**Comment by keyur32** [comment]
Hi @dcu-sharepoint - sorry for the frustration. I believe someone on the team replied on the feedback you left for the sample (if you have any questions, feel free to respond there)

@pmckenna  - Thank you for your report. I checked with the team and we had a few questions. The behavior of the add-in is to zoom the browser window to match the slide zoom as the addin is part of the document.  We have to do this to keep the content that the user sees on the screen consistent.  On print, this limitation means we print at the current zoom level.  How does this compare for when you print directly from Safari (on mac) at those zoom settings?

**Comment by dcu-sharepoint** [comment]
@pmckenna<https://github.com/pmckenna>; I didn't a question about printing. heck, I can't even finished with the HelloWorld example....

but thanks for the reply

L. Carlos Rodriguez


________________________________
