### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by sumurthy** [OfficeDev/office-js-docs#7]
1. The first few paragraphs are redundant. Anytime we modify definitions, we'll have to remember to change in all places. Rather have that in a separate place. You can start with "Your first add-in" section. 

2. should be "The below steps show..."

3. "loads some data into a worksheet and creates a simple chart." Could we clarify what this "some data" and 'simple chart are? e.g., "sends products data and creates quarterly trend chart"

In general,  it'll be good to lead with some background on what add-in does. e.g., Though the product data is hard-coded, it could have been read from a database/external source. The chart creation helps with analysis of the products data, etc. 

4. Do we need "Set it up"

5. Use passive voice and avoid second person pronouns? I prefer that style.. you don't have to follow it.

Instead of 
"To create the add-in, you essentially need to create a web app and an XML manifest file that tells where your web app is located and how you want it to appear within Excel" 
-try- 
"1. Create web app and XML manifest file that describes the web application's location and its appearance within Excel "
Same applies to other cases such as "Let's now create the...", "Believe it or not, we’ve only just begun exp..."

6. It'll be helpful to show a diagram at the beginning of the final directory structure that shows all the files/sub-folders. 

7. I'm guessing you'll use the CDN locations in manifest snippet at the end. 

8. "Generate a GUID using an online generator" is one of few options I think. Folks may use in-house generators. Maybe we can say, for this sample an online generator could be used to obtain a GUID. 

9. "Try it out" can use screen shots. Also, you can mention the creation of network share on a standalone desktop. Most people trying this out at home may not have a corp network drive...

**Comment by umasubra** [comment]
I've already fixed all of the comments that were actionable in the short term. Network drive comment, we'll have to come back to, soon.
