### ISSUE TITLE
Can i use WebSocket or Socket.io in add-ins?

### ISSUE THREAD

**Issue by sagnol** [OfficeDev/office-js-docs#70]
first, please understand a pool command of my English.
(I would like my question to be conveyed .)

I am just curios.

Can i use WebSocket or Socket.io in add-ins?
Also, How about React.js?

**Comment by Reezaali** [comment]
Sure! Here's some resources that may be helpful:
[Use the OAuth authorization framework in an Office Add-in](https://msdn.microsoft.com/en-us/library/office/mt629180.aspx)
[Office-Add-in-Nodejs-ServerAuth](https://github.com/OfficeDev/Office-Add-in-NodeJS-ServerAuth)

**Comment by sagnol** [comment]
Thanks! @Reezaali !

**Comment by sagnol** [comment]
React.js : [](https://github.com/UKDXOfficeDev/office-reactjs-taskpane-addin)

**Comment by MIchaelMainer** [comment]
@sagnol Thanks for the screen cast and sample link!
