### ISSUE TITLE
outlook getAsync method  return always null in compose mode on mobile browsers

### ISSUE THREAD

**Issue by OriAmir** [OfficeDev/office-js-docs#701]
Hey , I try to use my add-in on **mobile browsers** . I success to see my add-in and to use him . 
I success to set text on compose mode with setAsync method  , but I not success to **get** the text with getAsync method . no matter what I try with correction Type and many another things it's return null in the value of the call back response...

On read mode I success to use getAsync and to get the correct text from my message...

So I think maybe I have a problem on my add-in so I create one that just take the text with getAsync but it's always return null on mobile. in computer everything is OK..

Maybe it's bug? maybe I do something wrong ?

Thank you all.

**Comment by mlafleur** [comment]
These is a bug with getAsync in mobile browsers at the moment. Technically it isn't "mobile" so much as the OneColumn view in OWA. I am not aware of a workaround at this time but you can test for the scenario using [Office.context.mailbox.dianostics.OWAView](https://github.com/OfficeDev/office-js-docs/blob/master/reference/outlook/Office.context.mailbox.diagnostics.md#owaview-string).

**Comment by Lauragra** [comment]
Thanks all; I'm closing this issue for now, feel free to reopen if you have further questions or if we can help to clarify something in the documentation.
