### ISSUE TITLE
Loading data into custom XML parts bound to content controls in a Word document

### ISSUE THREAD

**Issue by dcu-sharepoint** [OfficeDev/office-js-docs#704]
this is a very frustrating issue  as I don't seem to be able to make some headway.

this question is about the javascript office-js-docs  the **Word add-in: Loading data into custom XML parts bound to content controls in a Word document** example from the **GITHUB** site

I would like to get some help on the binding control issue with the example downloaded for the GitHub site.

I'm still trying to find information on a couple of (frustrating )things I've posted several times.

**_1) how to create the controls on the word document.
2) how to bind data from the javascript to the word document
3) how to make the table dynamic, in other words, say you have one row for one packing slip and 10 rows for another packing slip._**

at least send me some links I can explore. after binging and googleling and even trying to get paid support from Microsoft, I still don't have an answer.

I made the mistake of showing the example to a customer who immediately decided on going for this solution.

going to stackoverflow has not helped so where else can I go besides HELL!.

**Comment by Rick-Kirkham** [comment]
@dcu-sharepoint 
If you haven't read it already, start here: [Word add-ins overview](https://dev.office.com/docs/add-ins/word/word-add-ins-programming-overview).
There are actually two JavaScript API object models that can be used in Office Web Add-ins:

- JavaScript API for Office (also called Common)
- Word (or Excel) JavaScript API (also called Host-specific)

The sample you refer to, [Word-Add-in-JavaScript-InvoiceManager](https://github.com/OfficeDev/Word-Add-in-JavaScript-InvoiceManager), uses the first of these exclusively. For more about the distinction between them and how to use them, see [Word Add-ins Reference Overview](https://dev.office.com/reference/add-ins/word/word-add-ins-reference-overview).

I think for what  you have in mind, you should try to work as much as possible with the host-specific Word Javascript API for the fine-grained interaction with the Word document. For example, it has a Table object with methods for creating a table, adding rows to a table, and populating it with data. For a sample that uses the Table object in these ways and does not assume a fixed number of rows for the table, see [Word-Add-in-MarkdownConversion](https://github.com/OfficeDev/Word-Add-in-MarkdownConversion). Our documentation for the latest/greatest version of this Word-specific API set is not in dev.office.com yet. You can find it by going to [office-js-docs](https://github.com/OfficeDev/office-js-docs) and then opening the **Branch** drop down list and choosing **WordJs_1.3_openspec**.

Regarding you questions:
1) By "controls" I assume that you mean either [CustomXMLPart](https://dev.office.com/reference/add-ins/shared/customxmlpart.customxmlpart)s from the "common" API or [ContentControl](https://github.com/OfficeDev/office-js-docs/blob/WordJs_1.3_Openspec/reference/word/contentcontrol.md)s from the Word-specific APIs.
2) We have a topic on binding data to objects in the Word document here: [Bind to regions in a document or spreadsheet](https://dev.office.com/docs/add-ins/develop/bind-to-regions-in-a-document-or-spreadsheet).
3) If you use the Word-specific APIs, the sample I mentioned above shows how to add any number of rows to a table: [Word-Add-in-MarkdownConversion](https://github.com/OfficeDev/Word-Add-in-MarkdownConversion). If you use the Common APIs as the InvoiceManager sample does, perhaps there is a way that you can put a call to `_document.customXmlParts.addAsync` inside a loop that loops through your packing slips.

**Comment by dcu-sharepoint** [comment]
thanks for the links, will study all of them and report back with my progress




________________________________

**Comment by dcu-sharepoint** [comment]
I finally found documentation on the openXML from one of the links I received.

Thank you
