### ISSUE TITLE
Office.context.officeTheme is undefined

### ISSUE THREAD

**Issue by echoworxdev** [OfficeDev/office-js-docs#722]
Hello all,
I am building a Office365 add-in on Visual studio.
As mention in the title, I am unable to get the officeTheme object even in desktop client mode.

Kindly help.

**Comment by LezaMax** [comment]
Hi, could you please post your question on stackoverflow and tag it with **office-js**, we can follow up further there. Please include which host (Word/Excel/PPT or Outlook) you are targeting. Thank you.
