### ISSUE TITLE
Need reference material and sample for menus

### ISSUE THREAD

**Issue by LezaMax** [OfficeDev/office-js-docs#757]
- On this page: https://github.com/OfficeDev/office-js-docs/blob/master/reference/manifest/extensionpoint.md we are missing content for how to use the different "Control" types of "Button" and "Menu" (the links are broken)
-We need a public sample that illustrates its use
-Likely also update the overview article for commands to point to the samples we create

**Comment by kbrandl** [comment]
Closing this issue as the links have been fixed (https://docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/extensionpoint#extension-points-for-word-excel-powerpoint-and-onenote-add-in-commands) and those target pages provide code snippets.
