### ISSUE TITLE
Outlook Addin for iOS not working

### ISSUE THREAD

**Issue by thiagodosreis** [OfficeDev/office-js-docs#762]
Hi guys,

I really hope you can help me find out a solution for my problem. I have been trying to make it work for the last 4 days with no success.

I'm trying to implement the new Addin on Outlook for iOS Devices.

I already changed the manifest file to include the Mobile, uploaded in the Office Add-in repository and now when I open the Outlook for iPhone it is showing under my Settings>Add-ins for Enable and Disable.

However, when I Enable it in the settings and open an email to read it and click on the Addins button, my Addin doesn't show in the list, only the others Addins that I have enabled too. 

I can't understand why. Here is my manifest, if someone it could help me would be so good! 

http://www.accerti.com.br/downloads/MoxtramanifestiOS_copy_v2.xml 

thank you. Thiago

**Comment by Lauragra** [comment]
Hi Thiago, thanks for reaching out. This repo is primarily for feedback on the documentation. For specific help with your code or manifest, we recommend that you post your question to [StackOverflow](https://stackoverflow.com/search?q=office-js), and tag with [office-js]. You're likely to get a faster response. I'm closing this issue for now, but if we can assist by updating or clarifying our docs, feel free to reopen. Thanks.

**Comment by thiagodosreis** [comment]
Ok Laura, thank you.

**Comment by jasonjoh** [comment]
Feel free to ping me on Twitter (@JasonJohMSFT) with your StackOverflow link.
