### ISSUE TITLE
Missing documentation on binding.addHandlerAsync

### ISSUE THREAD

**Issue by ThorstenHans** [OfficeDev/office-js-docs#763]
The `binding.addHandlerAsync` method is able to receive an `options` parameter. When reviewing the docs [here](https://dev.office.com/reference/add-ins/shared/binding.addhandlerasync), no further information is provided.

Are there any valid parameters that could be provided as part of the `options` argument?

**Comment by Lauragra** [comment]
Hi, does this content provide the information you're looking for?
[Passing optional parameters to asynchronous methods](https://dev.office.com/docs/add-ins/develop/asynchronous-programming-in-office-add-ins#passing-optional-parameters-to-asynchronous-methods)

**Comment by ThorstenHans** [comment]
@Lauragra no, its not about how to create a `JSON` object :D it's more about which options are valid for `binding.addHandlerAsync`. Especially for `EventType.BindingDataChanged`.

**Comment by sumurthy** [comment]
Will find and assign to the right owner.

**Comment by kbrandl** [comment]
Closing this issue, as I believe the new reference docs provide this info. Please let us know if that's not the case.

https://docs.microsoft.com/en-us/javascript/api/office/office.asynccontextoptions?view=office-js
