### ISSUE TITLE
Office.context.mailbox.item.displayReplyAllForm with attachments not working outlook.live.com

### ISSUE THREAD

**Issue by Nadeermalangadan** [OfficeDev/office-js-docs#764]
Using office.js outlook add-ins, displayReplyAllForm with attachments is opening reply form without attachments in [outlook.live.com](https://outlook.live.com), but in [outlook.office.com](https://outlook.office.com) its working perfect.

Any workaround for this.

script is 
```
Office.context.mailbox.item.displayReplyAllForm(
                    {
                        'htmlBody': template,
                        'attachments': attachments
                    });
```

**Comment by Lauragra** [comment]
Hi, Thanks for reaching out. This repo is primarily for feedback on the documentation. For more specific help with your code, we recommend that you post your question to [StackOverflow](https://stackoverflow.com/search?q=office-js) and tag with [office-js]. If we can help by clarifying the docs, feel free to reopen. Thanks.
