### ISSUE TITLE
Excel 2016 for Mac - instructions?

### ISSUE THREAD

**Issue by workbooks** [OfficeDev/office-js-docs#773]
This article suggest "Choose the File tab, and then choose Options." and discusses use of UNC paths etc.   If I am using a Mac how do I get Excel to load an add-in from a local folder?

Thank you

------------
 
Article:

Issue:

**Comment by Rick-Kirkham** [comment]
To sideload on a Mac, see https://dev.office.com/docs/add-ins/testing/sideload-an-office-add-in-on-ipad-and-mac

**Comment by workbooks** [comment]
This was an issue with the documentation here - will it be fixed?

**Comment by workbooks** [comment]
Thank you.
