### ISSUE TITLE
Question about upcoming enhancements to the Powerpoint JS api ?

### ISSUE THREAD

**Issue by directable** [OfficeDev/office-js-docs#789]
I noticed that word and excel are called out for enhancements. Is there somewhere I can review and suggest functionality for future Powerpoint enhancements?  I looked at the user voice area but it seemed pretty dated.

**Comment by sumurthy** [comment]
We don't have anything to announce yet.. however PowerPoint is in our broader roadmap. As soon as we have any design effort underway, we'll definitely post an open specification to explain the thinking.
