### ISSUE TITLE
links in your readme.md

### ISSUE THREAD

**Issue by draschke** [OfficeDev/office-js-docs#790]
Will only let you know, that your links in your readme.md  (i.e issues and stackoverflow) are wrong.

https://github.com/OfficeDev/office-js-docs/blob/WordJs_1.3_Openspec/reference/word/https:/officesnippetexplorer.azurewebsites.net/#/snippets/word

**Comment by Lauragra** [comment]
Thanks for pointing that out! I just fixed the links.
