### ISSUE TITLE
Typescript Definitions - DialogOptions Interface Missing DisplayInIFrame

### ISSUE THREAD

**Issue by LanceEa** [OfficeDev/office-js-docs#792]
The TypeScript definition published is missing a member on the interface for **DialogOptions**. The following message is thrown by the Typescript compiler indicating that **DisplayInIframe** doesn't exist on interface.

![screen shot 2017-03-21 at 8 56 03 pm](https://cloud.githubusercontent.com/assets/8103374/24178723/e28c29a2-0e78-11e7-9a38-a8678414cecd.png)

Looking in the _node_modules/@types/office-js_ you will see that the interface only has the old _XFrameDenySafe_ available in the interface. But, if you look at your documentation it shows the only available field is the DisplayInIFrame member of the interface.

https://dev.office.com/reference/add-ins/shared/officeui.displaydialogasync

![screen shot 2017-03-21 at 8 50 50 pm](https://cloud.githubusercontent.com/assets/8103374/24178783/3b06210a-0e79-11e7-8b18-7b549e37e280.png)

Here is the Package Information for the types I have installed:

![screen shot 2017-03-21 at 8 51 13 pm](https://cloud.githubusercontent.com/assets/8103374/24178776/348e36f0-0e79-11e7-95e7-3f0475490be8.png)

Currently, the way I have been solving this is to manually add it to the interface but this is inconvenient because any new developer that grabs this project needs to do this and\or anytime I update\install new modules it overwrites those changes. 

Can someone please fix this or if there is a place I can submit a pull-request I would be happy to do so! 😄

**Comment by Lauragra** [comment]
Hi, feel free to submit an update to the topic via PR and we can take a look - just click the pencil icon on this file to make your changes: https://github.com/OfficeDev/office-js-docs/blob/master/reference/shared/officeui.displaydialogasync.md

Thanks,
Laura

**Comment by Rick-Kirkham** [comment]
@LanceEa 
The topic is correct. It is the Typescript types definition file that is out-of-date. You need to make the pull requests on the DefinitelyTyped repo in GitHub.

**Comment by LanceEa** [comment]
@Lauragra - Thanks for the reply. As Rick mentioned the issue is with the Typescript Definition and not the documentation.

@Rick-Kirkham - Thanks! I wasn't sure if it was part of some automated process on your end so that as changes were published to the CDN, would then be pushed automatically to Definitely Typed. I have gone ahead and entered the following pull-request:

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/15315

***NOTE** I only added _displayInIframe_ to the DialogOptions interface. I believe _xFrameDenySafe_ is no longer valid but I left it just in case it needs to be around for legacy reasons. Let me know if you would like me to remove that from the interface as well.

**Comment by Rick-Kirkham** [comment]
If it's not too much trouble, it would be great if you could delete the _xFrameDenySave_ property.

**Comment by LanceEa** [comment]
@Rick-Kirkham - Done 😃 !

**Comment by LanceEa** [comment]
@Rick-Kirkham @Lauragra - Any chance I can get someone from the OfficeDev team to review\approve the pull-request at DefinitelyTyped?

I believe it just needs someone from the OfficeDev Github account to approve it and then it will automatically get committed.

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/15315 

Thanks,
Lance

**Comment by Rick-Kirkham** [comment]
I believe that an admin of the https://github.com/DefinitelyTyped/DefinitelyTyped repo has to approve the pull request. That was the case the last time I made a PR to that repo which was last summer. It takes a few days, but they automatically accept anything that doesn't fail their automated tests. 
I will ask around to see if anyone knows otherwise, but I think you just have to wait a few days.

**Comment by Zlatkovsky** [comment]
@LanceEa , I have given a thumbs-up to your definitely-typed addition.  It generally take a few days for someone from the DefinitelyTyped team to merge in the change.  If you haven't seen it done by mid-next-week, feel free to ping me, and I can see if I can accelerate the process on my end...

Thanks!

**Comment by LanceEa** [comment]
@Rick-Kirkham @Zlatkovsky - Thanks! Appreciate the help and will keep an eye out for it!

FYI...the JSDoc description I included in the PR was just copied & pasted from the main documentation. So, if in the future you want to change it per your suggestion then we should probably change it in both places!

**Comment by Zlatkovsky** [comment]
@LanceEa , let's assume that we want the JS description that I suggested... and let's see if @Rick-Kirkham can update it in the real docs:

> This setting is only applicable in Office Online clients, **and is ignored on the other platforms.**

**Comment by LanceEa** [comment]
@Zlatkovsky - Made the change

**Comment by Rick-Kirkham** [comment]
@LanceEa @Zlatkovsky - Fixed grammar in the source document on GitHub. The new version will be on dev.office.com sometime Tuesday.
