### ISSUE TITLE
getAsync Outlook js function bugs in mobile version

### ISSUE THREAD

**Issue by OriAmir** [OfficeDev/office-js-docs#794]
Hi , I just try to ask this questions in MDN  develop forum and they reffed me to here. 
I write an outlook add-in in js and now I try to customize it to mobile version ( OWA app and browsers).

I success to see my add in in mobile but there is 2 bugs with the getAsync function in mobile:
1. In **compose mode** - getAsync always return null no matter what  we have in the body of  the message . I write a question about it [here](https://social.msdn.microsoft.com/Forums/office/en-US/6c46f458-12a4-4ae4-988b-9bfb742ea7ab/outlook-getasync-method-return-always-null-in-compose-mode-on-mobile-browsers?forum=appsforoffice) and they confirm the bug . My question is if it will be fixed sometime ? Or if someone work on it?

2.  In **read mode** - If the message is bigger then 50,000 characters ( roughly ) so the getAsync  return just part of the message and not all the message .It's return something like the first 47,000 first characters . I don't find any reason for it because in computer I get all message. I also write about it [here](https://social.msdn.microsoft.com/Forums/office/en-US/79b18647-093a-4d9e-8747-2719dcdf8b5e/getasync-function-return-just-part-of-the-message-on-owa-mobile?forum=appsforoffice) but again no one really know exactly.

I check this cases also in iOS and also in android devices in different browsers and in OWA application and this is the same issues..

Hope some one could help

Thank you very much!

**Comment by JFrei86** [comment]
Hi,
Thanks for sharing this with us. To clarify, are you talking about body.getAsync in mobile OWA? In OWA mobile there is a known issue that in compose body.getAsync is always returning null. We have fixed this and it should become available to Office 365 users in the next week or two.

As for the read scenario, this appears to be a bug specifically in body.getAsync in Tablet and Mobile versions of OWA. We have filed this bug and will try to address it as soon as possible.

Thanks again!

**Comment by OriAmir** [comment]
@JFrei86 Thanks! Yes,I talking about OWA application and also when I get into OWA from chrome/safari etc..
I will check it again in the next weeks and I hope that it will be solved.
**Thanks** again!

**Comment by jasonjoh** [comment]
Thanks @OriAmir, glad we could help! For future problems with the APIs, please post on StackOverflow and tag your post with `outlook-web-addins`. GitHub issues here should be limited to problems with the documentation itself.

**Comment by OriAmir** [comment]
@jasonjoh  @JFrei86 
Hi, first problem looks like solved but second it's still here , if message is too long I get just part of the message.. there is something I could do or working to fix this bug?

Thank you very much .
