### ISSUE TITLE
Unable to retrieve Custom Properties [office-js]

### ISSUE THREAD

**Issue by AhmedVali** [OfficeDev/office-js-docs#800]
Hello Experts,

I am trying to set custom properties to my Word document using the below code:
Word.run(function (context) { 
context.document.properties.customProperties.add("PropertyName", 1234); 
return context.sync() })

I am using this office.js :: https://appsforoffice.microsoft.com/lib/beta/hosted/office.js.
And I'm on Office version 1609 (Build 7369.2120) Deferred Channel.

What I am trying to do is:
1. Created a task pane add in with a button to Set Custom Properties.
2. Whenever I click on the button, the function is getting called and there is no any error as such.
3. But when I try to see the custom properties through File-->properties-->Advanced Properties-->Custom. I don't see the property added there. Do we have to save the file explicitly in order to view the properties ?

**Comment by sumurthy** [comment]
No need to save the file. It should just work. Can you use the build Version 1612 (Build 7668.1000) or later or later?

**Comment by sumurthy** [comment]
No response.
