### ISSUE TITLE
Get content body

### ISSUE THREAD

**Issue by j4m1** [OfficeDev/office-js-docs#802]
Maybe my question is too basic, I don't know.

The thing is I cannot find how to get only one mail instead of all the conversation, which I get with:

`Office.context.mailbox.item.body.getAsync(
          "html",
          { asyncContext: "This is passed to the callback" },
          function callback(result) {
              CKEDITOR.instances.taskDesc.setData(result.value);
          });`

Please, help!

**Comment by jasonjoh** [comment]
Hi @j4m1! I guess you're talking about the contents of the previous messages within a mail thread? Unfortunately the API has no way to ask for just the content of the current message with the old thread content filtered out. You can provide feedback on the APIs here: https://officespdev.uservoice.com/.
