### ISSUE TITLE
Version differences: OfficeJS in CDN vs Nuget

### ISSUE THREAD

**Issue by ujwalr** [OfficeDev/office-js-docs#832]
We are referencing Office JS in our code using the URL 'https://appsforoffice.microsoft.com/lib/1.1/hosted/office.js', we have noticed that the version of this JS file is '16.0.8101.1000' while the latest nuget package has an older version of JS file.

We have also seen some performance issues last week, but we aren't sure if that was because of the change in Office.js file in CDN, and we ended up rewriting some code to alleviate the issues. Is there a place where we can see release history and changelog for the JS files being published to CDN.

Also, what is your recommendation on whether we should point to CDN path for Office.JS or use nuget package, which one is more stable and safer for production apps?

------------
 
Article:

Issue:

**Comment by mlafleur** [comment]
The guidance is to always reference the CDN in production. You should only use a local copy for dev/test scenarios. 

Also note, if you're planning to publish to the Office Store this is a validation policy (7.15). Referencing anything other than the CDN will result in the submission being rejected.

**Comment by ujwalr** [comment]
Thanks for the update.

Is there a place where we can get a change log as to when CDN is getting updated and what changes are being made?

**Comment by sumurthy** [comment]
We don't have a change log that shows all of the changes. The CDN can change as frequently as a week. The major changes are announced as part of blogs, open-specs, etc. However, some of the changes are really small such as bug fixes and are not documented anywhere. This maybe a good follow-up action for us to take.
