### ISSUE TITLE
Word add-in stops working after dialog.close is fired. Office JS

### ISSUE THREAD

**Issue by naveed-butt** [OfficeDev/office-js-docs#853]
I have been working on an Office365 application where I opened a dialog and after some kind of activity when I close the dialog with dialog.close(). It works perfectly fine but ribbon button stops working and next time it will not show that same dialog again.

`Office.context.ui.displayDialogAsync("https://" + location.host + "/Dialog.html", { width: 90, height: 90, requireHTTPS: true }, function (asyncResult) {
        dialog = asyncResult.value;
        dialog.addEventHandler(Office.EventType.DialogMessageReceived, processMessage);
        if (asyncResult.status !== Office.AsyncResultStatus.Succeeded) {
            return;
        }
    });`

and here is my processMessage function

`function processMessage(arg) {
try{
    var messageFromDialog = JSON.parse(arg.message);

    var base64 = messageFromDialog.image.split(",")[1];
    Word.run(function (context) {
        var body = context.document.getSelection();
        body.insertInlinePictureFromBase64(base64, Word.InsertLocation.replace);
        return context.sync();
    }).catch(function (error) {
        app.showNotification("Error: " + JSON.stringify(error));
        if (error instanceof OfficeExtension.Error) {
            app.showNotification("Debug info: " + JSON.stringify(error.debugInfo));
        }
    });
    if (messageFromDialog.messageType === "dialogClosed") {
        dialog.close();
    }
} catch (ex) {
    console.log("Exception " + ex);
}
}`
Thanks in advance :)

**Comment by Rick-Kirkham** [comment]
@naveed-butt 
Please raise this question on StackOverflow and tag it with "office-js".

**Comment by naveed-butt** [comment]
Already posted on Stackoverflow with very few activity. Looks like no one is looking at the issue... 
[http://stackoverflow.com/questions/42950678/word-add-in-stops-working-after-dialog-close-is-fired-office-js?noredirect=1#comment74157073_42950678](http://stackoverflow.com/questions/42950678/word-add-in-stops-working-after-dialog-close-is-fired-office-js?noredirect=1#comment74157073_42950678)
