### ISSUE TITLE
Document.getFilePropertiesAsync method documentation is inconsistent

### ISSUE THREAD

**Issue by TheSamsterZA** [OfficeDev/office-js-docs#860]
Here is the [documentation page for `Document.getFilePropertiesAsync`](https://dev.office.com/reference/add-ins/shared/document.getfilepropertiesasync). Note that this page says that this method is supported in Office Online (specifically, Word Online).

Here is the [documentation page for Office common API requirement sets,  methods not in a requirement set](https://dev.office.com/reference/add-ins/requirement-sets/office-add-in-requirement-sets#methods-that-arent-part-of-a-requirement-set). Note that this page says that `Document.getFilePropertiesAsync` is NOT supported on Word Online.

I am bringing this up because my add-in specifies `Document.getFilePropertiesAsync` in its manifest but today it is not available in Word Online. It cannot be found on the Office Store from Word Online, and its page does NOT list Word Online anymore.

When I submitted the add-in last year, it was definitely available on Word Online.

Using the [Microsoft Office Add-in Manifest Validator](https://github.com/OfficeDev/office-addin-validator) against the manifest shows that the add-in is supported on Word Online:

![image](https://cloud.githubusercontent.com/assets/4981594/25466268/bd8f4c30-2b4a-11e7-8638-20c8c04c348b.png)

So, either the documentation is incorrect (and inconsistent) or the Office Store is incorrectly filtering out my add-in from Word Online. Please help.

**Comment by Rick-Kirkham** [comment]
Thanks for bringing this to our attention. I am investigating.

**Comment by Rick-Kirkham** [comment]
We have established that getFilePropertiesAsync is supported by Word Online. I will get the second document that you linked to corrected. Are you still having problems with the store?

**Comment by TheSamsterZA** [comment]
Hi @Rick-Kirkham,

> We have established that getFilePropertiesAsync is supported by Word Online. I will get the second document that you linked to corrected.

Thanks, that's good to hear.

> Are you still having problems with the store?

No, not in terms of getting my add-in re-validated for Word Online. That was done a few weeks back. I am now going through Microsoft Support in order to get my publisher display name updated, and to be honest I feel like it should not take this long to do.

I do have another issue which I think requires a change to the docs: [the page for content controls](https://dev.office.com/reference/add-ins/word/contentcontrol). Specifically, I think that page should call out prominently that **editing of content controls are not (yet) supported in Word Online**.

It is distressing that we as OfficeJS add-in developers are led to believe that we can, in effect, "write once, run anywhere" on Windows, Mac and Online - yet, in reality certain parts of the API are not supported on certain platforms.

Please go through all documentation and re-validate what APIs work across platforms, which are not yet supported, and which will never be supported. I think having a page dedicated to this, that is always up-to-date, would save everyone hours if not days of development time.

**Comment by Rick-Kirkham** [comment]
@TheSamsterZA 
Could you make a separate issue of your last 3 paragraphs above? The problem will get handled faster that way. Thanks.
