### ISSUE TITLE
Unable to load Custom Properties of a docx file in Office 2013

### ISSUE THREAD

**Issue by cyberexe** [OfficeDev/office-js-docs#862]
Hi,

I am working on an Add in for Word that needs to be supported for Office 2013.
The Add in loads a document with custom properties.
I am not able to get those properties via any way.
If i transform it to a zip file i can see the xml file in the docProps folder, but the custom properties are not loaded and accessible via the Add in.

Thnx in advance.

**Comment by Rick-Kirkham** [comment]
@cyberexe 
The Issues for this repo are primarily intended for reporting errors in the documentation. Please post your question on StackOverflow and tag it with **office-js**. You'll get an answer sooner and the whole community will benefit from the answer. Thanks!
