### ISSUE TITLE
Internet Explorer issue

### ISSUE THREAD

**Issue by thorild** [OfficeDev/office-js-docs#866]
Hi!

We have trubles using the API in Internet Explorer, is this a known issue and maybe a fix under way?

The Visio loads fine but we can't for instance detect what shape was clicked etc. Problem goes away if you change the compatibility mode meta tag.

BR

Fredrik

**Comment by rahul-mi** [comment]
There are no known issues in IE and it should work fine in IE 11.  

For posting queries on existing APIs, you can use 
Answers: https://answers.microsoft.com/en-us/msoffice/forum/msoffice_visio
TechNet: https://social.technet.microsoft.com/Forums/office/en-US/home?forum=visiogeneral

For new feature requests, you can use UserVoice where others can also upvote your feature request. https://visio.uservoice.com/forums/368199-visio-online
