### ISSUE TITLE
Visio manipulating the chrome and visio

### ISSUE THREAD

**Issue by thorild** [OfficeDev/office-js-docs#867]
Hi, 

We would love to see some capabilities around setting shape colors dynamically via the API (as an example) another example would maybe be hiding the page tabs - Antyhing regarding this in the back log?

**Comment by rahul-mi** [comment]
We have shape.Fill to se the shape color in our backlog. Regarding hiding page tabs, you can achieve this today by using: application.showToolbars =false;
You can find an example related to this on https://dev.office.com/reference/add-ins/visio/application.
