### ISSUE TITLE
`context.document.body.insertOoxml` breaks documents, crashes word

### ISSUE THREAD

**Issue by Thiez** [OfficeDev/office-js-docs#874]
When I use `insertOoxml` with the 'replace' parameter, Word will insert extra content at the end. For example, when using the following code in [Script Lab](https://dev.office.com/blogs/script-lab-a-microsoft-garage-project), with a new, empty word document:

```es6
$("#run").click(run);

function run() {
    Word.run(function (context) {
        var ooxml = context.document.body.getOoxml();
        return context.sync().then(function () {
            console.log(ooxml.value.length);
            context.document.body.insertOoxml(ooxml.value, Word.InsertLocation.replace);
            return context.sync();
        });
    });
}
```

Every time you trigger this code, the word document will acquire an additional paragraph at the end of the body. It gets crazier when the document ends in a content control: take a new document, insert a new rich text content control. Triggering `run` will duplicate the content control and insert it inside itself (so you have two content controls, where one is contained by the other). Clicking `run` a couple of times will create a lot of nested content controls and slow down Word to a crawl. Inserting a plain text content control and triggering 'run' twice will crash word (appears to be a null pointer dereference).

This is not a problem related to Script Lab, but using Script Lab is the easiest way to reproduce it.

Word version: 1703, build 7967.2139, 2016 MSO (16.0.7927.1020) 32-bit.

Expected behavior: Word does not crash and does not introduce extra content.

**Comment by Rick-Kirkham** [comment]
@Thiez 
This looks like an important issue in the platform. But the issues for this repo are intended to report errors in the documentation. Please raise this issue on StackOverflow and tag it with "office-js". This will get the attention of the right people faster.
