### ISSUE TITLE
owa for ios and dialog

### ISSUE THREAD

**Issue by EliseoAzpeitia** [OfficeDev/office-js-docs#897]
When I try open a dialog in owa for iOS, this show the same message IE for windows. 
In Windows the solution is to add the site as trusted but How do I do this in iOS? The help link redirect to help for IE 11

![capture from iphone](https://cloud.githubusercontent.com/assets/6379265/26127758/a87ff8a6-3a60-11e7-8ad2-8766546c1c58.jpg)

**Comment by jasonjoh** [comment]
Hi @EliseoAzpeitia. From the message, I'm assuming that you're trying to open a dialog to an external website? This isn't supported per the documentation for `displayDialog`:

> The initial page must be on the same domain as the parent page. After the initial page loads, you can go to other domains.

If that's not what you're doing, could you provide some more information so I can investigate?

**Comment by adhorvath** [comment]
It possible to add trusted domains in manifest file. You can use [AppDomains](https://dev.office.com/reference/add-ins/manifest/appdomains) node to achive this. You can eliminate security message if you add domain into your manifest what you want to open in dialog.

**Comment by EliseoAzpeitia** [comment]
I added the domain in manifest file, and this works in outlook for ios,
web, desktop, etc. but it not works in owa for iOS (app).

2017-06-06 16:37 GMT-03:00 Adam <notifications@github.com>:

**Comment by jasonjoh** [comment]
> I added the domain in manifest file, and this works in outlook for ios,
web, desktop, etc. but it not works in owa for iOS (app).

As I mentioned, opening a dialog to a URL that isn't on the same domain as your add-in isn't supported. You can open to a page and navigate to other URL's, but the initial URL must be on the same domain.
