### ISSUE TITLE
The table does not show well

### ISSUE THREAD

**Issue by Hongbo-Miao** [OfficeDev/office-js-docs#908]
Article:
https://dev.office.com/docs/add-ins/excel/format-tables-in-add-ins-for-excel?product=excel

Issue: 
The table does not show well, like below
![image](https://cloud.githubusercontent.com/assets/3375461/26429905/ac610a16-409e-11e7-93ea-4ac4cb9f9009.png)

**Comment by keyur32** [comment]
The rendering issue is fixed, closing this for now.  We will still want to re-write this topic to make it easier to read as it is one giant table in a table
