### ISSUE TITLE
ChartCollection.Add method doesn't specify all of the valid types

### ISSUE THREAD

**Issue by slabereemsft** [OfficeDev/office-js-docs#912]
The documentation for type contains "Etc" instead of specifying all of the types.  This makes it impossible for the developer to determine how to use the types aren't list in the example.

type
string
Represents the type of a chart. Possible values are: ColumnClustered, ColumnStacked, ColumnStacked100, BarClustered, BarStacked, BarStacked100, LineStacked, LineStacked100, LineMarkers, LineMarkersStacked, LineMarkersStacked100, PieOfPie, **etc.**

**Comment by sumurthy** [comment]
Added chart types.
