### ISSUE TITLE
YellowThreeArrows causes invalid argument error

### ISSUE THREAD

**Issue by tomjebo** [OfficeDev/office-js-docs#930]
Article:
ConditionalFormatCollection Object (JavaScript API for Excel) 

[add(type: string)](https://github.com/OfficeDev/office-js-docs/blob/master/reference/excel/conditionalformatcollection.md#addtype-string)

Issue: 
If you use the example for: 
add(type: string)

You will get an error because of this line: 
 conditionalFormat.iconOrNull.style = "YellowThreeArrows";

I found the doc on icon sets and it shows all the valid enumerations: 
https://dev.office.com/reference/add-ins/excel/iconsetconditionalformat?product=outlook

style	string	If set, displays the IconSet option for the conditional format. Possible values are: Invalid, **ThreeArrows**, ThreeArrowsGray, ThreeFlags, ThreeTrafficLights1, ThreeTrafficLights2, ThreeSigns, ThreeSymbols, ThreeSymbols2, FourArrows, FourArrowsGray, FourRedToBlack, FourRating, FourTrafficLights, FiveArrows, FiveArrowsGray, FiveRating, FiveQuarters, ThreeStars, ThreeTriangles, FiveBoxes.

Perhaps the example code should be updated?

**Comment by sumurthy** [comment]
Are you saying that we should support `YellowThreeArrows`? It is not one of the supported values.

**Comment by tomjebo** [comment]
@sumurthy I think I was saying to change the sample code in the documentation to use "ThreeArrows" instead of "YellowThreeArrows".
