### ISSUE TITLE
Visio.js api not loading correctly

### ISSUE THREAD

**Issue by Kofkegaze** [OfficeDev/office-js-docs#932]
Hi,

We are having problem with the visio api. we use the diagram for navigation purposes on a sharepoint site.
It was working untill yesterday, were we get this message.
![image](https://user-images.githubusercontent.com/29433966/27136664-2f47ffce-511c-11e7-9967-1ccc61a394f7.png)

There hasnt been any changes on the way we embedd the iframe nor any part of the code.
any ideas?

**Comment by rahul-mi** [comment]
Hi,
Thanks for reaching out. We are working on this issue at priority and expect to resolve it soon.
Apologies for the inconvenience.

Regards
Rahul Mittal | Program Manager | Microsoft Visio

**Comment by Kofkegaze** [comment]
Hi Rahul.

Thanx for the quick response, i qould love to hear when its resolved! 
The whole solution depends on the Visio content.

**Comment by rahul-mi** [comment]
Hi Kofkegaze

While we are investigating and working on this issue at priority, will you be able to share the code snippet where you are initializing the Visio iFrame?
Please remove/rename anything you believe is confidential.

Regards
Rahul Mittal | Program Manager | Microsoft Visio

**Comment by Kofkegaze** [comment]
Hi Rahul,
Here is the snippet of initialixing the iFrame.
```
getProcessMapUrl().then(function (processMap) {
    var iFrameHost = document.getElementById("cibus-visio-iframeHost");
    var url = processMap.results[0].ServerRedirectedEmbedUrl;
    url = url.replace("action=default", "action=embedview");
    url = url.replace("action=view", "action=embedview");
    url = url.replace("action=interactivepreview", "action=embedview");
    var session = new OfficeExtension.EmbeddedSession(url, { id: "embed-iframe", container: iFrameHost });
    session.init().then(function () {
         OfficeExtension.ClientRequestContext._overrideSession = session;
         jQuery("#embed-iframe").css({ "width": "100%", "height": "480px" });
         resolve();
     });
});
```

Thanx!

**Comment by rahul-mi** [comment]
Hi Kofkegaze

We believe that the issue is resolved now. Could you please confirm?

Also, we would like to connect with you (rahulmi AT microsoft.com) to understand your experience of using the new APIs. What kind of scenarios you are building, any feedback or functionality you are missing in the current set?

Regards
Rahul Mittal | Program Manager | Microsoft Visio

**Comment by Kofkegaze** [comment]
Hi Rahul,

Yes we noticed that the Api was working yesterday! Thanx for the quick response.

Sure, I'll write you a email later today, explaining more in depth the experince and the issues we have had with the api.

Regards
Kovan

**Comment by rahul-mi** [comment]
Hi Kofkegaze

Please do share the scenarios that you are trying to build and any feedback or functionality you are missing in the current set?

Regards 
Rahul Mittal | Program Manager | Microsoft Visio
