### ISSUE TITLE
Cannot load Word (15.35) Add-in as per documentation

### ISSUE THREAD

**Issue by sureshjoshi** [OfficeDev/office-js-docs#946]
I'm trying to get some of the sample code working to see a custom add-in running in Word for Mac 2016 (15.35)

I copied and pasted the HTML/JS/Manifest code mentioned here: https://dev.office.com/docs/add-ins/word/word-add-ins and I ran it in both/either a python server and nodejs.

I changed my default source location to http://0.0.0.0:8000 or http://localhost:3000 (depending on which server), restarted Word, went to Developer -> Add-ins, but couldn't see any custom plugins.

Is there something I'm missing? Should I be using SSL? Are the docs out of date? Permissions?

Note: I've also tried installing this manifest directly (https://github.com/OfficeDev/Office-Add-in-Commands-Samples/tree/master/Word) with no luck.

Equally no luck using the Yeoman generated code (https://dev.office.com/docs/add-ins/get-started/create-an-office-add-in-using-any-editor).

**Comment by sureshjoshi** [comment]
Damn... Wrote too soon - just paid closer attention to this page:
https://dev.office.com/docs/add-ins/testing/sideload-an-office-add-in-on-ipad-and-mac

![screen shot 2017-06-20 at 23 54 37](https://user-images.githubusercontent.com/3823045/27366388-dd4960a8-5613-11e7-93a5-9ab5f75a3bdf.png)

I'd propose that the documentation here could be cleared up by being careful about the term "Developer Add-ins" as there is also a Developer -> Add-in button/pane

![screen shot 2017-06-20 at 23 56 19](https://user-images.githubusercontent.com/3823045/27366438-1c15af3a-5614-11e7-8e4a-2f2ee7f8238e.png)

**Comment by Lauragra** [comment]
Thanks for the feedback. I updated the text in this topic to hopefully make it a little bit more clear!
