### ISSUE TITLE
Can't call rest api from outlook html email?

### ISSUE THREAD

**Issue by megancooper** [OfficeDev/office-js-docs#951]
I am creating a VTSO for Outlook and it has a ribbon that sends an email to a user containing html. This html has an element that is supposed to call an embedded script function and call a rest api, but for some reason its not working. Does outlook not support this?

Here is the stackoverflow post I made.

Here is my code:
```
<a href="#" onclick="markAsDone();" target="_blank" style="font-size: 16px; font-family: Helvetica, Arial, sans-serif; font-weight: normal; color: #ffffff; text-decoration: none; display: inline-block;">I am done working on this build. &rarr;</a>
<script type="text/javascript">
      function markAsDone() {
           var xhttp = new XMLHttpRequest();
           xhttp.open("POST", "http://localhost:1337/UserDone", false);
           xhttp.sendRequestHeader("Content-type", "application/json");
           xhttp.send();
       }
</script>
```

**Comment by mlafleur** [comment]
Office.js is a library for building add-ins for Outlook, Word, PowerPoint, etc.. It provides a cross-platform add-in platform and effectively replaces VSTO as the primary extensibility story for Office. This repository is particular only covers the documentation for Office.js, not the library itself. 

That said, to answer your question: While email clients have been using HTML for formatting for many years, it is not traditional HTML. Emails don't have a DOM, scripting capabilities, or support for external css for example. Support is also radically different between email clients (i.e. GMail supports some tags not supported by Outlook and vice versa). When constructing HTML emails you should keep things as simple as possible (no scripts, inline CSS, HTML 1.1).
