### ISSUE TITLE
Update TOC file

### ISSUE THREAD

**Issue by MIchaelMainer** [OfficeDev/office-js-docs#96]
The following files aren't linked in the TOC.

develop/office javascript api/support for content and task pane add-ins
excel/format tables in add-ins for Excel

Also, is the office mix content supposed to be under PowerPoint?

**Comment by Lauragra** [comment]
This issue appears to be fixed on the site:
excel/format tables in add-ins for Excel

Pls. verify - http://dev.office.com/docs/add-ins/excel/format-tables-in-add-ins-for-excel

Yes, Office Mix is under PowerPoint.

Will fix the support topic issue.

**Comment by MIchaelMainer** [comment]
Verified that the excel/format tables in add-ins for Excel works as expected.

**Comment by Lauragra** [comment]
This fix is now live as well: http://dev.office.com/docs/add-ins/develop/support-for-task-pane-and-content-add-ins

Closing the issue - thanks!
