### ISSUE TITLE
Internal error:5001 in binding.setDataAsync

### ISSUE THREAD

**Issue by PawelK95** [OfficeDev/office-js-docs#973]
I'm currently using Microsoft Office Professional in version 16.0.4266.1001, and it has Word JavaScript API 1.1. My function binding.setDataAsync(result.value) stopped working but I'm sure it worked in last week. It returns internal error 5001. Has anybody got any idea why this happend?

![blad setdataasync](https://user-images.githubusercontent.com/17577759/28155548-8a49b27e-67af-11e7-9d74-9886564bf9de.PNG)

Thank you for reply :)

**Comment by PawelK95** [comment]
Please help, I really need Your help :D

**Comment by mlafleur** [comment]
Could you post this over at [StackOverflow](https://stackoverflow.com/questions/tagged/office-js) and tag it with `office-js`? SO is the proper place for questions like this (and far more likely to receive a quick response).
