### ISSUE TITLE
Unable to create binding using current selection and specified binding type

### ISSUE THREAD

**Issue by PawelK95** [OfficeDev/office-js-docs#974]
I''m currently using Microsoft Office Professional in version 16.0.4266.1001, and it has Word JavaScript API 1.1.

My function addFromSelectionAsync stopped working but I'm sure it worked recently. The result.status is Failed. Here is my code:
![addfromselectionasync](https://user-images.githubusercontent.com/17577759/28155590-aef2889e-67af-11e7-8db7-514b81b6f72e.PNG)

And here are error message I get:

Error: Unable to create binding using current selection and specified binding type.
I'm sure Office.BindingType.Text is correct because I'm selecting text in the document

**Comment by PawelK95** [comment]
Please help, I really need Your help :D

**Comment by Rick-Kirkham** [comment]
@PawelK95 
Please ask technical questions like this on StackOverflow. Be sure to tag the question "office-js".
