### ISSUE TITLE
Office.EventType.DocumentSelectionChanged inconsistent slow

### ISSUE THREAD

**Issue by wvrzel** [OfficeDev/office-js-docs#976]
I wrote the following code for debugging puposes:

    (function () {
        "use strict";

        // The initialize function is run each time the page is loaded.
        Office.initialize = function (reason) {
            

            $(document).ready(function () {

                // Use this to check whether the API is supported in the Word client.
                if (Office.context.requirements.isSetSupported('WordApi', 1.1)) {
                    // Do something that is only available via the new APIs
                    
                    Office.context.document.addHandlerAsync(Office.EventType.DocumentSelectionChanged, onSelectionChanged);
                    
                    $('#status').html('Add-In Seite geladen.');
                }
                else {
                    // Just letting you know that this code will not work with your version of Word.
                    $('#status').html('This code requires WordApi 1.1 or greater.');
                }
            });
        };
        
        var c = 1;
        function onSelectionChanged(eventArgs) {
            c++;
        $('#status').html('onSelectionChanged() call'+c+);
        }
    })();

This code only reacts sometimes on changes. Sometimes reeaaly slow. Sometimes (I guess, if it is too slow and there have been multiple changes in between, it does not recognize them und prints `onSelectionChanged() call 4` after a while, even though, there have been many more changes.
Other times, if I close Word, and open it again, it just works as a charm. Then I close it and open it again, and again, it fails - It is completely inconsistant. Thereby this feature is effectively not usable.

I tested this on different machines, different versions of Windows and it occures independend of the utilization of the system.

**Comment by wvrzel** [comment]
I was able to reproduce this with the current Word Version 1706 (Build 8229.2086)

**Comment by Rick-Kirkham** [comment]
@wvrzel 
Please ask this question on StackOverflow and tag the question "office-js". The issues for this repo are intended for reporting problems with the documentation, not technical questions. Thanks.

**Comment by wvrzel** [comment]
@Rick-Kirkham I thought so, but there are a lot of technical issues here, some of them assigned.
So, what is the official way to file a technical bug for office-js?

**Comment by Rick-Kirkham** [comment]
@wvrzel 
Not everyone has gotten the word that technical questions should be referred to StackOverflow, so some of them do get answered. We're trying to be more consistent. 
To my knowledge, there is no official way to file a bug. The process is to raise the question on StackOverflow. Microsoft employees, including me, monitor those questions. If we conclude that it is a bug, we'll indicate that in our answer on SO and file the bug internally.

**Comment by wvrzel** [comment]
@Rick-Kirkham Thank you for your answer. I will repost this on Stackoverflow, but (just for yout information) I feel like the response-loop at github is much shorter.
