### ISSUE TITLE
Visio.js API hyperlink missing when ? character in url

### ISSUE THREAD

**Issue by Kofkegaze** [OfficeDev/office-js-docs#977]
We are facing an issue when rendering an Visio Diagram with shapes that have hyperlinks.

When getting the hyperlinks programmatically via the api, the Url property is partly missing.

We have reduced the problem to the '?' character in the url? There is no problem when opening the link but the URL property of the shape is a corrupt url.

```
Visio.run(function (ctx) {
    var page = ctx.document.getActivePage();
    var shape = page.shapes.getItem(args.shapeNames[0]);
    shape.hyperlinks.load();
    return ctx.sync().then(function () {
        if (shape.hyperlinks.items.length) {
            var url = shape.hyperlinks.items[0].description || "";

            if (!url.match(/vdw:\/\//i)) {
                window.location.href = url;
            }
        }
    });
}).catch(Cibus.onError);
```

The Url is https://site.com/subsite/item3 when code is running!

**Comment by rahul-mi** [comment]
Hi,

Thank you for reaching out. We have reported the issue internally and will be coning up with a fix soon.

Regards
Rahul Mittal | Program Manager 2 | Microsoft Visio

**Comment by rahul-mi** [comment]
This issue is now resolved. We have provided the API [Hyperlink.extraInfo](https://dev.office.com/reference/add-ins/visio/hyperlink), that provides the missing URL.
