### ISSUE TITLE
Long time of inserting HTML to content controller

### ISSUE THREAD

**Issue by PawelK95** [OfficeDev/office-js-docs#980]
I'm currently developing Microsoft Office add-in on Word Online. I have large amount of content controllers (more than 100), and I have to replace in every content controller one stylled text to another in one action. For example

"**Document** blabla _nr 1_" to "**Document** blabla _nr 2_"

Only numbers changes in this oparation. So my problem is that I'm using function contentController.insertHTML(styled html text) to achieve this result, but it takes a very long time for such large number of content controllers. For 100 content controller it takes about 1 min to change it all! **Has anybody got idea how can I do it much faster?**

Thank You for reply :)

**Comment by Rick-Kirkham** [comment]
@PawelK95 
Please raise technical questions like this on StackOverflow. Be sure to tag the question "office-js".
