### ISSUE TITLE
ContentControl.insertText throws exception in Word Online

### ISSUE THREAD

**Issue by DanHopkins-TGI** [OfficeDev/office-js-docs#981]
I am developing a Word add-in that utilizes [ContentControl.insertText](https://dev.office.com/reference/add-ins/word/contentcontrol#inserttexttext-string-insertlocation-string).  According to the documentation, this method is provided by [WordApi requirement set 1.1](https://dev.office.com/reference/add-ins/requirement-sets/word-api-requirement-sets), which is supported in Office Online. Furthermore, the documentation for [ContentControls ](https://dev.office.com/reference/add-ins/word/contentcontrol) lists Office Online as being supported and does not mention any exceptions when it comes to using that particular method.

That said, when I run the add-in in native Word 2016, everything works fine, but when I run it in the Word Online environment, it fails with the following exception:

```
code:"NotAllowed"
errorLocation:"ContentControl.insertText"
message:"The action isn’t supported in Word Online. Check the OfficeExtension.Error.debugInfo for more information."
```
For reference, I am using it like so:

`control.insertText(heading.Text, 'Replace');`

I also tried running the example provided in the documentation, with the same results: it works in Word 2016, but fails with the above exception in Word Online.  Is this functionality meant to be supported in Office Online, and thus a bug, or not yet supported?

**Comment by sunjiajia** [comment]
Hi, I'm an engineer from MS. Could you share me the document and the script code.

**Comment by DanHopkins-TGI** [comment]
Good afternoon!

I apologize for the delayed reply.  I have been doing some further testing to see if I can narrow down the issue, and have setup a simple scenario to demonstrate the problem.  For simplicity, I adapted the code from the documentation like so:

```
$(function () {

    Office.initialize = function (reason) {

        // Only support Word 2016 or newer for now
        if (!Office.context.requirements.isSetSupported('WordApi', 1.1)) {
            return;
        }

        Word.run(function (context) {

            // Load content controls in test document
            var contentControls = context.document.contentControls;
            context.load(contentControls, 'id');

            return context.sync().then(function () {

                // Get second content control (heading control)
                var control = contentControls.items[1];

                // Queue commands to enable editing, replace text, and disable editing
                control.cannotEdit = false;
                control.insertText('Hello, world', 'replace');
                control.cannotEdit = true;

                return context.sync()
                    .then(function () {
                        console.log('Success!');
                    });
            });
        })
        .catch(function (error) {
            console.log('Error: ' + JSON.stringify(error));
            if (error instanceof OfficeExtension.Error) {
                console.log('Debug info: ' + JSON.stringify(error.debugInfo));
            }
        });
    };
});
```

One thing to note is that, for our needs, we are using nested ContentControls with the 'cannotEdit' flag initially set.  Before inserting text, we disable the flag, insert the text, and then re-enable it.  

I have also attached two documents:  ContentControl_Succeed.docx and ContentControl_Error.docx.  The above script seems to run just fine in native Word 2016 for both documents, as well as when opening the first in Word Online--it is only the latter that throws the exception, and only in Word Online.  If you enter Design Mode in Word and show formatting symbols, you'll see that each document has two ContentControls--one nested in the other--and that the only difference is that the latter has an additional carriage return just after the Heading control, within the Container.

Any input you could provide would be most appreciated!  Thank you!

**Comment by sunjiajia** [comment]
Thanks for sharing the docs and script code. We have looked into this issue and found that it is caused by a known issue. We are now focusing on fixing this known issue. 

I suggest you some alternative ways:
Suggestion 1: Keep the outer container and the inner heading control in the same paragraph, just like the ContentControl_Succeed.docx does. 
Suggestion 2: Insert a tiny blank space after the heading control boundary.

**Comment by DanHopkins-TGI** [comment]
Thank you for looking into it and providing alternative suggestions!  #2 works great for our purposes.
