### ISSUE TITLE
refresh URL within PowerPoint app problems

### ISSUE THREAD

**Issue by bkyileo** [OfficeDev/office-js-docs#986]
I create a context-based  PowerPoint add-ins programs
I want to refresh URL and new page will be seen within PowerPoint
the code like below : 
 href="xxx.com" target="_self"  demo 
but when I click this text the add-ins program generate a web page out of the powerpoint app
and display in a new browser。
how can i fix it .thank you~~

**Comment by Rick-Kirkham** [comment]
@bkyileo 
We use the Issues for this repo to report errors in the documentation. For technical questions like this, please ask the question on StackOverflow. Be sure to tag the question "office-js".
