### ISSUE TITLE
Can't insert ContentControl over the table if it has different borders in rows

### ISSUE THREAD

**Issue by AndrewGorovoy** [OfficeDev/office-js-docs#988]
If table which i process have different borders, it is impossible to insert content control over it. Trouble only in word online. In desktop it works.
Code example:
```javascript
        Word.run(async (context) => {
            let tables: Word.TableCollection = context.document.body.tables;
            tables.load();
            await context.sync();
            let rng1 = tables.items[0].getParagraphBefore().getRange("After");
            let rng2 = tables.items[0].getRange("After");
            let ccRng = rng1.expandTo(rng2);
            ccRng.insertContentControl();
            return context.sync();
        }).catch((error) => {
            this.errorEmitter.emit(error);
        });
```
Table example:
[differentBorders.docx](https://github.com/OfficeDev/office-js-docs/files/1159044/differentBorders.docx)
![img](https://user-images.githubusercontent.com/30073512/28366452-734891f4-6c95-11e7-96b6-3cdc3eb384d8.png)

**Comment by Rick-Kirkham** [comment]
@AndrewGorovoy 
Please ask this question on StackOverflow and be sure to tag the question "office-js".
