### ISSUE TITLE
Addin project structure for Angular 2 unsing yo man

### ISSUE THREAD

**Issue by s1728k** [OfficeDev/office-js-docs#999]
Hi 

I generated a project structure for angular using yo man. but i see controllers used in angularjs inside the ts file. 
//-------------
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import { AppModule } from './app.module';

Office.initialize = function () {
  const platform = platformBrowserDynamic();
  platform.bootstrapModule(AppModule);
};
//----------------
i used this snippet in main.ts in the project structure created by angular-cli but then manifest file i dont have

I copied the manifest file generated from yo man and put it in this structure then also it did not work.

with the above code snippet I  am not able to serve angular project only.

need help on project structure for angular 2

**Comment by Rick-Kirkham** [comment]
@s1728k 
Please ask this question on StackOverflow and tag it with "office-js". The issues for this repo are intended to report problems with the documentation, not a forum for technical help. Thanks for your interest in Office Add-ins!
